import { describe, expect, it } from 'vitest';
import { createMatch, issueCommand, refreshVisibility, stepGame } from '../src/core/simulation';
import { economicState, economyGatherFactor, economyProductionFactor, economyResearchFactor, ECONOMY_RULES, burnEconomyAt } from '../src/core/economy';
import { saveGame, loadGame } from '../src/core/saves';
import { PlayerView } from '../src/core/observation';
import { validateCommand } from '../src/core/commands';
import { validateEconomyState } from '../src/core/economy-validation';
import type { Entity, GameState, ResourceNode, Side } from '../src/core/types';
function fixture():GameState {const s=createMatch({map:{seed:4127,size:'small'},players:[{id:0,teamId:0,factionId:'orcs',controller:'external',handicap:{startingResources:{wood:5000,ore:5000,crystal:500}}},{id:1,teamId:1,factionId:'fairies',controller:'external',handicap:{startingResources:{wood:5000,ore:5000,crystal:500}}}],rules:{startingAge:3}});s.terrain.fill('grass');s.resources=[];refreshVisibility(s);return s;}
const run=(s:GameState,seconds:number)=>{for(let i=0;i<Math.round(seconds*20);i++)stepGame(s,.05);};
const workers=(s:GameState,side:Side=0)=>s.entities.filter(e=>e.side===side&&e.kind==='unit'&&e.role==='worker'&&!economicState(s)!.caravans.includes(e.id));
const hq=(s:GameState,side:Side=0)=>s.entities.find(e=>e.side===side&&e.role==='hq')!;
function node(s:GameState,kind:ResourceNode['kind'],amount=500,x=hq(s).x+7,y=hq(s).y):ResourceNode {const n={id:s.nextId++,x,y,kind,amount,maxAmount:amount};s.resources.push(n);workers(s)[0].x=x-1;workers(s)[0].y=y;refreshVisibility(s);return n;}
function build(s:GameState,kind:'warehouse'|'extractor'|'deep-mine',target?:number):Entity {const w=workers(s)[0];const c=kind==='warehouse'?{type:'buildEconomy' as const,ids:[w.id],kind,x:hq(s).x+6,y:hq(s).y+5}:{type:'buildEconomy' as const,ids:[w.id],kind,target:target!};expect(issueCommand(s,0,c)).toBe(true);const e=s.entities.at(-1)!;run(s,70);expect(e.progress).toBe(1);return e;}
function caravan(s:GameState):Entity {expect(issueCommand(s,0,{type:'trainCaravan',id:hq(s).id})).toBe(true);run(s,20);const id=economicState(s)!.caravans.at(-1)!;expect(id).toBeTruthy();return s.entities.find(e=>e.id===id)!;}
function expansion(s:GameState,x:number,y:number):Entity {const w=workers(s)[0];w.x=x-2;w.y=y+3;refreshVisibility(s);expect(issueCommand(s,0,{type:'build',ids:[w.id],role:'hq',x,y})).toBe(true);const e=s.entities.at(-1)!;run(s,100);expect(e.progress).toBe(1);return e;}
describe('economy and settlements command paths',()=>{
 it('plants paid groves, saves growth, harvests wood and burns finite saplings',()=>{const s=fixture(),w=workers(s)[0],p={x:hq(s).x+5,y:hq(s).y+2};const balance=s.players[0].wood;expect(issueCommand(s,0,{type:'plantGrove',ids:[w.id],...p})).toBe(true);expect(s.players[0].wood).toBe(balance-ECONOMY_RULES.grove.cost.wood);run(s,15);const grove=economicState(s)!.groves[0];expect(grove.plantedAt).toBeGreaterThan(0);const restored=loadGame(saveGame(s));run(s,70);run(restored,70);expect(saveGame(restored)).toEqual(saveGame(s));expect(grove.resourceId).toBeTruthy();const tree=s.resources.find(r=>r.id===grove.resourceId)!;expect(issueCommand(s,0,{type:'gather',ids:[w.id],target:tree.id})).toBe(true);run(s,100);expect(economicState(s)!.ledgers[0].gathered.wood).toBeGreaterThan(0);expect(tree.amount).toBeLessThan(tree.maxAmount);const burned={x:hq(s).x+5,y:hq(s).y-2};expect(issueCommand(s,0,{type:'plantGrove',ids:[workers(s)[1].id],...burned})).toBe(true);run(s,20);burnEconomyAt(s,burned.x,burned.y,1);run(s,70);expect(economicState(s)!.groves[1].resourceId).toBeUndefined();});
 it('opens exactly one paid finite deep reserve at a depleted ore deposit',()=>{const s=fixture(),ore=node(s,'ore',2),w=workers(s)[0];expect(issueCommand(s,0,{type:'buildEconomy',ids:[w.id],kind:'deep-mine',target:ore.id})).toBe(false);expect(issueCommand(s,0,{type:'gather',ids:[w.id],target:ore.id})).toBe(true);run(s,20);expect(ore.amount).toBe(0);const before=s.players[0].ore,mine=build(s,'deep-mine',ore.id);expect(ore.amount).toBe(1);expect(mine.definitionId).toBe('economy:deep-mine');expect(issueCommand(s,0,{type:'gather',ids:[w.id],target:ore.id})).toBe(true);run(s,30);expect(economicState(s)!.ledgers[0].gathered.ore).toBeGreaterThan(2);expect(s.players[0].ore).toBeLessThan(before);expect(ore.amount).toBe(0);expect(issueCommand(s,0,{type:'buildEconomy',ids:[w.id],kind:'deep-mine',target:ore.id})).toBe(false);});
 it('overcharges physical crystal harvest, reproduces damage and permits worker repair',()=>{const s=fixture(),crystal=node(s,'crystal',1000),extractor=build(s,'extractor',crystal.id);const w=workers(s)[0];expect(economyGatherFactor(s,w,crystal)).toBe(1.15);const normal=loadGame(saveGame(s));expect(issueCommand(normal,0,{type:'gather',ids:[w.id],target:crystal.id})).toBe(true);expect(issueCommand(s,0,{type:'setOvercharge',id:extractor.id,enabled:true})).toBe(true);expect(economyGatherFactor(s,w,crystal)).toBe(1.9);expect(issueCommand(s,0,{type:'gather',ids:[w.id],target:crystal.id})).toBe(true);const restored=loadGame(saveGame(s));run(s,90);run(restored,90);run(normal,90);expect(economicState(s)!.ledgers[0].gathered.crystal).toBeGreaterThan(economicState(normal)!.ledgers[0].gathered.crystal);expect(saveGame(restored)).toEqual(saveGame(s));expect(economicState(s)!.ledgers[0].gathered.crystal).toBeGreaterThan(0);expect(extractor.hp).toBeLessThan(extractor.maxHp);expect(issueCommand(s,0,{type:'setOvercharge',id:extractor.id,enabled:false})).toBe(true);const hurt=extractor.hp;expect(issueCommand(s,0,{type:'repair',ids:[workers(s)[1].id],target:extractor.id})).toBe(true);run(s,25);expect(extractor.hp).toBeGreaterThan(hurt);});
 it('gathers into local stock and physically delivers it before the wallet changes',()=>{const s=fixture(),warehouse=build(s,'warehouse'),wood=node(s,'wood',100,warehouse.x+4,warehouse.y),w=workers(s)[0];expect(issueCommand(s,0,{type:'setWarehouse',ids:[w.id],target:warehouse.id})).toBe(true);expect(issueCommand(s,0,{type:'gather',ids:[w.id],target:wood.id})).toBe(true);const before=s.players[0].wood;run(s,70);const local=economicState(s)!.structures.find(item=>item.entityId===warehouse.id)!;expect(local.stock.wood).toBeGreaterThan(0);expect(s.players[0].wood).toBe(before);expect(issueCommand(s,0,{type:'stop',ids:[w.id]})).toBe(true);const cart=caravan(s),amount=Math.min(30,local.stock.wood);expect(issueCommand(s,0,{type:'deliverStock',id:cart.id,source:warehouse.id,target:hq(s).id,stock:{wood:amount,ore:0,crystal:0}})).toBe(true);const paid=s.players[0].wood;run(s,60);expect(s.players[0].wood).toBeCloseTo(paid+amount,6);expect(economicState(s)!.ledgers[0].delivered.wood).toBeGreaterThanOrEqual(amount);});
 it('uses exclusive local expansion specializations for gathering, recruitment and research',()=>{const s=fixture(),start=hq(s),mine=expansion(s,start.x+15,start.y+3);expect(issueCommand(s,0,{type:'specializeSettlement',id:start.id,kind:'mining'})).toBe(false);expect(issueCommand(s,0,{type:'specializeSettlement',id:mine.id,kind:'mining'})).toBe(true);expect(issueCommand(s,0,{type:'specializeSettlement',id:mine.id,kind:'research'})).toBe(false);const ore=node(s,'ore',100,mine.x+3,mine.y);expect(economyGatherFactor(s,workers(s)[0],ore)).toBe(1.3);const research=expansion(s,start.x+3,start.y+18);expect(issueCommand(s,0,{type:'specializeSettlement',id:research.id,kind:'research'})).toBe(true);expect(economyResearchFactor(s,research)).toBe(1.35);expect(economyResearchFactor(s,start)).toBe(1);expect(economyProductionFactor(s,research)).toBe(1);const military=expansion(s,start.x+12,start.y+18);expect(issueCommand(s,0,{type:'specializeSettlement',id:military.id,kind:'military'})).toBe(true);expect(economyProductionFactor(s,military)).toBe(1.3);expect(economyProductionFactor(s,start)).toBe(1);
 expect(issueCommand(s,0,{type:'train',id:military.id,role:'worker'})).toBe(true);expect(issueCommand(s,0,{type:'train',id:start.id,role:'worker'})).toBe(true);run(s,5);expect(military.trainProgress).toBeGreaterThan(start.trainProgress);
 expect(issueCommand(s,0,{type:'research',id:research.id,upgrade:'worker-speed'})).toBe(true);expect(issueCommand(s,1,{type:'research',id:hq(s,1).id,upgrade:'worker-speed'})).toBe(true);run(s,5);expect(research.researchProgress).toBeGreaterThan(hq(s,1).researchProgress);
 expect(loadGame(saveGame(s)).economy).toEqual(s.economy);});
 it('reserves caravan recruits against ordinary queues and keeps caravans out of combat',()=>{const s=fixture(),base=hq(s);s.populationLimits[0]=9;run(s,.05);expect(issueCommand(s,0,{type:'trainCaravan',id:base.id})).toBe(true);expect(issueCommand(s,0,{type:'trainCaravan',id:base.id})).toBe(true);expect(issueCommand(s,0,{type:'train',id:base.id,role:'worker'})).toBe(true);expect(issueCommand(s,0,{type:'train',id:base.id,role:'worker'})).toBe(false);run(s,40);const cart=s.entities.find(e=>economicState(s)!.caravans.includes(e.id))!,enemy=s.entities.find(e=>e.side===1&&e.role==='melee')!;expect(s.players[0].population).toBeLessThanOrEqual(9);expect(issueCommand(s,0,{type:'attack',ids:[cart.id],target:enemy.id})).toBe(false);expect(issueCommand(s,0,{type:'attackMove',ids:[cart.id],x:10,y:10})).toBe(false);});
 it('rejects commands and interactions across map levels',()=>{const s=fixture(),w=workers(s)[0],market=economicState(s)!.markets[0];expect(issueCommand(s,0,{type:'plantGrove',ids:[w.id],x:w.x+2,y:w.y,level:1})).toBe(false);expect(issueCommand(s,0,{type:'buildEconomy',ids:[w.id],kind:'warehouse',x:w.x+3,y:w.y,level:1})).toBe(false);const cart=caravan(s);cart.level=1;expect(issueCommand(s,0,{type:'deliverStock',id:cart.id,source:hq(s).id,target:hq(s,1).id,stock:{wood:1,ore:0,crystal:0}})).toBe(false);w.x=market.x;w.y=market.y;w.level=1;market.level=0;refreshVisibility(s);expect(issueCommand(s,0,{type:'marketTrade',market:market.id,kind:'ore',amount:1,direction:'buy'})).toBe(false);expect(validateCommand({type:'plantGrove',ids:[w.id],x:5,y:5,level:3})).toBe(false);});
 it('enforces command shapes and hides foreign cargo, warehouse stock and contracts',()=>{const s=fixture(),warehouse=build(s,'warehouse');economicState(s)!.structures[0].stock.wood=80;const cart=caravan(s);economicState(s)!.cargo[0].stock.wood=30;workers(s,1)[0].x=warehouse.x;workers(s,1)[0].y=warehouse.y+2;cart.x=warehouse.x;cart.y=warehouse.y+3;refreshVisibility(s);const view=new PlayerView(1).observe(s).economy;expect(view.structures[0].stock.wood).toBe(0);expect(view.caravans[0].stock.wood).toBe(0);expect(issueCommand(s,1,{type:'setOvercharge',id:warehouse.id,enabled:true})).toBe(false);expect(validateCommand({type:'plantGrove',ids:[workers(s)[0].id],x:5,y:5,queued:true})).toBe(false);expect(validateCommand({type:'marketTrade',market:1,kind:'ore',amount:Infinity,direction:'buy'})).toBe(false);const broken=structuredClone(s.economy)!;broken.cargo[0].stock.wood=10000;expect(()=>validateEconomyState(broken,{width:s.width,height:s.height,time:s.time,nextId:s.nextId,playerCount:s.players.length,entities:s.entities,resources:s.resources})).toThrow('cargo');});
});
