import { describe, expect, it } from 'vitest';
import { validateCommand } from '../src/core/commands';
import { FACTIONS } from '../src/core/content';
import { factionCommandReason, factionConcealment, factionDamageFactor, refreshPowerNetworks } from '../src/core/faction-systems';
import { CORPSE_WAGON, FACTION_STRUCTURE_INFO, TROPHY_STANDARD } from '../src/core/faction-systems-content';
import { PlayerView } from '../src/core/observation';
import { MatchRecorder, ReplayPlayer, replayChecksum } from '../src/core/replays';
import { loadGame, saveGame } from '../src/core/saves';
import { createGame, issueCommand, refreshVisibility, spawnFactionDefinition, stepGame } from '../src/core/simulation';
import { canObserveTacticalEntity, initializeTactics } from '../src/core/tactics';
import type { BuildingRole, Entity, FactionId, GameState, Side, UnitRole } from '../src/core/types';

function fixture(faction:FactionId,opponent:FactionId='orcs') {const s=createGame(faction,4127,opponent,{controllers:['external','external']});s.terrain.fill('grass');s.resources=[];s.entities=s.entities.filter(e=>e.kind==='building');for(const p of s.players){p.wood=2000;p.ore=2000;p.crystal=1000;p.upgrades=['town-age','citadel-age'];p.cap=100;}return s;}
function unit(s:GameState,side:Side,role:UnitRole,x=20.5,y=20.5):Entity {const d=FACTIONS[s.players[side].faction].units[role],e:Entity={id:s.nextId++,side,kind:'unit',role,x,y,hp:d.hp,maxHp:d.hp,order:{type:'hold'},cooldown:100,progress:1,queue:[],trainProgress:0,researchProgress:0,facing:4,animation:'idle',animTime:0,momentum:0,illusion:false,expires:0,carried:0,carriedKind:'wood',path:[]};if(d.shield){e.shield=d.shield;e.maxShield=d.shield;}initializeTactics(s,e);s.entities.push(e);if(d.ability==='ammunition-cannon')expect(issueCommand(s,side,{type:'ability',ids:[e.id]})).toBe(true);return e;}
function building(s:GameState,side:Side,role:BuildingRole,x:number,y:number):Entity {const d=FACTIONS[s.players[side].faction].buildings[role],e={...structuredClone(s.entities[0]),id:s.nextId++,side,role,x,y,hp:d.hp,maxHp:d.hp};delete e.definitionId;s.entities.push(e);return e;}
function advance(s:GameState,seconds:number) {for(let i=0;i<Math.round(seconds/.05);i++)stepGame(s,.05);}
function fire(s:GameState,a:Entity,b:Entity,seconds=.05) {refreshVisibility(s);a.cooldown=0;expect(issueCommand(s,a.side,{type:'attack',ids:[a.id],target:b.id})).toBe(true);advance(s,seconds);return b;}
function reveal(s:GameState) {refreshVisibility(s);for(const set of [...s.visible,...s.explored])for(let i=0;i<s.width*s.height;i++)set.add(i);}
function wagon(s:GameState,x=20.5,y=20.5) {const e=spawnFactionDefinition(s,0,CORPSE_WAGON.id,{x,y});e.order={type:'hold'};return e;}

describe('faction mechanics through authoritative encounters',()=>{
 it('hostile damage earns bounded Fury, selected assault raises real damage, and the chant expires',()=>{
  const s=fixture('orcs'),a=unit(s,0,'ranged'),b=unit(s,1,'melee',24.5,20.5);const hp=b.hp;fire(s,a,b);const baseline=hp-b.hp;expect(s.factionSystems!.fury[0]).toBeCloseTo(baseline*.12);expect(issueCommand(s,0,{type:'warChant',ids:[a.id],chant:'assault'})).toBe(false);
  s.factionSystems!.fury[0]=40;expect(issueCommand(s,0,{type:'warChant',ids:[a.id],chant:'assault'})).toBe(true);expect(s.factionSystems!.fury[0]).toBe(15);const next=b.hp;a.momentum=0;fire(s,a,b);expect(next-b.hp).toBeGreaterThan(baseline);a.cooldown=100;advance(s,12.1);expect(a.factionState!.chant).toBeUndefined();
 });
 it('a dying Orc earns Fury for its completed simultaneous attack regardless of target group order',()=>{
  for(const orcFirst of [true,false]){const s=fixture('orcs','fairies');let a:Entity,b:Entity;if(orcFirst){a=unit(s,0,'melee',20.5,20.5);b=unit(s,1,'melee',21.5,20.5);}else{b=unit(s,1,'melee',21.5,20.5);a=unit(s,0,'melee',20.5,20.5);}a.hp=b.hp=1;reveal(s);a.cooldown=b.cooldown=0;issueCommand(s,0,{type:'attack',ids:[a.id],target:b.id});issueCommand(s,1,{type:'attack',ids:[b.id],target:a.id});advance(s,.05);expect(a.hp).toBe(0);expect(b.hp).toBe(0);expect(s.factionSystems!.fury[0]).toBeCloseTo(.12);}
 });
 it('bulwark reduces damage on selected troops and another faction cannot spend Fury',()=>{
  const s=fixture('orcs','fairies'),a=unit(s,0,'melee',24.5,20.5),b=unit(s,1,'ranged');s.factionSystems!.fury=[50,50];reveal(s);const hp=a.hp;fire(s,b,a);const baseline=hp-a.hp;expect(issueCommand(s,0,{type:'warChant',ids:[a.id],chant:'bulwark'})).toBe(true);const next=a.hp;fire(s,b,a);expect(next-a.hp).toBeCloseTo(baseline-3);expect(issueCommand(s,1,{type:'warChant',ids:[b.id],chant:'bulwark'})).toBe(false);
 });
 it('two hostile mortal kills earn a destructible trophy standard without supply or drop-off',()=>{
  const s=fixture('orcs'),a=unit(s,0,'ranged');for(let i=0;i<2;i++){const b=unit(s,1,'melee',24.5,20.5+i*.8);b.hp=1;fire(s,a,b);}expect(a.factionState!.trophyKills).toBe(2);a.cooldown=100;reveal(s);const cap=s.players[0].cap;expect(issueCommand(s,0,{type:'trophyStandard',ids:[a.id]})).toBe(true);const banner=s.entities.find(e=>e.definitionId===TROPHY_STANDARD.id)!;expect(banner.hp).toBe(160);expect(a.factionState!.trophyKills).toBe(0);advance(s,.05);expect(s.players[0].cap).toBe(cap);a.tactics!.morale=50;advance(s,1);expect(a.tactics!.morale).toBeGreaterThan(53);
  const b=unit(s,1,'siege',banner.x-5,banner.y);banner.hp=1;fire(s,b,banner,1);expect(banner.hp).toBe(0);
 });
 it('expired standards stop their aura before entity cleanup',()=>{const s=fixture('orcs'),a=unit(s,0,'ranged'),banner=spawnFactionDefinition(s,0,TROPHY_STANDARD.id,{x:22.5,y:20.5});banner.expires=1;expect(factionDamageFactor(s,a)).toBe(1.1);s.time=1;expect(factionDamageFactor(s,a)).toBe(1);});
 it('illusion swapping exchanges positions and clears orders for a paid cooldown, rejecting foreign doubles',()=>{
  const s=fixture('fairies'),a=unit(s,0,'melee'),illusion=unit(s,0,'melee',26.5,20.5);illusion.illusion=true;illusion.expires=100;const crystal=s.players[0].crystal;reveal(s);expect(issueCommand(s,0,{type:'illusionSwap',ids:[a.id],target:illusion.id})).toBe(true);expect([a.x,illusion.x]).toEqual([26.5,20.5]);expect(s.players[0].crystal).toBe(crystal-15);expect(a.order.type).toBe('hold');expect(issueCommand(s,0,{type:'illusionSwap',ids:[a.id],target:illusion.id})).toBe(false);advance(s,10);expect(issueCommand(s,0,{type:'illusionSwap',ids:[a.id],target:illusion.id})).toBe(true);illusion.side=1;expect(factionCommandReason(s,0,{type:'illusionSwap',ids:[a.id],target:illusion.id})).toMatch(/owned/);
 });
 it('a blocked swap is atomic and neither spends crystal nor moves actors',()=>{
  const s=fixture('fairies'),a=unit(s,0,'melee'),illusion=unit(s,0,'melee',26.5,20.5);illusion.illusion=true;illusion.expires=100;reveal(s);s.terrain[20*s.width+26]='rock';const crystal=s.players[0].crystal;expect(issueCommand(s,0,{type:'illusionSwap',ids:[a.id],target:illusion.id})).toBe(false);expect([a.x,illusion.x,s.players[0].crystal]).toEqual([20.5,26.5,crystal]);
 });
 it('groves conceal nearby allies until attacking, contact or scouts reveal them',()=>{
  const s=fixture('fairies'),ally=unit(s,0,'ranged',24.5,20.5),foe=unit(s,1,'ranged',28.5,20.5);spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO['enchanted-grove'].definition.id,{x:22.5,y:20.5});reveal(s);expect(factionConcealment(s,ally)).toBe(true);expect(canObserveTacticalEntity(s,1,ally)).toBe(false);expect(new PlayerView(1).observe(s).entities.some(e=>e.id===ally.id)).toBe(false);expect(issueCommand(s,1,{type:'attack',ids:[foe.id],target:ally.id})).toBe(false);const scout=unit(s,1,'cavalry',26.5,20.5);refreshVisibility(s);expect(canObserveTacticalEntity(s,1,ally)).toBe(true);scout.x=35;ally.animation='attack';expect(factionConcealment(s,ally)).toBe(false);ally.animation='idle';ally.lastDamagedAt=s.time;expect(factionConcealment(s,ally)).toBe(false);
 });
 it('a grove sends a harmless moving decoy only toward an observed hostile scout',()=>{
  const s=fixture('fairies'),ally=unit(s,0,'melee',23.5,22.5),scout=unit(s,1,'cavalry',38.5,20.5),grove=spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO['enchanted-grove'].definition.id,{x:22.5,y:20.5});advance(s,.05);scout.x=28.5;s.visible[0].clear();advance(s,.05);expect(s.entities.filter(e=>e.illusion)).toHaveLength(0);refreshVisibility(s);advance(s,.25);const decoy=s.entities.find(e=>e.illusion)!;expect(decoy).toBeDefined();expect(decoy.order.type).toBe('move');expect(decoy.cooldown).toBeGreaterThan(90);expect(grove.factionState!.nextDecoyAt).toBeGreaterThan(s.time);const hp=scout.hp;advance(s,2);expect(scout.hp).toBe(hp);expect(decoy.x).toBeGreaterThan(ally.x);
 });
 it.each(['stone','grapeshot','reinforced'] as const)('%s modifications pay per artillery unit and affect real shots or movement',modification=>{
  const s=fixture('dwarves'),a=unit(s,0,'siege',18.5,20.5),c=unit(s,0,'special',18.5,24.5),b=modification==='stone'?building(s,1,'depot',25.5,20.5):unit(s,1,'melee',25.5,20.5);const wood=s.players[0].wood,ore=s.players[0].ore;reveal(s);expect(issueCommand(s,0,{type:'modifyArtillery',ids:[a.id,c.id],modification})).toBe(true);expect(s.players[0].wood).toBe(wood-50);expect(s.players[0].ore).toBe(ore-40);expect(a.factionState!.artillery).toBe(modification);expect(c.factionState!.artillery).toBe(modification);
  if(modification==='reinforced'){expect(issueCommand(s,0,{type:'move',ids:[a.id],x:23.5,y:20.5})).toBe(true);advance(s,.5);const moved=a.x-18.5;const plain=fixture('dwarves'),normal=unit(plain,0,'siege',18.5,20.5);reveal(plain);issueCommand(plain,0,{type:'move',ids:[normal.id],x:23.5,y:20.5});advance(plain,.5);expect(moved).toBeLessThan(normal.x-18.5);}
  else {const hp=b.hp;fire(s,a,b,.05);expect((s.projectiles?.[0]??s.specialists?.shots?.[0])!.modification).toBe(modification);expect(modification==='grapeshot'?Math.max(s.specialists?.shots?.[0]?.payload.radius??s.projectiles?.[0]?.radius??0,2.5):s.specialists?.shots?.[0]?.payload.radius??s.projectiles?.[0]?.radius).toBe(modification==='grapeshot'?2.5:0);advance(s,1);expect(b.hp).toBeLessThan(hp);}
 });
 it('stone and grapeshot scale damage for each impact victim instead of the primary target',()=>{
  const trial=(modification:'stone'|'grapeshot'|undefined,kind:'unit'|'building')=>{const s=fixture('dwarves'),a=unit(s,0,'siege',18.5,20.5),b=kind==='building'?building(s,1,'depot',25.5,20.5):unit(s,1,'melee',25.5,20.5);if(modification)a.factionState={artillery:modification};const hp=b.hp;fire(s,a,b,.05);s.entities=s.entities.filter(e=>e!==a);advance(s,1);return hp-b.hp;};
  expect(trial('stone','building')+3).toBeCloseTo((trial(undefined,'building')+3)*1.25);expect(trial('stone','unit')).toBeCloseTo(trial(undefined,'unit'));expect(trial('grapeshot','unit')+3).toBeCloseTo((trial(undefined,'unit')+3)*1.5);expect(trial('grapeshot','building')).toBeCloseTo(trial(undefined,'building'));
 });
 it('incendiary engines and fitted cannons pay ammunition at launch and retain payload after source removal',()=>{
  for(const role of ['siege','special'] as const){const s=fixture('dwarves'),a=unit(s,0,role,18.5,20.5),b=unit(s,1,'melee',24.5,20.5);reveal(s);expect(issueCommand(s,0,{type:'modifyArtillery',ids:[a.id],modification:'incendiary'})).toBe(true);const wood=s.players[0].wood,ore=s.players[0].ore;fire(s,a,b);expect(s.players[0].wood).toBe(wood-15);expect(s.players[0].ore).toBe(ore-5);expect((s.projectiles?.[0]??s.specialists?.shots?.[0])!.modification).toBe('incendiary');const hp=b.hp;s.entities=s.entities.filter(e=>e!==a);const resumed=loadGame(saveGame(s));advance(s,1);advance(resumed,1);expect(b.hp).toBeLessThan(hp);expect(replayChecksum(resumed)).toBe(replayChecksum(s));}
 });
 it('incendiary fittings with no ammunition do not create a projectile or spend partial funds',()=>{
  const s=fixture('dwarves'),a=unit(s,0,'siege',18.5,20.5),b=unit(s,1,'melee',24.5,20.5);a.factionState={artillery:'incendiary'};s.players[0].wood=14;const hp=b.hp;fire(s,a,b);expect(s.projectiles).toHaveLength(0);expect(s.players[0].wood).toBe(14);expect(b.hp).toBe(hp);
 });
 it('crew damage earns Fury only for HP lost even when simultaneous attackers overkill the crew',()=>{
  const s=fixture('orcs'),a=unit(s,0,'melee',23.5,20.5),b=unit(s,0,'melee',24.5,21.5),engine=unit(s,1,'siege',24.5,20.5);engine.tactics!.siegeCrew!.hp=1;reveal(s);a.cooldown=0;b.cooldown=0;issueCommand(s,0,{type:'attack',ids:[a.id,b.id],target:engine.id});advance(s,.05);expect(s.factionSystems!.fury[0]).toBeCloseTo(.12);expect(s.events.filter(e=>e.type==='attack'&&e.target===engine.id).reduce((n,e)=>n+(e.amount??0),0)).toBeCloseTo(1);
 });
 it('faction foundations move their friendly builders out of the construction footprint',()=>{
  const s=fixture('undead'),worker=unit(s,0,'worker',24.5,20.5);reveal(s);expect(issueCommand(s,0,{type:'buildFactionStructure',ids:[worker.id],structure:'necropolis',x:24.5,y:20.5})).toBe(true);expect(Math.hypot(worker.x-24.5,worker.y-20.5)).toBeGreaterThan(1.5);advance(s,29);expect(s.entities.find(e=>e.definitionId===FACTION_STRUCTURE_INFO.necropolis.definition.id)!.progress).toBe(1);
 });
 it('workers pay for special structures and complete their definition-specific construction',()=>{
  const s=fixture('undead'),worker=unit(s,0,'worker',20.5,20.5);reveal(s);const wood=s.players[0].wood;expect(issueCommand(s,0,{type:'buildFactionStructure',ids:[worker.id],structure:'necropolis',x:24.5,y:20.5})).toBe(true);const b=s.entities.find(e=>e.definitionId===FACTION_STRUCTURE_INFO.necropolis.definition.id)!;expect(b.maxHp).toBe(550);expect(b.progress).toBe(0);expect(s.players[0].wood).toBe(wood-120);advance(s,31);expect(b.progress).toBe(1);expect(b.hp).toBe(550);
 });
 it('tunnel travel channels, preserves a mid-channel save, and arrives at a walkable exit',()=>{
  const s=fixture('dwarves'),a=unit(s,0,'melee',22.5,20.5),origin=spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO.tunnel.definition.id,{x:20.5,y:20.5}),target=spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO.tunnel.definition.id,{x:40.5,y:20.5});reveal(s);expect(issueCommand(s,0,{type:'tunnelTravel',ids:[a.id],target:target.id})).toBe(true);advance(s,1.5);expect(a.factionState!.tunnel!.progress).toBeCloseTo(.5);const resumed=loadGame(saveGame(s));advance(s,1.6);advance(resumed,1.6);expect(a.x).toBeGreaterThan(41.5);expect(a.factionState!.tunnel).toBeUndefined();expect(replayChecksum(resumed)).toBe(replayChecksum(s));expect(origin.hp).toBe(origin.maxHp);
 });
 it('damage or a new ordinary order cancels tunnel travel and foreign exits are rejected',()=>{
  const s=fixture('dwarves'),a=unit(s,0,'melee',22.5,20.5);spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO.tunnel.definition.id,{x:20.5,y:20.5});const target=spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO.tunnel.definition.id,{x:40.5,y:20.5});reveal(s);issueCommand(s,0,{type:'tunnelTravel',ids:[a.id],target:target.id});advance(s,1);a.lastDamagedAt=s.time;advance(s,.05);expect(a.factionState!.tunnel).toBeUndefined();advance(s,.3);reveal(s);issueCommand(s,0,{type:'tunnelTravel',ids:[a.id],target:target.id});issueCommand(s,0,{type:'move',ids:[a.id],x:25.5,y:20.5});expect(a.factionState!.tunnel).toBeUndefined();target.side=1;expect(issueCommand(s,0,{type:'tunnelTravel',ids:[a.id],target:target.id})).toBe(false);
 });
 it('corpse wagons recruit through the normal queue with correct cost, stats, cancellation and save',()=>{
  const s=fixture('undead'),b=building(s,0,'barracks',20.5,20.5),wood=s.players[0].wood;reveal(s);expect(issueCommand(s,0,{type:'train',id:b.id,role:'special',definitionId:CORPSE_WAGON.id})).toBe(true);expect(s.players[0].wood).toBe(wood-100);expect(b.queue).toEqual(['special']);expect(b.queueDefinitionIds).toEqual([CORPSE_WAGON.id]);const resumed=loadGame(saveGame(s));advance(s,25);advance(resumed,25);const recruited=s.entities.find(e=>e.definitionId===CORPSE_WAGON.id)!;expect(recruited.maxHp).toBe(160);expect(recruited.role).toBe('special');expect(replayChecksum(resumed)).toBe(replayChecksum(s));expect(issueCommand(s,0,{type:'train',id:b.id,role:'special',definitionId:CORPSE_WAGON.id})).toBe(true);expect(issueCommand(s,0,{type:'cancelTrain',id:b.id,index:0})).toBe(true);expect(s.players[0].wood).toBe(wood-100);expect(b.queueDefinitionIds).toEqual([]);
 });
 it('two wagons cannot claim one corpse; delivery feeds raising once while expiry remains unchanged',()=>{
  const s=fixture('undead'),a=wagon(s),b=wagon(s,20.5,21.5);const body={id:s.nextId++,x:20.5,y:20.7,expires:45};s.corpses.push(body);reveal(s);expect(issueCommand(s,0,{type:'collectCorpses',ids:[a.id,b.id],target:body.id})).toBe(true);advance(s,1.2);expect(s.corpses).toHaveLength(0);expect([a,b].reduce((n,e)=>n+(e.factionState?.corpseCargo?.length??0),0)).toBe(1);expect(a.factionState!.corpseCargo![0].expires).toBe(45);const caster=unit(s,0,'special',23.5,20.5);expect(issueCommand(s,0,{type:'deliverCorpses',ids:[a.id],target:caster.id})).toBe(true);const resumed=loadGame(saveGame(s));advance(s,3);advance(resumed,3);expect(s.entities.filter(e=>e.raised)).toHaveLength(1);expect(a.factionState!.corpseCargo).toHaveLength(0);expect(caster.factionState!.deliveredCorpses).toHaveLength(0);expect(replayChecksum(resumed)).toBe(replayChecksum(s));advance(s,23);expect(s.entities.filter(e=>e.raised)).toHaveLength(1);
 });
 it('wagon cargo decays on its original clock and surviving cargo drops when the wagon dies',()=>{
  const s=fixture('undead'),a=wagon(s);const expired={id:s.nextId++,x:a.x,y:a.y,expires:.5},fresh={id:s.nextId++,x:a.x,y:a.y,expires:45};a.factionState={corpseCargo:[expired,fresh]};advance(s,1);expect(a.factionState.corpseCargo).toEqual([fresh]);const enemy=unit(s,1,'ranged',24.5,20.5);a.hp=1;fire(s,enemy,a);expect(a.hp).toBe(0);expect(s.corpses.some(b=>b.id===fresh.id&&b.expires===45)).toBe(true);
 });
 it('necropolis sustains and heals raised allies until they leave its territory',()=>{
  const s=fixture('undead'),a=unit(s,0,'melee',23.5,20.5);a.raised=true;a.expires=3;a.hp=30;spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO.necropolis.definition.id,{x:20.5,y:20.5});advance(s,4);expect(a.hp).toBeCloseTo(38);expect(a.expires-s.time).toBeCloseTo(3);a.x=35.5;advance(s,3.1);expect(a.hp).toBe(0);
 });
 it('water shaping costs crystal, changes legal terrain, survives saves and restores it after twenty seconds',()=>{
  const s=fixture('tideborn'),caster=unit(s,0,'special',20.5,20.5);reveal(s);s.terrain[20*s.width+24]='rock';const crystal=s.players[0].crystal;expect(issueCommand(s,0,{type:'shapeWater',ids:[caster.id],x:24.5,y:21.5,terrain:'mud'})).toBe(true);expect(s.players[0].crystal).toBe(crystal-25);expect(s.terrain[21*s.width+24]).toBe('mud');expect(s.terrain[20*s.width+24]).toBe('rock');const resumed=loadGame(saveGame(s));advance(s,20.1);advance(resumed,20.1);expect(s.terrain[21*s.width+24]).toBe('grass');expect(s.factionSystems!.terrainEffects).toHaveLength(0);expect(replayChecksum(resumed)).toBe(replayChecksum(s));
 });
 it('overlapping water effects restore underlying ground once and protected terrain is not overwritten',()=>{
  const s=fixture('tideborn'),a=unit(s,0,'special',20.5,20.5),b=unit(s,0,'special',21.5,21.5);reveal(s);issueCommand(s,0,{type:'shapeWater',ids:[a.id],x:24.5,y:21.5,terrain:'mud'});advance(s,5);reveal(s);expect(issueCommand(s,0,{type:'shapeWater',ids:[b.id],x:24.5,y:21.5,terrain:'shallows'})).toBe(true);advance(s,15.1);expect(s.terrain[21*s.width+24]).toBe('shallows');advance(s,5);expect(s.terrain[21*s.width+24]).toBe('grass');
  reveal(s);s.terrain[21*s.width+24]='rock';issueCommand(s,0,{type:'shapeWater',ids:[a.id],x:24.5,y:21.5,terrain:'mud'});expect(s.terrain[21*s.width+24]).toBe('rock');
 });
 it('a powered tower fires and shares real shield damage; a broken relay disconnects it',()=>{
  const s=fixture('automata');const hq=s.entities.find(e=>e.side===0)!;hq.x=10.5;hq.y=20.5;const relay=spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO['power-relay'].definition.id,{x:18.5,y:20.5}),tower=building(s,0,'tower',26.5,20.5),enemy=unit(s,1,'ranged',31.5,20.5);refreshPowerNetworks(s,0);expect(tower.factionState!.power).toEqual({connected:true,root:hq.id});const hp=enemy.hp;advance(s,.05);expect(enemy.hp).toBeLessThan(hp);enemy.cooldown=0;const towerHp=tower.hp;fire(s,enemy,tower);expect(tower.hp).toBe(towerHp);expect(tower.shield).toBeLessThan(80);tower.shield=0;enemy.cooldown=0;const reserve=relay.shield!;fire(s,enemy,tower);expect(relay.shield).toBeLessThan(reserve);relay.hp=0;advance(s,.05);expect(tower.factionState!.power!.connected).toBe(false);tower.cooldown=0;const after=enemy.hp;advance(s,.2);expect(enemy.hp).toBe(after);
 });
 it('power networks with separate headquarters cannot borrow an unrelated component shield',()=>{
  const s=fixture('automata'),hq=s.entities.find(e=>e.side===0)!;hq.x=10.5;hq.y=10.5;const hq2=building(s,0,'hq',40.5,30.5),tower=building(s,0,'tower',45.5,30.5);refreshPowerNetworks(s,0);expect(tower.factionState!.power!.root).toBe(hq2.id);expect(hq.factionState!.power!.root).toBe(hq.id);
 });
 it('connected headquarters form one shield component after a relay joins them',()=>{
  const s=fixture('automata'),hq=s.entities.find(e=>e.side===0)!;hq.x=10.5;hq.y=20.5;const hq2=building(s,0,'hq',26.5,20.5);refreshPowerNetworks(s,0);expect(hq2.factionState!.power!.root).toBe(hq2.id);spawnFactionDefinition(s,0,FACTION_STRUCTURE_INFO['power-relay'].definition.id,{x:18.5,y:20.5});refreshPowerNetworks(s,0);expect(hq2.factionState!.power!.root).toBe(hq.id);
 });
 it('observation hides opponents Fury, body manifests and private cooldowns while exposing visible fittings',()=>{
  const s=fixture('undead'),a=wagon(s,20.5,20.5);unit(s,1,'ranged',24.5,20.5);a.factionState={corpseCargo:[{id:s.nextId++,x:a.x,y:a.y,expires:45}],swapReadyAt:10,artillery:'reinforced'};s.factionSystems!.fury=[25,3];reveal(s);const enemy=new PlayerView(1).observe(s),own=new PlayerView(0).observe(s),seen=enemy.entities.find(e=>e.id===a.id)!;expect(enemy.factionSystems).toEqual({fury:3});expect(seen.factionState).not.toHaveProperty('corpseCargo');expect(seen.factionState).not.toHaveProperty('swapReadyAt');expect(seen.factionState!.artillery).toBe('reinforced');expect(own.entities.find(e=>e.id===a.id)!.factionState).toHaveProperty('corpseCargo',a.factionState.corpseCargo);
 });
 it('faction commands and persistent effects replay through the same command boundary',()=>{
  const s=fixture('tideborn'),caster=unit(s,0,'special');reveal(s);const recorder=new MatchRecorder(s);expect(issueCommand(s,0,{type:'shapeWater',ids:[caster.id],x:24.5,y:21.5,terrain:'mud'})).toBe(true);advance(s,2);const player=new ReplayPlayer(recorder.export());player.seek(s.tick);expect(replayChecksum(player.state)).toBe(replayChecksum(s));recorder.dispose();player.dispose();
 });
 it('strict commands and save loading reject bad modes, queue mismatch and duplicated bodies',()=>{
  expect(validateCommand({type:'warChant',ids:[1],chant:'infinite'})).toBe(false);expect(validateCommand({type:'shapeWater',ids:[1],x:2,y:2,terrain:'rock'})).toBe(false);expect(validateCommand({type:'buildFactionStructure',ids:[1],structure:'tunnel',x:2,y:2,level:-1})).toBe(false);const s=fixture('undead'),a=wagon(s);a.factionState={corpseCargo:[{id:s.nextId++,x:a.x,y:a.y,expires:45}]};let saved=saveGame(s);saved.state.corpses=[...a.factionState.corpseCargo!];expect(()=>loadGame(saved)).toThrow(/more than one/);saved=saveGame(s);saved.state.entities.find(e=>e.id===a.id)!.factionState!.corpseOrder={type:'collect',target:1,progress:2};expect(()=>loadGame(saved)).toThrow(/between 0 and 1/);
 });
});
