import { distance, levelOf, sameLevel } from '../core/economy-common';
import { factionFor, unitFor } from '../core/content-registry';
import { marketCurrency, marketQuote } from '../core/economy-cargo';
import { ECONOMY_BUILDINGS, ECONOMY_CARAVAN, ECONOMY_RULES } from '../core/economy-definitions';
import type { EconomyCommand, EconomyView, SettlementSpecialization } from '../core/economy-types';
import type { Cost, Entity, GameState, ResourceKind, ResourceNode, Side } from '../core/types';
import './economy-tools.css';

type MaybePromise<T> = T | Promise<T>;
export interface EconomyToolsStatus { side?:Side; readOnly?:boolean; blocked?:boolean }
export interface EconomyToolsCallbacks {
  getGame:()=>GameState|null;
  getView:()=>EconomyView|null;
  /** Use PlayerView memory or the authoritative client view, never the live hidden resource list. */
  knownResources:()=>readonly (ResourceNode & {visible?:boolean;lastSeen?:number})[];
  selectedIds:()=>number[];
  submit:(command:EconomyCommand)=>MaybePromise<boolean>;
  onModal:(open:boolean)=>void;
}
const kinds:ResourceKind[]=['wood','ore','crystal'];
const title=(value:string)=>value.charAt(0).toUpperCase()+value.slice(1);
const amount=(value:number)=>Number.isFinite(value)?String(Math.round(value*10)/10):'?';
const stock=(value:Cost)=>kinds.map(kind=>`${amount(value[kind])} ${kind}`).join(', ');
const el=<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string,className?:string):HTMLElementTagNameMap[K]=>{const result=document.createElement(tag);if(text!==undefined)result.textContent=text;if(className)result.className=className;return result;};
const button=(text:string,action:()=>void)=>{const result=el('button',text);result.type='button';result.addEventListener('click',action);return result;};
const field=(label:string,input:HTMLElement)=>{const result=el('label',label,'economy-field');result.append(input);return result;};
const select=(label:string)=>{const result=el('select');result.setAttribute('aria-label',label);return result;};
const number=(label:string,value:string,min='0',step='1')=>{const result=el('input');result.type='number';result.value=value;result.min=min;result.step=step;result.setAttribute('aria-label',label);return result;};
interface Choice { id:number|string;label:string;disabled?:boolean }
function choices(input:HTMLSelectElement,items:Choice[],empty:string){
  const key=JSON.stringify(items);if(input.dataset.choices===key)return;const value=input.value;input.dataset.choices=key;input.replaceChildren();
  for(const item of items){const option=el('option',item.label);option.value=String(item.id);option.disabled=!!item.disabled;input.append(option);}
  if(!items.length){const option=el('option',empty);option.value='';option.disabled=true;input.append(option);}
  if(items.some(item=>String(item.id)===value&&!item.disabled))input.value=value;else input.value=String(items.find(item=>!item.disabled)?.id??'');
}
function numericId(input:HTMLSelectElement,label:string):number {const value=Number(input.value);if(!input.value||!Number.isSafeInteger(value)||value<=0||!Array.from(input.options).some(option=>option.value===input.value&&!option.disabled))throw new Error(`Choose ${label}.`);return value;}
function whole(input:HTMLInputElement,label:string,max=10000):number {const value=Number(input.value);if(!input.value.trim()||!Number.isSafeInteger(value)||value<1||value>max)throw new Error(`${label} must be a whole number from 1 to ${max}.`);return value;}
function errorText(error:unknown):string{return error instanceof Error?error.message:'The economy command could not be applied.';}

/** All spending and orders go through the host's recorded command path. */
export function mountEconomyTools(root:HTMLElement,callbacks:EconomyToolsCallbacks){
  let status:EconomyToolsStatus={},game:GameState|null=null,view:EconomyView|null=null,opened=false,disposed=false,pending:{generation:number}|null=null,previousFocus:HTMLElement|null=null;
  let oldGame:GameState|null=null,oldSide:Side|undefined,contextGeneration=0,activePage='resources';
  const selected=new Set<number>(),actions:{control:HTMLButtonElement;reason:()=>string}[]=[],editable:HTMLInputElement[]=[];
  const host=el('section',undefined,'economy-tools');host.setAttribute('aria-label','Economy and settlements');
  const toolbar=el('nav',undefined,'economy-toolbar');toolbar.setAttribute('aria-label','Economy and settlements');
  const launch=button('Economy and settlements',open);launch.dataset.economyLaunch='';toolbar.append(launch);
  const overlay=el('div',undefined,'economy-overlay');overlay.hidden=true;
  const dialog=el('section',undefined,'economy-dialog');dialog.setAttribute('role','dialog');dialog.setAttribute('aria-modal','true');dialog.setAttribute('aria-label','Economy and settlements');dialog.tabIndex=-1;
  const header=el('header');const closeButton=button('Close',close);closeButton.setAttribute('aria-label','Close economy and settlements');header.append(el('h2','Economy and settlements'),closeButton);
  const notice=el('p',undefined,'economy-notice');notice.setAttribute('role','status');notice.setAttribute('aria-live','polite');notice.hidden=true;
  const summary=el('p',undefined,'economy-summary'),gate=el('p',undefined,'economy-reason');gate.setAttribute('aria-live','polite');
  const tabs=el('div',undefined,'economy-tabs');tabs.setAttribute('role','tablist');tabs.setAttribute('aria-label','Economy sections');
  const content=el('div',undefined,'economy-content'),pages=new Map<string,HTMLElement>(),tabButtons=new Map<string,HTMLButtonElement>();
  for(const [key,name] of [['resources','Resources'],['routes','Caravans and markets'],['supply','Supply and salvage'],['settlements','Settlements and contracts']]){
    const page=el('section',undefined,'economy-grid');page.dataset.economyPage=key;page.id=`economy-page-${key}`;page.setAttribute('role','tabpanel');page.setAttribute('aria-label',name);pages.set(key,page);
    const tab=button(name,()=>showPage(key));tab.id=`economy-tab-${key}`;tab.dataset.economyTab=key;tab.setAttribute('role','tab');tab.setAttribute('aria-controls',page.id);page.setAttribute('aria-labelledby',tab.id);tabButtons.set(key,tab);tabs.append(tab);content.append(page);
  }
  const roster=el('section',undefined,'economy-card');roster.append(el('h3','Workers and raiders'));
  const selectedSummary=el('p'),unitPicker=select('Economy units');unitPicker.multiple=true;unitPicker.size=5;
  unitPicker.addEventListener('change',()=>{selected.clear();for(const option of Array.from(unitPicker.selectedOptions)){const id=Number(option.value);if(Number.isSafeInteger(id))selected.add(id);}refresh();});
  const useSelection=button('Use battlefield selection',()=>{selected.clear();const ids=new Set(callbacks.selectedIds());for(const entity of ownUnits())if(ids.has(entity.id))selected.add(entity.id);refresh();});
  roster.append(el('p','Choose workers for planting, construction, gathering deliveries and salvage. Supply raids use selected military units. Building and caravan choices are listed in their sections.'),selectedSummary,field('Owned units',unitPicker),useSelection);
  content.prepend(roster);
  function card(page:string,name:string,description:string){const result=el('section',undefined,'economy-card');result.append(el('h3',name),el('p',description));pages.get(page)!.append(result);return result;}
  function fields(card:HTMLElement,...items:HTMLLabelElement[]){const row=el('div',undefined,'economy-fields');row.append(...items);card.append(row);}
  function commandButton(card:HTMLElement,text:string,build:()=>EconomyCommand,reason:()=>string,success:string){const result=button(text,()=>{void run(build,reason,success,result);});result.dataset.economyAction=text;actions.push({control:result,reason});let row=card.querySelector('.economy-actions');if(!row){row=el('div',undefined,'economy-actions');card.append(row);}row.append(result);return result;}
  function output(card:HTMLElement,label:string){const result=el('p',undefined,'economy-summary');result.setAttribute('aria-label',label);card.append(result);return result;}
  function coordinate(label:string){const result=number(label,'0','0.5','0.5');editable.push(result);return result;}
  const groveCard=card('resources','Forestry','Workers plant a grove at a visible site. A planted grove takes time to mature into wood; planting does not provide immediate stock.'),groveX=coordinate('Grove X'),groveY=coordinate('Grove Y');fields(groveCard,field('Map X',groveX),field('Map Y',groveY));
  const groveRules=output(groveCard,'Forestry cost and timing');
  commandButton(groveCard,'Plant grove',()=>({type:'plantGrove',ids:workerIds(),...point(groveX,groveY)}),()=>needsWorkers()||costReason(ECONOMY_RULES.grove.cost),'Grove planting order issued.');
  const groveList=el('ul',undefined,'economy-list');groveList.setAttribute('aria-label','Planted groves');groveCard.append(groveList);
  const mineCard=card('resources','Deep mines','Build a deep mine on a depleted, visible ore deposit. Workers construct the mine before it supplies more ore.'),mineNode=select('Depleted ore deposit');fields(mineCard,field('Depleted ore deposit',mineNode));const mineRules=output(mineCard,'Deep mine cost');
  commandButton(mineCard,'Build deep mine',()=>({type:'buildEconomy',ids:workerIds(),kind:'deep-mine',target:numericId(mineNode,'a depleted ore deposit')}),()=>needsWorkers()||costReason(ECONOMY_RULES.deepMine.cost)||noChoice(mineNode,'No visible depleted ore deposit.'),'Deep mine construction order issued.');
  const extractorCard=card('resources','Crystal extractors','Build on a visible crystal deposit. Overcharging accelerates extraction and can damage the extractor.'),crystalNode=select('Crystal deposit'),extractor=select('Owned crystal extractor');fields(extractorCard,field('Crystal deposit',crystalNode),field('Extractor',extractor));const extractorRules=output(extractorCard,'Extractor cost and overcharge risk'),extractorInfo=output(extractorCard,'Extractor condition');
  commandButton(extractorCard,'Build crystal extractor',()=>({type:'buildEconomy',ids:workerIds(),kind:'extractor',target:numericId(crystalNode,'a visible crystal deposit')}),()=>needsWorkers()||costReason(ECONOMY_RULES.extractor.cost)||noChoice(crystalNode,'No visible crystal deposit.'),'Crystal extractor construction order issued.');
  const overchargeButton=commandButton(extractorCard,'Enable overcharge',()=>{const current=ownStructures().find(item=>item.entityId===numericId(extractor,'an extractor'));if(!current||current.kind!=='extractor'||current.progress<1)throw new Error('Choose a completed owned extractor.');return {type:'setOvercharge',id:current.entityId,enabled:!current.overcharge};},()=>noChoice(extractor,'No completed owned extractor.'),'Extractor overcharge setting changed.');
  extractor.addEventListener('change',refresh);

  const caravanCard=card('routes','Trade caravans','Recruit at a completed settlement. Choose a source and a different destination, then send a caravan carrying one resource. Trading settlements must be at least 8 tiles apart. Routes can repeat while stock and destinations remain available. Trade rewards use finite market crystal reserves.'),caravanHQ=select('Caravan recruitment settlement'),caravan=select('Caravan'),routeSource=select('Trade route source'),routeTarget=select('Trade route destination'),routeKind=select('Trade route resource'),routeAmount=number('Trade route amount','20','1'),routeRepeat=select('Repeat trade route');
  choices(routeKind,kinds.map(kind=>({id:kind,label:title(kind)})),'Choose a resource');choices(routeRepeat,[{id:'yes',label:'Repeat route'},{id:'no',label:'Single delivery'}],'Choose a route');routeAmount.max=String(ECONOMY_RULES.caravan.capacity);editable.push(routeAmount);fields(caravanCard,field('Recruitment settlement',caravanHQ));const caravanRules=output(caravanCard,'Caravan recruitment cost');
  commandButton(caravanCard,'Recruit caravan',()=>({type:'trainCaravan',id:numericId(caravanHQ,'a completed settlement')}),recruitReason,'Caravan recruitment command issued.');
  fields(caravanCard,field('Caravan',caravan),field('Source',routeSource),field('Destination',routeTarget),field('Resource',routeKind),field('Amount',routeAmount),field('Route',routeRepeat));const caravanInfo=output(caravanCard,'Selected caravan cargo');
  commandButton(caravanCard,'Start trade route',()=>({type:'tradeRoute',id:numericId(caravan,'a caravan'),source:numericId(routeSource,'a route source'),target:numericId(routeTarget,'a route destination'),kind:resourceKind(routeKind),amount:whole(routeAmount,'Trade amount',ECONOMY_RULES.caravan.capacity),repeat:routeRepeat.value==='yes'}),()=>noChoice(caravan,'No owned caravan.')||noChoice(routeSource,'No route source.')||noChoice(routeTarget,'No route destination.')||sameChoice(routeSource,routeTarget)||routeDistanceReason(),'Trade route order issued.');caravan.addEventListener('change',refresh);
  const caravanList=el('ul',undefined,'economy-list');caravanList.setAttribute('aria-label','Caravan routes');caravanCard.append(caravanList);
  const marketCard=card('routes','Neutral markets','Move an owned unit within 3 tiles to buy or sell at a visible market. Prices change with demand, and market stock can run out.'),market=select('Neutral market'),marketKind=select('Market resource'),marketAmount=number('Market amount','10','1');choices(marketKind,kinds.map(kind=>({id:kind,label:title(kind)})),'Choose a resource');editable.push(marketAmount);fields(marketCard,field('Market',market),field('Resource',marketKind),field('Amount',marketAmount));const marketInfo=output(marketCard,'Market price and stock');
  commandButton(marketCard,'Buy resource',()=>({type:'marketTrade',market:numericId(market,'a visible market'),kind:resourceKind(marketKind),amount:whole(marketAmount,'Market amount'),direction:'buy'}),()=>marketReason('buy'),'Market purchase command issued.');
  commandButton(marketCard,'Sell resource',()=>({type:'marketTrade',market:numericId(market,'a visible market'),kind:resourceKind(marketKind),amount:whole(marketAmount,'Market amount'),direction:'sell'}),()=>marketReason('sell'),'Market sale command issued.');market.addEventListener('change',refresh);marketKind.addEventListener('change',refresh);

  const raidCard=card('supply','Supply raids','Order selected units to raid a visible hostile caravan or storage building. Enemy stock and cargo are hidden until recovered.'),raidTarget=select('Supply raid target');fields(raidCard,field('Visible hostile supply',raidTarget));
  commandButton(raidCard,'Raid supply',()=>({type:'raidSupply',ids:unitIds(),target:numericId(raidTarget,'a visible hostile supply target')}),()=>needsUnits()||noChoice(raidTarget,'No visible hostile caravan or storage building.'),'Supply raid order issued.');
  const salvageCard=card('supply','Battlefield salvage','Send workers to collect visible materials left by destroyed buildings, siege engines or dropped cargo. Salvage expires if it remains uncollected.'),salvage=select('Salvage deposit');fields(salvageCard,field('Salvage',salvage));const salvageInfo=output(salvageCard,'Salvage materials and expiry');
  commandButton(salvageCard,'Collect salvage',()=>({type:'collectSalvage',ids:workerIds(),target:numericId(salvage,'visible salvage')}),()=>needsWorkers()||noChoice(salvage,'No visible salvage.'),'Salvage collection order issued.');salvage.addEventListener('change',refresh);
  const ledgerCard=card('supply','Recovered resources','This ledger records income delivered by your economy commands.'),ledgerList=el('ul',undefined,'economy-list');ledgerList.setAttribute('aria-label','Economy ledger');ledgerCard.append(ledgerList);

  const warehouseCard=card('settlements','Regional warehouses','Workers assigned to a warehouse store harvests there. Send a caravan to carry local stock to another settlement or warehouse.'),warehouseX=coordinate('Warehouse X'),warehouseY=coordinate('Warehouse Y');fields(warehouseCard,field('Map X',warehouseX),field('Map Y',warehouseY));const warehouseRules=output(warehouseCard,'Warehouse construction cost');
  commandButton(warehouseCard,'Build warehouse',()=>({type:'buildEconomy',ids:workerIds(),kind:'warehouse',...point(warehouseX,warehouseY)}),()=>needsWorkers()||costReason(ECONOMY_RULES.warehouse.cost),'Warehouse construction order issued.');
  const warehouse=select('Worker delivery warehouse');fields(warehouseCard,field('Gathering delivery destination',warehouse));const warehouseInfo=output(warehouseCard,'Warehouse stock and capacity');
  commandButton(warehouseCard,'Assign worker warehouse',()=>({type:'setWarehouse',ids:workerIds(),target:numericId(warehouse,'a completed warehouse')}),()=>needsWorkers()||noChoice(warehouse,'No completed owned warehouse.'),'Selected workers now deliver harvests to the warehouse.');
  commandButton(warehouseCard,'Use central delivery',()=>({type:'setWarehouse',ids:workerIds(),target:null}),needsWorkers,'Selected workers now use central resource delivery.');warehouse.addEventListener('change',refresh);
  const warehouseList=el('ul',undefined,'economy-list');warehouseList.setAttribute('aria-label','Warehouse worker assignments');warehouseCard.append(warehouseList);
  const deliveryCard=card('settlements','Organize a delivery','Choose owned local stock and an owned or visible allied destination. A caravan loads available resources at the source and carries them across the map.'),deliveryCaravan=select('Delivery caravan'),deliverySource=select('Delivery stock source'),deliveryTarget=select('Delivery stock destination'),deliveryInputs=new Map<ResourceKind,HTMLInputElement>();
  fields(deliveryCard,field('Caravan',deliveryCaravan),field('Source',deliverySource),field('Destination',deliveryTarget));for(const kind of kinds){const input=number(`${title(kind)} delivery amount`,'0');editable.push(input);deliveryInputs.set(kind,input);fields(deliveryCard,field(title(kind),input));}
  const deliveryInfo=output(deliveryCard,'Delivery source stock');
  commandButton(deliveryCard,'Deliver stock',()=>({type:'deliverStock',id:numericId(deliveryCaravan,'a caravan'),source:numericId(deliverySource,'a stock source'),target:numericId(deliveryTarget,'a destination'),stock:readStock()}),()=>noChoice(deliveryCaravan,'No owned caravan.')||noChoice(deliverySource,'No stock source.')||noChoice(deliveryTarget,'No delivery destination.')||sameChoice(deliverySource,deliveryTarget)||deliveryLayerReason(deliveryCaravan,deliverySource,storageEntities().find(e=>String(e.id)===deliveryTarget.value)),'Stock delivery order issued.');deliverySource.addEventListener('change',refresh);
  const settlementCard=card('settlements','Settlement specialization','Choose an expansion headquarters and develop it for mining, military production or research. Each settlement can choose one specialization.'),settlement=select('Expansion settlement'),specialization=select('Settlement specialization');choices(specialization,[{id:'mining',label:'Mining'},{id:'military',label:'Military'},{id:'research',label:'Research'}],'Choose a specialization');fields(settlementCard,field('Expansion settlement',settlement),field('Specialization',specialization));const specializationRules=output(settlementCard,'Specialization cost and effects'),settlementInfo=output(settlementCard,'Settlement specialization status');
  commandButton(settlementCard,'Specialize settlement',()=>({type:'specializeSettlement',id:numericId(settlement,'an expansion headquarters'),kind:specialization.value as SettlementSpecialization}),()=>costReason(ECONOMY_RULES.specialization.cost)||noChoice(settlement,'No completed expansion headquarters.')||(view?.specializations.some(item=>String(item.entityId)===settlement.value)?'This settlement already has a specialization.':''),'Settlement specialization command issued.');settlement.addEventListener('change',refresh);specialization.addEventListener('change',refresh);
  const contractCard=card('settlements','Resource contracts','Move an owned unit within 3 tiles to accept a visible neutral settlement contract. Send a caravan with the requested resource before the deadline to receive its reward.'),contract=select('Resource contract'),contractCaravan=select('Contract caravan'),contractSource=select('Contract stock source');fields(contractCard,field('Contract',contract),field('Caravan',contractCaravan),field('Stock source',contractSource));const contractInfo=output(contractCard,'Contract delivery and reward');
  commandButton(contractCard,'Accept contract',()=>({type:'acceptContract',id:numericId(contract,'an open contract')}),()=>noChoice(contract,'No visible available contract.')||contractReason(false)||contractNearbyReason(),'Resource contract acceptance command issued.');
  commandButton(contractCard,'Deliver contract',()=>({type:'deliverContract',id:numericId(contractCaravan,'a caravan'),contract:numericId(contract,'an accepted contract'),source:numericId(contractSource,'a stock source')}),()=>noChoice(contractCaravan,'No owned caravan.')||noChoice(contractSource,'No stock source.')||contractReason(true)||deliveryLayerReason(contractCaravan,contractSource,view?.contracts.find(c=>String(c.id)===contract.value)),'Contract delivery order issued.');contract.addEventListener('change',refresh);
  const contractList=el('ul',undefined,'economy-list');contractList.setAttribute('aria-label','Resource contracts');contractCard.append(contractList);
  dialog.append(header,notice,summary,gate,tabs,content);overlay.append(dialog);host.append(toolbar,overlay);root.append(host);

  function busy():boolean{return pending?.generation===contextGeneration;}
  function side():Side{return status.side??0;}
  function context():boolean{return !!game&&!!view&&!!game.players[side()];}
  function readOnly():string{return !context()?'Start or load a match first.':status.readOnly?'Economy commands are unavailable in this view.':game!.eliminated[side()]?'Your settlement has been eliminated.':game!.winner!==null||game!.draw?'The match has ended.':'';}
  function ownUnits():Entity[]{return !context()?[]:game!.entities.filter(entity=>entity.side===side()&&entity.kind==='unit'&&entity.hp>0&&!entity.illusion&&!entity.raised).sort((a,b)=>a.id-b.id);}
  function ownHQs():Entity[]{return !context()?[]:game!.entities.filter(entity=>entity.side===side()&&entity.kind==='building'&&entity.role==='hq'&&entity.hp>0&&entity.progress>=1).sort((a,b)=>a.id-b.id);}
  function ownStructures(){return (view?.structures??[]).filter(item=>item.side===side()&&item.hp>0);}
  function ownCaravans(){return (view?.caravans??[]).filter(item=>item.side===side()&&item.hp>0);}
  function unitIds():number[]{const ids=ownUnits().filter(entity=>entity.role!=='worker'&&selected.has(entity.id)).map(entity=>entity.id);if(!ids.length)throw new Error('Choose at least one owned military unit.');return ids;}
  function workerIds():number[]{const ids=ownUnits().filter(entity=>entity.role==='worker'&&!view?.caravans.some(item=>item.entityId===entity.id)&&selected.has(entity.id)).map(entity=>entity.id);if(!ids.length)throw new Error('Choose at least one owned worker.');return ids;}
  function costReason(cost:Cost):string{return !game?.players[side()]?'No active settlement.':kinds.filter(kind=>game!.players[side()][kind]+1e-8<cost[kind]).map(kind=>`Need ${amount(cost[kind])} ${kind}; ${amount(game!.players[side()][kind])} available.`).join(' ');}
  function needsUnits():string{return ownUnits().some(entity=>entity.role!=='worker'&&selected.has(entity.id))?'':'Choose at least one owned military unit.';}
  function chosenWorkers(){return ownUnits().filter(entity=>entity.role==='worker'&&!view?.caravans.some(item=>item.entityId===entity.id)&&selected.has(entity.id));}
  function needsWorkers():string{const workers=chosenWorkers();return !workers.length?'Choose at least one owned worker.':new Set(workers.map(levelOf)).size>1?'Choose workers on one map level.':'';}
  function workerLayerMismatch(point:{level?:number}){return chosenWorkers().some(worker=>!sameLevel(worker,point));}
  function layerName(point:{level?:number}){return game?.world?.levels[levelOf(point)]?.title??(levelOf(point)?`Level ${levelOf(point)+1}`:'Surface');}
  function deliveryLayerReason(cartInput:HTMLSelectElement,sourceInput:HTMLSelectElement,target:{level?:number}|undefined):string{const cart=game?.entities.find(e=>String(e.id)===cartInput.value),source=storageEntities().find(e=>String(e.id)===sourceInput.value);return cart&&source&&target&&(!sameLevel(cart,source)||!sameLevel(source,target))?'Caravan, source and destination must be on the same map level.':'';}
  function noChoice(input:HTMLSelectElement,message:string):string{return input.value&&Array.from(input.options).some(option=>option.value===input.value&&!option.disabled)?'':message;}
  function sameChoice(source:HTMLSelectElement,target:HTMLSelectElement):string{return source.value&&source.value===target.value?'Choose different source and destination settlements.':'';}
  function resourceKind(input:HTMLSelectElement):ResourceKind {if(!kinds.includes(input.value as ResourceKind))throw new Error('Choose wood, ore or crystal.');return input.value as ResourceKind;}
  function point(x:HTMLInputElement,y:HTMLInputElement){const px=Number(x.value),py=Number(y.value);if(!game||!x.value.trim()||!y.value.trim()||!Number.isFinite(px)||!Number.isFinite(py)||px<.5||py<.5||px>game.width-.5||py>game.height-.5)throw new Error('Enter a position within the map.');return {x:px,y:py};}
  function readStock():Cost {const result:Cost={wood:0,ore:0,crystal:0};for(const kind of kinds){const input=deliveryInputs.get(kind)!,value=Number(input.value);if(!input.value.trim()||!Number.isSafeInteger(value)||value<0||value>10000)throw new Error('Delivery amounts must be whole numbers from 0 to 10000.');result[kind]=value;}if(kinds.reduce((sum,kind)=>sum+result[kind],0)>ECONOMY_RULES.caravan.capacity)throw new Error(`Caravan deliveries cannot exceed ${ECONOMY_RULES.caravan.capacity} total resources.`);if(!kinds.some(kind=>result[kind]>0))throw new Error('Choose at least one resource to deliver.');return result;}
  function contractReason(deliver:boolean):string {const item=view?.contracts.find(item=>String(item.id)===contract.value);return !item?'Choose a visible contract.':deliver?item.status!=='accepted'||item.side!==side()?'Accept this contract before arranging delivery.':'':item.status!=='open'?'Only open contracts can be accepted.':'';}
  function message(text:string,failed=false){notice.textContent=text;notice.hidden=!text;notice.classList.toggle('economy-error',failed);}
  async function run(build:()=>EconomyCommand,reason:()=>string,success:string,control:HTMLButtonElement){
    if(disposed||busy()||!opened)return;refresh();const blocked=readOnly()||reason();if(blocked){message(blocked,true);return;}
    const generation=contextGeneration,operation={generation};try {const command=build();pending=operation;refresh();const accepted=await callbacks.submit(command);if(disposed||generation!==contextGeneration)return;if(!accepted)throw new Error('The economy command was rejected. Check resources, ownership, visibility and available space.');message(success);}
    catch(error){if(!disposed&&generation===contextGeneration)message(errorText(error),true);}
    finally{if(pending===operation)pending=null;if(!disposed){refresh();if(opened&&generation===contextGeneration&&document.activeElement===document.body){const fallback=Array.from(control.closest('.economy-card')?.querySelectorAll<HTMLInputElement|HTMLSelectElement>('input,select')??[]).find(input=>!input.disabled&&!input.closest('[hidden]'));if(!control.disabled)control.focus();else (fallback??tabButtons.get(activePage)??closeButton).focus();}}}
  }
  function showPage(key:string){if(!pages.has(key))return;activePage=key;for(const [name,page] of pages)page.hidden=name!==key;for(const [name,tab] of tabButtons){tab.setAttribute('aria-selected',String(name===key));tab.tabIndex=name===key?0:-1;}}
  function stockSource(id:number):Cost|null {const entity=storageEntities().find(item=>item.id===id&&item.side===side());if(!entity)return null;const structure=ownStructures().find(item=>item.entityId===id&&item.kind==='warehouse');return structure?.stock??game!.players[side()];}
  function storageEntities():Entity[]{return !context()?[]:game!.entities.filter(item=>item.kind==='building'&&(item.role==='hq'||item.role==='depot')&&item.hp>0&&item.progress===1&&(item.side===side()||game!.teams[item.side]===game!.teams[side()]&&game!.visible[side()].has(levelOf(item)*game!.width*game!.height+Math.floor(item.y)*game!.width+Math.floor(item.x)))).sort((a,b)=>a.id-b.id);}
  function routeDistanceReason():string{const source=storageEntities().find(item=>String(item.id)===routeSource.value),target=storageEntities().find(item=>String(item.id)===routeTarget.value),cart=game?.entities.find(item=>String(item.id)===caravan.value);return source&&target&&cart&&(!sameLevel(source,target)||!sameLevel(cart,source))?'Caravan and route endpoints must be on the same map level.':source&&target&&distance(source,target)<8?'Trade settlements must be at least 8 tiles apart.':'';}
  function recruitReason():string{const unavailable=costReason(ECONOMY_RULES.caravan.cost)||noChoice(caravanHQ,'No completed owned settlement.');if(unavailable)return unavailable;const recruits=view?.recruits??[];if(recruits.filter(item=>String(item.producerId)===caravanHQ.value).length>=3)return 'This settlement already has three caravans in recruitment.';const reserved=game!.entities.filter(item=>item.side===side()&&item.hp>0).reduce((sum,item)=>sum+item.queue.length,0)+recruits.length;return game!.players[side()].population+reserved>=game!.players[side()].cap?'Population capacity is full.':'';}
  function nearbyReason(point:{x:number;y:number;level?:number}|undefined):string{return point&&ownUnits().some(item=>distance(item,point)<=3)?'':'Move an owned unit within 3 tiles of the neutral settlement.';}
  function contractNearbyReason():string{return nearbyReason(view?.contracts.find(item=>String(item.id)===contract.value));}
  function marketReason(direction:'buy'|'sell'):string{const chosen=view?.markets.find(item=>String(item.id)===market.value);if(!chosen)return 'No visible neutral market.';const nearby=nearbyReason(chosen);if(nearby)return nearby;const kind=resourceKind(marketKind),value=Number(marketAmount.value);if(!marketAmount.value.trim()||!Number.isSafeInteger(value)||value<1||value>10000)return 'Market amount must be a whole number from 1 to 10000.';const currency=marketCurrency(kind),quote=marketQuote(chosen,kind,value,direction),wallet=game!.players[side()];return direction==='buy'?chosen.stock[kind]+1e-8<value?'The market does not have enough stock.':wallet[currency]+1e-8<quote?`Need ${amount(quote)} ${currency}.`:'':wallet[kind]+1e-8<value?`Need ${value} ${kind}.`:chosen.stock[currency]+1e-8<quote?'The market cannot pay for this sale.':'';}
  function listRows(list:HTMLElement,rows:string[]){const key=rows.join('\n');if(list.dataset.rows===key)return;list.dataset.rows=key;list.replaceChildren(...(rows.length?rows:['None visible.']).map(text=>el('li',text)));}
  function refresh(){
    if(disposed)return;try{game=callbacks.getGame();view=callbacks.getView();if(game!==oldGame||side()!==oldSide){oldGame=game;oldSide=side();contextGeneration++;pending=null;selected.clear();const ids=new Set(callbacks.selectedIds());for(const item of ownUnits())if(ids.has(item.id))selected.add(item.id);const home=game?.starts[side()];if(home){for(const input of [groveX,warehouseX])input.value=String(Math.min(game!.width-.5,home.x+5));for(const input of [groveY,warehouseY])input.value=String(home.y);}message('');}
      launch.disabled=!context()||!!status.blocked&&!opened;if(!opened)return;const blocked=readOnly();gate.textContent=blocked;gate.hidden=!blocked;
      summary.textContent=context()?`Player ${side()+1} · ${stock(game!.players[side()])}`:'No active economy.';
      const units=ownUnits();for(const id of selected)if(!units.some(item=>item.id===id))selected.delete(id);
      choices(unitPicker,units.map(item=>({id:item.id,label:`${view?.caravans.some(caravan=>caravan.entityId===item.id)?ECONOMY_CARAVAN.name:unitFor(game!,item).name??title(item.role)} ${item.id} · ${layerName(item)} · ${item.order.type}`})),'No owned units');for(const option of Array.from(unitPicker.options))option.selected=selected.has(Number(option.value));
      selectedSummary.textContent=`${selected.size} units chosen · ${units.filter(item=>item.role==='worker'&&!view?.caravans.some(caravan=>caravan.entityId===item.id)&&selected.has(item.id)).length} workers`;useSelection.disabled=busy()||!!blocked;
      const nodes=context()?callbacks.knownResources():[],nodeChoices=(kind:ResourceKind,depleted=false)=>nodes.filter(node=>node.kind===kind&&(!depleted||!view?.deepSites.includes(node.id))&&!view?.structures.some(item=>item.resourceId===node.id&&(depleted?item.kind==='deep-mine':item.kind==='extractor'))&&(depleted?node.amount<=1e-8:node.amount>0)).map(node=>({id:node.id,label:`${title(node.kind)} ${node.id} at ${node.x}, ${node.y} · ${amount(node.amount)} remaining · ${layerName(node)}${node.visible===false?' · remembered':''}`,disabled:node.visible!==true||workerLayerMismatch(node)}));
      choices(mineNode,nodeChoices('ore',true),'No known depleted ore');choices(crystalNode,nodeChoices('crystal'),'No known crystal deposits');
      const structures=ownStructures(),complete=structures.filter(item=>item.progress>=1),warehouses=complete.filter(item=>item.kind==='warehouse');
      choices(extractor,complete.filter(item=>item.kind==='extractor').map(item=>({id:item.entityId,label:`Extractor ${item.entityId} · ${amount(item.hp)}/${amount(item.maxHp)} HP · ${item.overcharge?'overcharged':'normal'}`})),'No completed owned extractor');
      const currentExtractor=structures.find(item=>String(item.entityId)===extractor.value);overchargeButton.textContent=currentExtractor?.overcharge?'Disable overcharge':'Enable overcharge';extractorInfo.textContent=currentExtractor?`${amount(currentExtractor.hp)}/${amount(currentExtractor.maxHp)} HP · ${currentExtractor.overcharge?'overcharge enabled':'normal extraction'} · ${stock(currentExtractor.stock)}`:'No extractor chosen.';
      const hqs=ownHQs(),hqChoices=hqs.map(item=>({id:item.id,label:`${factionFor(game!,side()).buildings.hq.name} ${item.id} at ${item.x}, ${item.y} · ${layerName(item)}`}));choices(caravanHQ,hqChoices,'No completed settlement');
      const routes=storageEntities().map(item=>{const local=view?.structures.find(structure=>structure.entityId===item.id&&structure.kind==='warehouse');return {id:item.id,label:`${item.side!==side()?'Allied ':''}${local?'Warehouse':item.role==='hq'?'Headquarters':'Depot'} ${item.id} at ${item.x}, ${item.y} · ${layerName(item)}${item.side!==side()?' · stock private':local?` · ${stock(local.stock)}`:' · central stock'}`};});const destinations=routes;
      const sourceChoices=routes.filter(item=>storageEntities().find(entity=>entity.id===item.id)?.side===side());for(const input of [routeSource,deliverySource,contractSource])choices(input,sourceChoices,'No owned stock source');for(const input of [routeTarget,deliveryTarget])choices(input,destinations,'No destination');
      const caravans=ownCaravans(),caravanChoices=caravans.map(item=>({id:item.entityId,disabled:kinds.some(kind=>item.stock[kind]>1e-8)||!!game?.entities.find(entity=>entity.id===item.entityId&&entity.carried>1e-8),label:`Caravan ${item.entityId} · ${layerName(item)} · ${stock(item.stock)} · ${amount(item.hp)}/${amount(item.maxHp)} HP`}));for(const input of [caravan,deliveryCaravan,contractCaravan])choices(input,caravanChoices,'No owned caravan');
      const currentCaravan=caravans.find(item=>String(item.entityId)===caravan.value);caravanInfo.textContent=currentCaravan?`Cargo ${stock(currentCaravan.stock)} · capacity ${amount(currentCaravan.capacity)} · ${currentCaravan.task?`${currentCaravan.task.kind}${currentCaravan.task.kind==='route'?` · ${currentCaravan.task.phase} to ${currentCaravan.task.targetId}`:''}`:'idle'}`:'No caravan chosen.';
      listRows(caravanList,[...(view?.recruits??[]).map(item=>`Caravan at settlement ${item.producerId} · recruiting · ${amount(Math.max(0,item.readyAt-(game?.time??0)))} seconds remaining`),...caravans.map(item=>`Caravan ${item.entityId} · cargo ${stock(item.stock)} · ${item.task?.kind==='route'?`${item.task.phase} from ${item.task.sourceId} to ${item.task.targetId}${item.task.repeat?' · repeating':''}`:item.task?.kind??'idle'}`)]);
      choices(market,(view?.markets??[]).map(item=>({id:item.id,label:`Market ${item.id} at ${item.x}, ${item.y}`})),'No visible neutral market');const currentMarket=view?.markets.find(item=>String(item.id)===market.value),chosenKind=resourceKind(marketKind),quotedAmount=Number(marketAmount.value);marketInfo.textContent=currentMarket?`${title(chosenKind)} price ${amount(currentMarket.prices[chosenKind])} ${marketCurrency(chosenKind)} per unit · buy ${amount(quotedAmount)} for ${amount(marketQuote(currentMarket,chosenKind,quotedAmount,'buy'))} ${marketCurrency(chosenKind)} · sell for ${amount(marketQuote(currentMarket,chosenKind,quotedAmount,'sell'))} ${marketCurrency(chosenKind)} · market stock ${stock(currentMarket.stock)} · demand ${stock(currentMarket.demand)}`:'No visible market chosen.';
      const hostile=(target:Side)=>!!game&&target!==side()&&game.teams[target]!==game.teams[side()];
      choices(raidTarget,[...(view?.structures??[]).filter(item=>hostile(item.side)&&item.kind==='warehouse'&&item.hp>0).map(item=>({id:item.entityId,label:`Hostile warehouse ${item.entityId} at ${item.x}, ${item.y} · ${amount(item.hp)}/${amount(item.maxHp)} HP`})),...(view?.caravans??[]).filter(item=>hostile(item.side)&&item.hp>0).map(item=>({id:item.entityId,label:`Hostile caravan ${item.entityId} at ${item.x}, ${item.y} · ${amount(item.hp)}/${amount(item.maxHp)} HP`}))],'No visible hostile supply');
      choices(salvage,(view?.salvage??[]).map(item=>({id:item.id,disabled:workerLayerMismatch(item),label:`${item.kind==='cargo'?'Dropped cargo':'Salvage'} ${item.id} · ${layerName(item)} · ${stock(item.stock)}`})),'No visible salvage');const currentSalvage=view?.salvage.find(item=>String(item.id)===salvage.value);salvageInfo.textContent=currentSalvage?`${stock(currentSalvage.stock)} · expires in ${amount(Math.max(0,currentSalvage.expiresAt-(game?.time??0)))} seconds`:'No visible salvage chosen.';
      listRows(ledgerList,view?([['Gathered',view.ledger.gathered],['Delivered',view.ledger.delivered],['Traded',view.ledger.traded],['Raided',view.ledger.raided],['Salvaged',view.ledger.salvaged],['Contract rewards',view.ledger.contractRewards]] as [string,Cost][]).map(([name,value])=>`${name}: ${stock(value)}`):[]);
      choices(warehouse,warehouses.map(item=>({id:item.entityId,disabled:workerLayerMismatch(item),label:`Warehouse ${item.entityId} · ${layerName(item)} · ${stock(item.stock)} · capacity ${item.capacity}`})),'No completed owned warehouse');const currentWarehouse=warehouses.find(item=>String(item.entityId)===warehouse.value);warehouseInfo.textContent=currentWarehouse?`Local stock ${stock(currentWarehouse.stock)} · capacity ${amount(currentWarehouse.capacity)}`:'No warehouse chosen.';
      listRows(warehouseList,(view?.workerWarehouses??[]).filter(item=>units.some(unit=>unit.id===item.entityId)).map(item=>`Worker ${item.entityId} delivers to warehouse ${item.warehouseId}`));const sourceStock=stockSource(Number(deliverySource.value));deliveryInfo.textContent=sourceStock?`Source stock ${stock(sourceStock)}`:'Choose an owned stock source.';
      const expansionIds=new Set(hqs.filter(item=>distance(item,game!.starts[side()])>=8).map(item=>item.id));choices(settlement,hqChoices.filter(item=>expansionIds.has(item.id)).map(item=>{const chosen=view?.specializations.find(entry=>entry.entityId===item.id);return {...item,label:item.label+(chosen?` · ${title(chosen.kind)}`:'')};}),'No expansion headquarters');const currentSpecialization=view?.specializations.find(item=>String(item.entityId)===settlement.value);settlementInfo.textContent=currentSpecialization?`${title(currentSpecialization.kind)} specialization`:'No specialization chosen for this settlement.';
      listRows(groveList,(view?.groves??[]).map(item=>`Grove ${item.id} at ${item.x}, ${item.y} · ${item.burned?'burned':item.resourceId?'harvestable':item.plantedAt<0?'awaiting planting':`matures in ${amount(Math.max(0,item.maturesAt-(game?.time??0)))} seconds`}`));
      const contracts=(view?.contracts??[]).filter(item=>item.side===null||item.side===side());choices(contract,contracts.map(item=>({id:item.id,label:`Contract ${item.id} · ${item.delivered}/${item.amount} ${item.kind} · ${item.status}`,disabled:item.status==='expired'||item.status==='complete'})),'No visible available contract');const currentContract=contracts.find(item=>String(item.id)===contract.value);contractInfo.textContent=currentContract?`${amount(currentContract.delivered)} of ${amount(currentContract.amount)} ${currentContract.kind} delivered · ${currentContract.status} · ${amount(Math.max(0,currentContract.deadline-(game?.time??0)))} seconds left · reward ${stock(currentContract.reward)}`:'No available contract chosen.';
      listRows(contractList,contracts.map(item=>`Contract ${item.id} · ${item.status} · ${amount(item.delivered)}/${amount(item.amount)} ${item.kind} · reward ${stock(item.reward)}`));
      for(const input of editable)input.disabled=busy()||!!blocked;for(const action of actions){const reason=blocked||action.reason();action.control.disabled=busy()||!!reason;action.control.title=reason;}
      for(const input of [groveX,warehouseX])input.max=String((game?.width??1)-.5);for(const input of [groveY,warehouseY])input.max=String((game?.height??1)-.5);
      showPage(activePage);
    }catch(error){message(errorText(error),true);for(const action of actions)action.control.disabled=true;}
  }
  function otherModalOpen(){return Array.from(document.querySelectorAll<HTMLElement>('[role="dialog"][aria-modal="true"]')).some(item=>item!==dialog&&!item.closest('[hidden]')&&getComputedStyle(item).display!=='none');}
  function open(){if(disposed||status.blocked||otherModalOpen())return;refresh();if(!context())return;if(!opened){previousFocus=document.activeElement instanceof HTMLElement?document.activeElement:null;opened=true;overlay.hidden=false;try{callbacks.onModal(true);}catch(error){message(errorText(error),true);}}refresh();closeButton.focus();}
  function close(){if(!opened)return;opened=false;overlay.hidden=true;try{callbacks.onModal(false);}catch(error){message(errorText(error),true);}if(previousFocus?.isConnected)previousFocus.focus();previousFocus=null;}
  function keydown(event:KeyboardEvent){if(!opened)return;if(event.key==='Escape'){event.preventDefault();event.stopImmediatePropagation();close();return;}if(event.target instanceof HTMLElement&&event.target.getAttribute('role')==='tab'&&['ArrowLeft','ArrowRight','Home','End'].includes(event.key)){event.preventDefault();const keys=[...tabButtons.keys()],at=keys.indexOf(activePage),next=event.key==='Home'?0:event.key==='End'?keys.length-1:(at+(event.key==='ArrowRight'?1:-1)+keys.length)%keys.length;showPage(keys[next]);tabButtons.get(keys[next])!.focus();return;}if(event.key!=='Tab')return;const focusable=Array.from(dialog.querySelectorAll<HTMLElement>('button,input,select,[tabindex]')).filter(item=>!item.closest('[hidden]')&&item.tabIndex>=0&&!('disabled' in item&&item.disabled));if(!focusable.length){event.preventDefault();dialog.focus();return;}if(event.shiftKey&&(document.activeElement===focusable[0]||!dialog.contains(document.activeElement))){event.preventDefault();focusable.at(-1)!.focus();}else if(!event.shiftKey&&(document.activeElement===focusable.at(-1)||!dialog.contains(document.activeElement))){event.preventDefault();focusable[0].focus();}}
  document.addEventListener('keydown',keydown,true);const stop=(event:Event)=>event.stopPropagation();for(const type of ['pointerdown','pointerup','mousedown','mouseup','click','dblclick','contextmenu','wheel','keydown'])host.addEventListener(type,stop);
  groveRules.textContent=`Cost ${stock(ECONOMY_RULES.grove.cost)} · ${ECONOMY_RULES.grove.plantSeconds} seconds to plant · ${ECONOMY_RULES.grove.growthSeconds} seconds to mature · ${ECONOMY_RULES.grove.wood} wood when mature.`;
  mineRules.textContent=`Cost ${stock(ECONOMY_RULES.deepMine.cost)} · ${ECONOMY_BUILDINGS['deep-mine'].buildTime} seconds to construct · finite reserve up to ${ECONOMY_RULES.deepMine.yield} ore.`;
  extractorRules.textContent=`Cost ${stock(ECONOMY_RULES.extractor.cost)} · ${ECONOMY_BUILDINGS.extractor.buildTime} seconds to construct · harvest ×${ECONOMY_RULES.extractor.normalGather} normally, ×${ECONOMY_RULES.extractor.overchargeGather} overcharged · ${ECONOMY_RULES.extractor.incidentChance*100}% chance of ${ECONOMY_RULES.extractor.incidentDamage} damage every ${ECONOMY_RULES.extractor.incidentSeconds} seconds while overcharged.`;
  caravanRules.textContent=`Cost ${stock(ECONOMY_RULES.caravan.cost)} · ${ECONOMY_RULES.caravan.trainSeconds} seconds to recruit · capacity ${ECONOMY_RULES.caravan.capacity}.`;
  warehouseRules.textContent=`Cost ${stock(ECONOMY_RULES.warehouse.cost)} · ${ECONOMY_BUILDINGS.warehouse.buildTime} seconds to construct · local capacity ${ECONOMY_RULES.warehouse.capacity}.`;
  specializationRules.textContent=`Cost ${stock(ECONOMY_RULES.specialization.cost)} · applies within ${ECONOMY_RULES.specialization.radius} tiles. Mining: ore harvest ×${ECONOMY_RULES.specialization.mining}. Military: training ×${ECONOMY_RULES.specialization.military}. Research: research speed ×${ECONOMY_RULES.specialization.research}.`;
  for(const input of Array.from(host.querySelectorAll('select')))input.addEventListener('change',refresh);marketAmount.addEventListener('input',refresh);
  refresh();return {update(nextStatus:EconomyToolsStatus={}){status=nextStatus;refresh();},close,dispose(){if(disposed)return;close();disposed=true;contextGeneration++;document.removeEventListener('keydown',keydown,true);host.remove();}};
}
