import type { EconomyCommand, EconomyState } from './economy-types';
import type { Entity, GameState, ResourceNode } from './types';
import { levelOf, sameLevel } from './economy-common';
export const ECONOMY_COMMAND_TYPES=['plantGrove','buildEconomy','setOvercharge','trainCaravan','tradeRoute','deliverStock','marketTrade','raidSupply','collectSalvage','setWarehouse','specializeSettlement','acceptContract','deliverContract'] as const;
const record=(v:unknown):v is Record<string,unknown>=>!!v&&typeof v==='object'&&!Array.isArray(v);
const id=(v:unknown):v is number=>Number.isSafeInteger(v)&&(v as number)>0;
const num=(v:unknown,min=0,max=10000):v is number=>typeof v==='number'&&Number.isFinite(v)&&v>=min&&v<=max;
const keys=(v:Record<string,unknown>,fields:string[])=>Object.keys(v).every(key=>fields.includes(key))&&fields.every(key=>Object.hasOwn(v,key));
const cost=(v:unknown)=>record(v)&&keys(v,['wood','ore','crystal'])&&['wood','ore','crystal'].every(k=>num(v[k]));
const kinds=['wood','ore','crystal'];
export function validateEconomyCommand(v:unknown):v is EconomyCommand {
 if(!record(v)||typeof v.type!=='string'||!ECONOMY_COMMAND_TYPES.includes(v.type as typeof ECONOMY_COMMAND_TYPES[number]))return false;
 const ids=()=>Array.isArray(v.ids)&&v.ids.length>0&&v.ids.length<=100&&v.ids.every(id)&&new Set(v.ids).size===v.ids.length;
 const positionKeys=(fields:string[])=>keys(v,v.level===undefined?fields:[...fields,'level'])&&(v.level===undefined||num(v.level,0,1)&&Number.isSafeInteger(v.level));
 if(v.type==='plantGrove')return positionKeys(['type','ids','x','y'])&&ids()&&num(v.x,0,256)&&num(v.y,0,256);
 if(v.type==='buildEconomy')return v.kind==='warehouse'?positionKeys(['type','ids','kind','x','y'])&&ids()&&num(v.x,0,256)&&num(v.y,0,256):keys(v,['type','ids','kind','target'])&&ids()&&['extractor','deep-mine'].includes(v.kind as string)&&id(v.target);
 if(v.type==='setOvercharge')return keys(v,['type','id','enabled'])&&id(v.id)&&typeof v.enabled==='boolean';
 if(v.type==='trainCaravan'||v.type==='acceptContract')return keys(v,['type','id'])&&id(v.id);
 if(v.type==='tradeRoute')return keys(v,['type','id','source','target','kind','amount','repeat'])&&id(v.id)&&id(v.source)&&id(v.target)&&kinds.includes(v.kind as string)&&num(v.amount,1)&&typeof v.repeat==='boolean';
 if(v.type==='deliverStock')return keys(v,['type','id','source','target','stock'])&&id(v.id)&&id(v.source)&&id(v.target)&&cost(v.stock);
 if(v.type==='marketTrade')return keys(v,['type','market','kind','amount','direction'])&&id(v.market)&&kinds.includes(v.kind as string)&&num(v.amount,1)&&['buy','sell'].includes(v.direction as string);
 if(v.type==='raidSupply'||v.type==='collectSalvage')return keys(v,['type','ids','target'])&&ids()&&id(v.target);
 if(v.type==='setWarehouse')return keys(v,['type','ids','target'])&&ids()&&(v.target===null||id(v.target));
 if(v.type==='specializeSettlement')return keys(v,['type','id','kind'])&&id(v.id)&&['mining','military','research'].includes(v.kind as string);
 return keys(v,['type','id','contract','source'])&&id(v.id)&&id(v.contract)&&id(v.source);
}
export function isEconomyCommand(c:{type:string}):c is EconomyCommand{return ECONOMY_COMMAND_TYPES.includes(c.type as typeof ECONOMY_COMMAND_TYPES[number]);}
interface ValidationContext {width:number;height:number;time:number;nextId:number;playerCount:number;entities:Entity[];resources:ResourceNode[];levels?:number;world?:GameState['world']}
export function validateEconomyState(value:unknown,c:ValidationContext):asserts value is EconomyState {
 const fail=(path:string):never=>{throw new Error(`Invalid economy state at ${path}.`);};
 const obj=(v:unknown,p:string,required:string[],optional:string[]=[])=>{if(!record(v)||required.some(key=>!Object.hasOwn(v,key))||Object.keys(v).some(key=>![...required,...optional].includes(key)))fail(p);return v as Record<string,unknown>;};
 const n=(v:unknown,p:string,min=0,max=1e9,integer=false)=>{if(!num(v,min,max)||integer&&!Number.isSafeInteger(v))fail(p);return v as number;};
 const array=(v:unknown,p:string,max=8192)=>{if(!Array.isArray(v)||v.length>max)fail(p);return v as unknown[];};
 const unique=(values:number[],p:string)=>{if(new Set(values).size!==values.length)fail(p);};
 const identifier=(v:unknown,p:string)=>n(v,p,1,c.nextId-1,true);
 const side=(v:unknown,p:string)=>n(v,p,0,c.playerCount-1,true);
 const vector=(v:Record<string,unknown>,p:string)=>{n(v.x,`${p}.x`,0,c.width);n(v.y,`${p}.y`,0,c.height);if(v.level!==undefined)n(v.level,`${p}.level`,0,(c.levels??c.world?.levels.length??1)-1,true);};
 const stock=(v:unknown,p:string)=>{const o=obj(v,p,kinds);for(const kind of kinds)n(o[kind],`${p}.${kind}`);return o;};
 const entity=(v:unknown,p:string,kind?:string)=>{const eid=identifier(v,p),e=c.entities.find(e=>e.id===eid);if(!e||kind&&e.kind!==kind)fail(p);return e!;};
 const flag=(v:unknown,p:string)=>{if(typeof v!=='boolean')fail(p);};
 const choice=(v:unknown,p:string,options:string[])=>{if(typeof v!=='string'||!options.includes(v))fail(p);};
 const s=obj(value,'economy',['version','groves','structures','caravans','cargo','tasks','salvage','markets','villages','contracts','specializations','workerWarehouses','deepSites','deathClaims','paidCosts','recruits','ledgers']);if(s.version!==1)fail('version');
 const allocated=new Set([...c.entities.map(e=>e.id),...c.resources.map(r=>r.id),...(c.world?[...c.world.bridges,...c.world.sites,...c.world.creatures].map(o=>o.id):[])]),economyIds=new Set<number>();
 const uniqueObjectId=(idValue:unknown,p:string,linkedVillage=false)=>{const eid=identifier(idValue,p);if(economyIds.has(eid)||allocated.has(eid)&&!linkedVillage)fail(p);allocated.add(eid);economyIds.add(eid);return eid;};
 const groveIds:number[]=[];
 array(s.groves,'groves',1600).forEach((v,i)=>{const p=`groves[${i}]`,o=obj(v,p,['id','side','x','y','plantedAt','maturesAt','burned'],['resourceId','level']);groveIds.push(uniqueObjectId(o.id,`${p}.id`));side(o.side,`${p}.side`);vector(o,p);n(o.plantedAt,`${p}.plantedAt`,-1,c.time);n(o.maturesAt,`${p}.maturesAt`,-1,c.time+60);flag(o.burned,`${p}.burned`);if((o.plantedAt as number)<0&&(o.maturesAt as number)!==-1)fail(p);if((o.plantedAt as number)>=0&&(o.maturesAt as number)<(o.plantedAt as number))fail(p);if(o.resourceId!==undefined){const rid=identifier(o.resourceId,`${p}.resourceId`);if(!c.resources.some(r=>r.id===rid&&r.kind==='wood'&&levelOf(r)===(o.level??0)&&r.x===o.x&&r.y===o.y))fail(`${p}.resourceId`);}});
 const structureIds:number[]=[];
 array(s.structures,'structures',1024).forEach((v,i)=>{const p=`structures[${i}]`,o=obj(v,p,['entityId','kind','stock','capacity','overcharge','nextIncident'],['resourceId']);const e=entity(o.entityId,`${p}.entityId`,'building');structureIds.push(e.id);choice(o.kind,`${p}.kind`,['warehouse','extractor','deep-mine']);const values=stock(o.stock,`${p}.stock`);n(o.capacity,`${p}.capacity`,0,10000);if(kinds.reduce((sum,kind)=>sum+(values[kind] as number),0)>(o.capacity as number)+1e-7)fail(`${p}.stock`);flag(o.overcharge,`${p}.overcharge`);n(o.nextIncident,`${p}.nextIncident`,0,c.time+12.1);if(o.kind!=='extractor'&&o.overcharge)fail(`${p}.overcharge`);if(o.kind==='warehouse'&&o.resourceId!==undefined||o.kind!=='warehouse'&&o.resourceId===undefined)fail(`${p}.resourceId`);if(o.resourceId!==undefined){const rid=identifier(o.resourceId,`${p}.resourceId`);if(!c.resources.some(r=>r.id===rid&&r.kind===(o.kind==='extractor'?'crystal':'ore')&&sameLevel(e,r)))fail(`${p}.resourceId`);}});unique(structureIds,'structures');
 const caravans=array(s.caravans,'caravans',1024).map((v,i)=>entity(v,`caravans[${i}]`,'unit').id);unique(caravans,'caravans');
 const cargoIds:number[]=[];array(s.cargo,'cargo',4096).forEach((v,i)=>{const p=`cargo[${i}]`,o=obj(v,p,['entityId','stock','capacity','origin','tradeValue'],['sourceId','destinationId','contractId']);cargoIds.push(entity(o.entityId,`${p}.entityId`,'unit').id);const values=stock(o.stock,`${p}.stock`);n(o.capacity,`${p}.capacity`,0,10000);if(kinds.reduce((sum,kind)=>sum+(values[kind] as number),0)>(o.capacity as number)+1e-7)fail(`${p}.stock`);choice(o.origin,`${p}.origin`,['delivery','trade','raid','salvage','contract']);n(o.tradeValue,`${p}.tradeValue`);for(const key of ['sourceId','destinationId','contractId'])if(o[key]!==undefined)identifier(o[key],`${p}.${key}`);});unique(cargoIds,'cargo');
 const salvageIds:number[]=[];array(s.salvage,'salvage',4096).forEach((v,i)=>{const p=`salvage[${i}]`,o=obj(v,p,['id','x','y','stock','expiresAt','owner','kind'],['level']);salvageIds.push(uniqueObjectId(o.id,`${p}.id`));vector(o,p);stock(o.stock,`${p}.stock`);n(o.expiresAt,`${p}.expiresAt`,0,c.time+120.1);if(o.owner!==null)side(o.owner,`${p}.owner`);choice(o.kind,`${p}.kind`,['salvage','cargo']);});
 const marketIds:number[]=[];array(s.markets,'markets',32).forEach((v,i)=>{const p=`markets[${i}]`,o=obj(v,p,['id','x','y','stock','demand','recoverAt'],['level']);marketIds.push(uniqueObjectId(o.id,`${p}.id`));vector(o,p);stock(o.stock,`${p}.stock`);const demand=obj(o.demand,`${p}.demand`,kinds);for(const kind of kinds)n(demand[kind],`${p}.demand.${kind}`,0,1e9);n(o.recoverAt,`${p}.recoverAt`,0,c.time);});
 const villages:number[]=[];array(s.villages,'villages',32).forEach((v,i)=>{const p=`villages[${i}]`,o=obj(v,p,['id','x','y','rewardPool'],['level']);const linked=c.world?.sites.some(site=>site.id===o.id&&site.kind==='village'&&site.level===(o.level??0))===true;villages.push(uniqueObjectId(o.id,`${p}.id`,linked));vector(o,p);stock(o.rewardPool,`${p}.rewardPool`);});
 const contracts:number[]=[];array(s.contracts,'contracts',96).forEach((v,i)=>{const p=`contracts[${i}]`,o=obj(v,p,['id','villageId','x','y','side','kind','amount','delivered','deadline','reward','status'],['level']);contracts.push(uniqueObjectId(o.id,`${p}.id`));if(!villages.includes(identifier(o.villageId,`${p}.villageId`)))fail(`${p}.villageId`);const village=(s.villages as Record<string,unknown>[]).find(v=>v.id===o.villageId)!;if((village.level??0)!==(o.level??0)||village.x!==o.x||village.y!==o.y)fail(`${p}.villageId`);vector(o,p);if(o.side!==null)side(o.side,`${p}.side`);choice(o.kind,`${p}.kind`,kinds);const amount=n(o.amount,`${p}.amount`,1,10000);n(o.delivered,`${p}.delivered`,0,amount);n(o.deadline,`${p}.deadline`,0,c.time+180.1);stock(o.reward,`${p}.reward`);choice(o.status,`${p}.status`,['open','accepted','complete','expired']);if((o.status==='accepted'||o.status==='complete')&&o.side===null||o.status==='complete'&&o.delivered!==o.amount)fail(p);});
 const taskIds:number[]=[];array(s.tasks,'tasks',4096).forEach((v,i)=>{const p=`tasks[${i}]`,o=obj(v,p,['entityId','kind','targetId','progress'],['sourceId','repeat','phase','amount','contractId']);const e=entity(o.entityId,`${p}.entityId`,'unit');taskIds.push(e.id);choice(o.kind,`${p}.kind`,['plant','collect','raid','route']);identifier(o.targetId,`${p}.targetId`);n(o.progress,`${p}.progress`,0,2);if(o.kind==='plant'&&!groveIds.includes(o.targetId as number)||o.kind==='collect'&&!salvageIds.includes(o.targetId as number))fail(p);if(o.kind==='route'){identifier(o.sourceId,`${p}.sourceId`);flag(o.repeat,`${p}.repeat`);choice(o.phase,`${p}.phase`,['loading','delivery']);stock(o.amount,`${p}.amount`);}if(o.contractId!==undefined&&!contracts.includes(identifier(o.contractId,`${p}.contractId`)))fail(`${p}.contractId`);});unique(taskIds,'tasks');
 const specializationIds:number[]=[];array(s.specializations,'specializations',1024).forEach((v,i)=>{const p=`specializations[${i}]`,o=obj(v,p,['entityId','kind']);const e=entity(o.entityId,`${p}.entityId`,'building');if(e.role!=='hq')fail(p);specializationIds.push(e.id);choice(o.kind,`${p}.kind`,['mining','military','research']);});unique(specializationIds,'specializations');
 const workerIds:number[]=[];array(s.workerWarehouses,'workerWarehouses',4096).forEach((v,i)=>{const p=`workerWarehouses[${i}]`,o=obj(v,p,['entityId','warehouseId']),e=entity(o.entityId,`${p}.entityId`,'unit'),w=entity(o.warehouseId,`${p}.warehouseId`,'building');if(e.role!=='worker'||caravans.includes(e.id)||e.side!==w.side||!sameLevel(e,w)||!array(s.structures,'structures').some(item=>record(item)&&item.entityId===w.id&&item.kind==='warehouse'))fail(p);workerIds.push(e.id);});unique(workerIds,'workerWarehouses');
 const deep=array(s.deepSites,'deepSites',8192).map((v,i)=>{const rid=identifier(v,`deepSites[${i}]`);if(!c.resources.some(r=>r.id===rid&&r.kind==='ore'))fail('deepSites');return rid;});unique(deep,'deepSites');
 const deaths=array(s.deathClaims,'deathClaims',16384).map((v,i)=>identifier(v,`deathClaims[${i}]`));unique(deaths,'deathClaims');
 const paidIds:number[]=[];array(s.paidCosts,'paidCosts',16384).forEach((v,i)=>{const p=`paidCosts[${i}]`,o=obj(v,p,['entityId','stock']);paidIds.push(identifier(o.entityId,`${p}.entityId`));stock(o.stock,`${p}.stock`);});unique(paidIds,'paidCosts');
 const producerQueues=new Map<number,number>();
 array(s.recruits,'recruits',3*c.entities.filter(e=>e.kind==='building'&&e.role==='hq').length).forEach((v,i)=>{const p=`recruits[${i}]`,o=obj(v,p,['producerId','side','readyAt']);const producer=entity(o.producerId,`${p}.producerId`,'building');if(producer.role!=='hq'||producer.side!==side(o.side,`${p}.side`))fail(p);const count=(producerQueues.get(producer.id)??0)+1;if(count>3)fail(p);producerQueues.set(producer.id,count);n(o.readyAt,`${p}.readyAt`,0,c.time+54.1);});
 const ledgers=array(s.ledgers,'ledgers',8);if(ledgers.length!==c.playerCount)fail('ledgers');ledgers.forEach((v,i)=>{const p=`ledgers[${i}]`,fields=['gathered','delivered','traded','raided','salvaged','contractRewards'],o=obj(v,p,fields);for(const key of fields)stock(o[key],`${p}.${key}`);});
}
