import { FACTIONS } from './content';
import type { BuildingDef, FactionId, UnitDef } from './types';

export type FactionStructureKind='enchanted-grove'|'tunnel'|'necropolis'|'power-relay';
export interface FactionStructureInfo {faction:FactionId;definition:BuildingDef;radius:number}
export const FACTION_STRUCTURE_INFO:Record<FactionStructureKind,FactionStructureInfo>={
 'enchanted-grove':{faction:'fairies',radius:4,definition:{...FACTIONS.fairies.buildings.depot,id:'core:fairies-enchanted-grove',name:'Enchanted Grove',cost:{wood:100,ore:20,crystal:15},hp:450,buildTime:24,description:'Conceals allied troops within four tiles. Sends harmless doubles toward visible enemy scouts every twenty seconds.'}},
 tunnel:{faction:'dwarves',radius:3,definition:{...FACTIONS.dwarves.buildings.depot,id:'core:dwarves-tunnel',name:'Tunnel Entrance',cost:{wood:150,ore:80,crystal:0},hp:650,buildTime:30,description:'Transfers nearby owned troops to another completed tunnel entrance after a three-second channel. Entrances can link map levels.'}},
 necropolis:{faction:'undead',radius:6,definition:{...FACTIONS.undead.buildings.depot,id:'core:undead-necropolis-outpost',name:'Necropolis Outpost',cost:{wood:120,ore:50,crystal:25},hp:550,buildTime:28,description:'Consecrates nearby territory for the Ashen Host. Raised allies regain health and their remaining lifetime is sustained while inside its six-tile radius.'}},
 'power-relay':{faction:'automata',radius:8,definition:{...FACTIONS.automata.buildings.depot,id:'core:automata-power-relay',name:'Power Relay',cost:{wood:70,ore:30,crystal:10},hp:350,buildTime:18,description:'Connects structures within eight tiles to a headquarters power network. Connected buildings share shield reserves and power defensive towers.'}},
};
export const CORPSE_WAGON:UnitDef={...FACTIONS.undead.units.siege,id:'core:undead-corpse-wagon',name:'Corpse Wagon',role:'special',cost:{wood:100,ore:45,crystal:0},hp:160,damage:0,ability:undefined,armor:1,range:1,speed:1.8,cooldown:1,trainTime:24,sight:7,age:2,buildingDamageMultiplier:1,description:'Carries up to six mortal bodies. Collect corpses before they decay, then deliver them to a Gravecaller. Cargo retains its original decay deadline.'};
export const TROPHY_STANDARD:BuildingDef={...FACTIONS.orcs.buildings.depot,id:'core:orcs-trophy-standard',name:'Trophy Standard',cost:{wood:0,ore:0,crystal:0},size:1,hp:160,buildTime:1,sight:4,description:'A victor spends two trophies to raise this banner. Nearby allies gain 10% damage and recover morale. Enemies can destroy it.'};
export const FACTION_SYSTEM_DEFINITIONS:Record<FactionId,{units:UnitDef[];buildings:BuildingDef[]}>=Object.fromEntries(Object.keys(FACTIONS).map(faction=>[faction,{units:faction==='undead'?[CORPSE_WAGON]:[],buildings:[...Object.values(FACTION_STRUCTURE_INFO).filter(info=>info.faction===faction).map(info=>info.definition),...(faction==='orcs'?[TROPHY_STANDARD]:[])]}])) as Record<FactionId,{units:UnitDef[];buildings:BuildingDef[]}>;
export function factionSystemDefinition(id:string|undefined):UnitDef|BuildingDef|undefined{return id?Object.values(FACTION_SYSTEM_DEFINITIONS).flatMap(f=>[...f.units,...f.buildings]).find(d=>d.id===id):undefined;}
export function factionStructureKind(id:string|undefined):FactionStructureKind|undefined{return (Object.keys(FACTION_STRUCTURE_INFO) as FactionStructureKind[]).find(kind=>FACTION_STRUCTURE_INFO[kind].definition.id===id);}
