import { TERRAIN } from './maps';
import { BIOMES } from './world-map';
import type { WorldState } from './world-types';

/** Validate runtime state without requiring a destroyed or burning map to stay connected. */
export function validateWorldState(input:unknown,width:number,height:number,nextId:number,players:number):asserts input is WorldState {
 const fail=(path:string):never=>{throw new Error(`Invalid save world at ${path}.`);};
 const record=(v:unknown,path:string,fields:string[],optional:string[]=[]):Record<string,unknown>=>{if(!v||typeof v!=='object'||Array.isArray(v)||Object.keys(v).some(k=>!fields.includes(k)&&!optional.includes(k))||fields.some(k=>!Object.hasOwn(v,k)))fail(path);return v as Record<string,unknown>;};
 const list=(v:unknown,path:string,max:number):unknown[]=>{if(!Array.isArray(v)||v.length>max)fail(path);return v as unknown[];};
 const number=(v:unknown,path:string,min=0,max=1e12,int=false):number=>{if(typeof v!=='number'||!Number.isFinite(v)||v<min||v>max||int&&!Number.isSafeInteger(v))fail(path);return v as number;};
 const world=record(input,'state',['version','biome','levels','transitions','bridges','fires','sites','creatures','dayLength','seasonLength','weatherLength','nextEnvironmentAt','iceTiles','thawWarned'],['revision']);
 if(world.revision!==undefined)number(world.revision,'revision',0,1e12,true);
 if(world.version!==1||!BIOMES.includes(world.biome as typeof BIOMES[number])||typeof world.thawWarned!=='boolean')fail('version/biome/flags');
 const levels=list(world.levels,'levels',2);if(!levels.length)fail('levels');const area=width*height;
 const coord=(v:Record<string,unknown>,path:string)=>{number(v.x,`${path}.x`,0,width);number(v.y,`${path}.y`,0,height);number(v.level,`${path}.level`,0,levels.length-1,true);};
 const side=(v:unknown,path:string)=>{if(v!==null)number(v,path,0,players-1,true);};
 const ids=new Set<number>(),id=(v:unknown,path:string,allocate=true)=>{const n=number(v,path,1,nextId-1,true);if(allocate){if(ids.has(n))fail(`${path}duplicate`);ids.add(n);}return n;};
 const cost=(v:unknown,path:string)=>{const c=record(v,path,['wood','ore','crystal']);for(const kind of ['wood','ore','crystal'])number(c[kind],`${path}.${kind}`,0,1e9);};
 for(let i=0;i<levels.length;i++){const l=record(levels[i],`levels${i}`,['id','title','terrain','elevation']);if(l.id!==i||typeof l.title!=='string'||l.title.length>80)fail(`levels${i}.id/title`);const terrain=list(l.terrain,`levels${i}.terrain`,area),elevation=list(l.elevation,`levels${i}.elevation`,area);if(terrain.length!==area||elevation.length!==area)fail(`levels${i}.dimensions`);terrain.forEach((t,j)=>{if(typeof t!=='string'||!Object.hasOwn(TERRAIN,t))fail(`levels${i}.terrain${j}`);});elevation.forEach((e,j)=>number(e,`levels${i}.elevation${j}`,0,3,true));}
 const transitionIds=new Set<number>();for(const [i,v] of list(world.transitions,'transitions',64).entries()){const t=record(v,`transition${i}`,['id','from','to']),n=number(t.id,`transition${i}.id`,1,0x7fffffff,true);if(transitionIds.has(n))fail(`transition${i}.duplicate`);transitionIds.add(n);for(const field of ['from','to'])coord(record(t[field],`transition${i}.${field}`,['x','y','level']),`transition${i}.${field}`);if((t.from as Record<string,unknown>).level===(t.to as Record<string,unknown>).level)fail(`transition${i}.levels`);}
 for(const [i,v] of list(world.bridges,'bridges',512).entries()){const b=record(v,`bridge${i}`,['id','x','y','level','hp','maxHp','tiles','rebuilding','repairSide']);id(b.id,`bridge${i}.id`);coord(b,`bridge${i}`);const max=number(b.maxHp,`bridge${i}.maxHp`,1,1e9);number(b.hp,`bridge${i}.hp`,0,max);number(b.rebuilding,`bridge${i}.rebuilding`,0,1);side(b.repairSide,`bridge${i}.repairSide`);const tiles=list(b.tiles,`bridge${i}.tiles`,area);if(!tiles.length||new Set(tiles).size!==tiles.length)fail(`bridge${i}.tiles`);tiles.forEach((t,j)=>number(t,`bridge${i}.tiles${j}`,0,area-1,true));}
 const fireKeys=new Set<string>();for(const [i,v] of list(world.fires,'fires',area*levels.length).entries()){const f=record(v,`fire${i}`,['x','y','level','heat','expires','nextSpread']);coord(f,`fire${i}`);number(f.heat,`fire${i}.heat`,0,1);number(f.expires,`fire${i}.expires`);number(f.nextSpread,`fire${i}.nextSpread`);const k=`${f.level},${Math.floor(f.x as number)},${Math.floor(f.y as number)}`;if(fireKeys.has(k))fail(`fire${i}.duplicate`);fireKeys.add(k);}
 const sites=list(world.sites,'sites',128),siteIds=new Set<number>(),creatureRefs=new Set<number>();for(const [i,v] of sites.entries()){const site=record(v,`site${i}`,['id','x','y','level','kind','owner','loyalty','progress','capturing','reward','rewarded','request','supplied','creatureIds','respawnAt']);siteIds.add(id(site.id,`site${i}.id`));coord(site,`site${i}`);if(!['relic','village','monster'].includes(site.kind as string)||typeof site.supplied!=='boolean')fail(`site${i}.kind/flags`);side(site.owner,`site${i}.owner`);side(site.capturing,`site${i}.capturing`);const loyalty=list(site.loyalty,`site${i}.loyalty`,players);if(loyalty.length!==players)fail(`site${i}.loyalty`);loyalty.forEach((l,j)=>number(l,`site${i}.loyalty${j}`,0,100));number(site.progress,`site${i}.progress`,0,1);cost(site.reward,`site${i}.reward`);cost(site.request,`site${i}.request`);for(const player of list(site.rewarded,`site${i}.rewarded`,players))number(player,`site${i}.rewarded`,0,players-1,true);if(new Set(site.rewarded as unknown[]).size!==(site.rewarded as unknown[]).length)fail(`site${i}.rewarded`);for(const n of list(site.creatureIds,`site${i}.creatureIds`,16)){const target=id(n,`site${i}.creatureId`,false);if(creatureRefs.has(target))fail(`site${i}.duplicateCreature`);creatureRefs.add(target);}number(site.respawnAt,`site${i}.respawnAt`);}
 const creatures=list(world.creatures,'creatures',2048),creatureIds=new Set<number>();for(const [i,v] of creatures.entries()){const creature=record(v,`creature${i}`,['id','site','x','y','level','hp','maxHp','cooldown','target','path','patrol','respawnAt']),n=id(creature.id,`creature${i}.id`);creatureIds.add(n);coord(creature,`creature${i}`);if(!siteIds.has(number(creature.site,`creature${i}.site`,1,nextId-1,true)))fail(`creature${i}.site`);const max=number(creature.maxHp,`creature${i}.maxHp`,1,1e9);number(creature.hp,`creature${i}.hp`,0,max);for(const field of ['cooldown','patrol','respawnAt'])number(creature[field],`creature${i}.${field}`);if(creature.target!==null)id(creature.target,`creature${i}.target`,false);for(const [j,p] of list(creature.path,`creature${i}.path`,area*16).entries()){if(!p||typeof p!=='object'||Array.isArray(p)||Object.keys(p).some(k=>!['x','y','level'].includes(k)))fail(`creature${i}.path${j}`);const point=p as Record<string,unknown>;coord({...point,level:point.level??0},`creature${i}.path${j}`);}}
 if(creatureRefs.size!==creatureIds.size||[...creatureRefs].some(n=>!creatureIds.has(n)))fail('siteCreatureReferences');
 for(const site of sites as Record<string,unknown>[])for(const n of site.creatureIds as number[])if((creatures as Record<string,unknown>[]).find(c=>c.id===n)?.site!==site.id)fail('creatureSiteReference');
 const iceKeys=new Set<string>();for(const [i,v] of list(world.iceTiles,'iceTiles',area*levels.length).entries()){const ice=record(v,`ice${i}`,['level','tile']);number(ice.level,`ice${i}.level`,0,levels.length-1,true);number(ice.tile,`ice${i}.tile`,0,area-1,true);const k=`${ice.level},${ice.tile}`;if(iceKeys.has(k))fail(`ice${i}.duplicate`);iceKeys.add(k);}
 for(const field of ['dayLength','seasonLength','weatherLength'])number(world[field],field,.05,1e6);number(world.nextEnvironmentAt,'nextEnvironmentAt');
}
