import assert from 'node:assert/strict';
import { createHash } from 'node:crypto';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { resolve } from 'node:path';
import { pathToFileURL } from 'node:url';

/** Drive the mounted panel and read DOM-published production simulation state. */
export async function verifyFactions(page,baseUrl='http://127.0.0.1:5296',capture=async()=>{}){
  const errors=[];page.on('pageerror',error=>errors.push(error.message));
  await page.goto(`${baseUrl}/scripts/factions/fixture.html?art=placeholder`);
  await page.waitForFunction(()=>JSON.parse(document.querySelector('#proof-data').textContent).ready);
  const snapshot=async()=>JSON.parse(await page.locator('#proof-data').textContent()),evidence={};
  const battlefieldCapture=async name=>{await page.locator('#fixture').evaluate(card=>{card.hidden=true;});try{await page.waitForTimeout(80);await capture(name);}finally{await page.locator('#fixture').evaluate(card=>{card.hidden=false;});}};
  const action=name=>page.getByRole('button',{name,exact:true});
  const entity=(state,name)=>state.entities.find(item=>item.id===state.ids[name]);
  const faction=async value=>{await page.getByLabel('Fixture faction',{exact:true}).selectOption(value);await page.waitForFunction(value=>JSON.parse(document.querySelector('#proof-data').textContent).faction===value,value);};
  const select=async name=>action(`Select fixture ${name}`).click();
  const advance=async seconds=>{const before=await snapshot();for(let left=seconds;left>0;left-=left>=30?30:1)await action(`Advance fixture simulation by ${left>=30?'30 seconds':'1 second'}`).click();const after=await snapshot();assert(Math.abs(after.time-before.time-seconds)<1e-6);return after;};
  const point=async(x=16.5,y=14.5)=>{await page.getByLabel('Faction destination X',{exact:true}).fill(String(x));await page.getByLabel('Faction destination Y',{exact:true}).fill(String(y));await page.getByLabel('Faction destination level',{exact:true}).selectOption('0');};
  const run=async(name,type)=>{const before=(await snapshot()).commands.length;await action(name).click();const state=await snapshot();assert.equal(state.commands.length,before+1);assert.equal(state.commands.at(-1).accepted,true);assert.equal(state.commands.at(-1).command.type,type);return state;};
  const build=async(name,id,x=16.5,y=14.5)=>{await select('worker');await point(x,y);const state=await run(name,'buildFactionStructure');const created=state.entities.find(item=>item.definitionId===id&&item.progress===0);assert(created);assert.equal(entity(state,'worker').order.target,created.id);const completed=await advance(35);assert.equal(completed.entities.find(item=>item.id===created.id).progress,1);return completed;};
  const initial=await snapshot();
  assert.equal(initial.system.fury[0],100);
  let state=await run('Assault chant','warChant');assert.equal(state.system.fury[0],75);assert.equal(entity(state,'soldier').factionState.chant.kind,'assault');evidence.assaultChantSpendsFuryAndReachesTroop=true;
  state=await run('Bulwark chant','warChant');assert.equal(state.system.fury[0],50);assert.equal(entity(state,'soldier').factionState.chant.kind,'bulwark');evidence.bulwarkChantSpendsFuryAndReachesTroop=true;
  state=await run('Raise trophy standard','trophyStandard');assert.equal(entity(state,'soldier').factionState.trophyKills,0);assert(state.entities.some(item=>item.definitionId==='core:orcs-trophy-standard'&&item.progress===1));evidence.trophyStandardConsumesEarnedTrophies=true;await capture('orcs');
  state=await advance(13);assert.equal(entity(state,'soldier').factionState.chant,undefined);evidence.chantExpiresInRunningSimulation=true;

  await faction('fairies');await select('specialist');state=await run('Conjure illusions','ability');const illusion=state.entities.find(item=>item.illusion);assert(illusion);assert.equal(await action('Conjure illusions').isEnabled(),false);evidence.veilweaverConjuresRealIllusions=true;
  await select('soldier');await page.getByLabel('Owned illusion',{exact:true}).selectOption(String(illusion.id));const from=entity(state,'soldier'),crystal=state.player.crystal;state=await run('Swap with illusion','illusionSwap');assert.equal(entity(state,'soldier').x,illusion.x);assert.equal(entity(state,'soldier').y,illusion.y);assert.equal(state.entities.find(item=>item.id===illusion.id).x,from.x);assert.equal(state.player.crystal,crystal-15);assert((await page.getByLabel('Selected faction unit details',{exact:true}).textContent()).includes('Swap ready in 10s'));evidence.illusionSwapChangesPositionsAndPaysCrystal=true;await capture('fairies-swap');
  await faction('orcs');await faction('fairies');state=await build('Build enchanted grove','core:fairies-enchanted-grove');assert.equal(entity(state,'soldier').concealed,true);evidence.completedGroveConcealsNearbyTroop=true;await capture('fairies-grove');

  await faction('dwarves');await select('artillery');for(const [name,modification] of [['Stone shot','stone'],['Grapeshot','grapeshot'],['Incendiary shot','incendiary'],['Reinforce artillery','reinforced']]){const before=await snapshot();state=await run(name,'modifyArtillery');assert.equal(entity(state,'siege').factionState.artillery,modification);assert.equal(state.player.wood,before.player.wood-25);assert.equal(state.player.ore,before.player.ore-20);evidence[`${modification}FittingReachesArtillery`]=true;}
  await select('soldier');const exit=state.ids.tunnels[1];await page.getByLabel('Owned tunnel exit',{exact:true}).selectOption(String(exit));await run('Travel through tunnel','tunnelTravel');state=await advance(1);assert(Math.abs(entity(state,'soldier').factionState.tunnel.progress-1/3)<1e-6);assert((await page.getByLabel('Selected faction unit details',{exact:true}).textContent()).includes('33%'));evidence.tunnelChannelProgressVisible=true;await capture('dwarves-channel');await battlefieldCapture('dwarves-channel-battlefield');state=await advance(3);const destination=state.entities.find(item=>item.id===exit);assert.equal(entity(state,'soldier').factionState.tunnel,undefined);assert(Math.hypot(entity(state,'soldier').x-destination.x,entity(state,'soldier').y-destination.y)<3);evidence.tunnelTravelCompletesAtOwnedExit=true;
  await build('Build tunnel entrance','core:dwarves-tunnel');evidence.workerBuildsTunnelEntrance=true;await capture('dwarves');

  await faction('undead');const beforeWagon=await snapshot(),deadline=beforeWagon.corpses[0].expires;state=await run('Recruit corpse wagon','train');assert.deepEqual(entity(state,'barracks').queueDefinitionIds,['core:undead-corpse-wagon']);assert.equal(state.player.wood,beforeWagon.player.wood-100);assert.equal(state.player.ore,beforeWagon.player.ore-45);state=await advance(30);assert.equal(state.entities.filter(item=>item.definitionId==='core:undead-corpse-wagon').length,2);assert.deepEqual(entity(state,'barracks').queue,[]);evidence.ordinaryProductionCompletesCorpseWagon=true;
  await select('wagon');await run('Collect corpses','collectCorpses');state=await advance(1);assert.equal(entity(state,'wagon').factionState.corpseCargo[0].expires,deadline);assert.equal(state.corpses.length,0);evidence.wagonCollectsBodyWithOriginalDeadline=true;await capture('undead-cargo');await battlefieldCapture('undead-cargo-battlefield');await run('Deliver corpses','deliverCorpses');state=await advance(4);assert.equal(entity(state,'wagon').factionState.corpseCargo.length,0);assert.equal(entity(state,'special').factionState.deliveredCorpses[0].expires,deadline);await select('specialist');assert((await page.getByLabel('Selected faction unit details',{exact:true}).textContent()).includes('1 delivered bodies ready'));evidence.wagonDeliversBodyToOwnedGravecaller=true;await capture('undead-delivery');
  state=await build('Build necropolis','core:undead-necropolis-outpost');assert.equal(entity(state,'special').factionState.deliveredCorpses.length,0);evidence.workerCompletesNecropolis=true;evidence.deliveredBodiesStillDecay=true;await capture('undead-necropolis');

  await faction('tideborn');await select('specialist');await point(15.5,16.5);for(const terrain of ['mud','shallows','water']){await page.getByLabel('Shaped terrain',{exact:true}).selectOption(terrain);const before=await snapshot();state=await run('Shape water','shapeWater');assert.equal(state.player.crystal,before.player.crystal-25);const effect=state.system.terrainEffects[0];assert(effect.tiles.length>0);assert(effect.tiles.every(tile=>tile.after===terrain&&state.terrain[Math.floor(tile.y)*state.width+Math.floor(tile.x)]===terrain));assert.equal(await action('Shape water').isEnabled(),false);evidence[`${terrain}ShapingChangesRealTerrain`]=true;if(terrain==='water')await capture('tideborn');state=await advance(21);assert.equal(state.system.terrainEffects.length,0);assert(effect.tiles.every(tile=>state.terrain[Math.floor(tile.y)*state.width+Math.floor(tile.x)]===tile.before));assert.equal(await action('Shape water').isEnabled(),true);}
  evidence.shapedTerrainExpiresAndCasterRecharges=true;

  await faction('automata');state=await advance(1);assert.equal(entity(state,'tower').factionState.power.connected,false);state=await build('Build power relay','core:automata-power-relay',13.5,14.5);assert.equal(entity(state,'tower').factionState.power.connected,true);await select('tower');assert((await page.getByLabel('Selected faction unit details',{exact:true}).textContent()).includes('Power connected'));assert((await page.getByLabel('Selected faction unit details',{exact:true}).textContent()).includes('Shield 80/80'));evidence.completedRelayConnectsTowerToHeadquarters=true;evidence.selectedBuildingShowsPowerAndShield=true;await capture('automata');await battlefieldCapture('automata-battlefield');
  await action('Toggle fixture read-only').click();assert.equal(await action('Build power relay').isEnabled(),false);assert((await page.getByText('Faction commands are unavailable in this view.',{exact:true}).count())>0);evidence.readOnlyDisablesFactionCommands=true;await capture('read-only');
  await action('Close faction powers').click();assert.equal(await page.locator('[data-faction-launch]').getAttribute('aria-expanded'),'false');await page.locator('[data-faction-launch]').click();assert.equal(await page.locator('[data-faction-launch]').getAttribute('aria-expanded'),'true');evidence.panelReopens=true;
  assert.deepEqual(errors,[]);return {evidence,initial,final:await snapshot(),browserErrors:errors};
}

if(process.argv[1]&&import.meta.url===pathToFileURL(resolve(process.argv[1])).href){
  const output=resolve('work/faction-ui-proof');await mkdir(output,{recursive:true});
  const {chromium}=await import(process.env.OVF_PLAYWRIGHT_MODULE??'playwright'),browser=await chromium.launch({headless:true});
  try{const page=await browser.newPage({viewport:{width:1280,height:900}}),result=await verifyFactions(page,process.env.OVF_FACTIONS_URL??'http://127.0.0.1:5296',name=>page.screenshot({path:resolve(output,`${name}.png`)}));const sourceFiles=['src/core/commands.ts','src/core/faction-systems.ts','src/core/faction-systems-content.ts','src/core/maps.ts','src/core/navigation.ts','src/core/observation.ts','src/core/saves.ts','src/core/simulation.ts','src/core/tactics.ts','src/core/types.ts','src/game/GameScene.ts','src/game/FactionOverlay.ts','src/game/TacticsOverlay.ts','src/ui/FactionTools.ts','src/ui/faction-tools.css','src/online/render-state.ts','src/online/protocol.ts','src/server/views.ts','tests/faction-systems.test.ts','tests/faction-tools.test.ts','tests/combat-tactics.test.ts','tests/tactics-tools.test.ts','tests/online-render-state.test.ts','scripts/factions/fixture-state.ts','scripts/factions/fixture.ts','scripts/verify_factions.mjs'];const sourceSha256={};for(const file of sourceFiles)sourceSha256[file]=createHash('sha256').update(await readFile(resolve(file))).digest('hex');await writeFile(resolve(output,'results.json'),JSON.stringify({...result,sourceSha256},null,2));console.log(JSON.stringify(result.evidence,null,2));}finally{await browser.close();}
}
