import assert from 'node:assert/strict';
import {prepareEconomyProof,observePage,nativeSessionEquality,finishEconomyProof} from './economy/browser-proof.mjs';
const {chromium}=await import(process.env.OVF_PLAYWRIGHT_MODULE??'playwright');
const base=process.argv[2],out=process.argv[3];assert(base&&out,'Pass the frozen preview and a new modal evidence directory.');
const context=await prepareEconomyProof(base,out,'economy-modal');
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']}),page=await browser.newPage({viewport:{width:1280,height:720},acceptDownloads:true});
const result={base,sourceCommit:context.sourcePin,productionSourceCommit:context.sourcePin,buildId:context.buildId,checks:[],errors:[]};observePage(page,result,context);
page.on('pageerror',error=>result.errors.push(error.message));
const record=(name,value=true)=>{result.checks.push({name,value});console.log(`${name}: ${JSON.stringify(value)}`);};
try{
 await page.goto(base);await page.locator('.mod-library > summary').click();await page.getByRole('button',{name:'Install Lantern Keepers example',exact:true}).click();await page.locator('#map-size').selectOption('small');await page.getByLabel('World biome',{exact:true}).selectOption('forest');await page.getByLabel('Enable team match setup',{exact:true}).check();await page.getByLabel('Victory mode',{exact:true}).selectOption('hill');await page.locator('.skirmish-roster [data-rule-group="draft"] > summary').click();await page.getByLabel('Enable army draft',{exact:true}).check();await page.getByLabel('Draft ban rounds',{exact:true}).fill('0');await page.getByLabel('Draft pick rounds',{exact:true}).fill('1');await page.getByLabel('Draft turn seconds',{exact:true}).fill('60');
 await page.getByRole('button',{name:'Play Lantern Keepers',exact:true}).click();await page.waitForSelector('.loading-battle[hidden]',{state:'attached',timeout:60000});await page.waitForSelector('.objective-overlay:not([hidden])');
 const draft=await page.evaluate(()=>({tick:window.rts.state.tick,selected:window.rts.selected,paused:window.rts.paused}));await page.keyboard.press('F2');assert.deepEqual(await page.evaluate(()=>window.rts.selected),draft.selected);await page.waitForFunction(tick=>window.rts.state.tick>tick+2,draft.tick);assert.equal(await page.evaluate(()=>window.rts.paused),false);record('Objectives owns keyboard input while draft ticks remain live',draft);
 await page.getByRole('button',{name:'Pick Lantern Duelist',exact:true}).click();await page.waitForFunction(()=>window.rts.state.draft.status==='complete');assert.equal(await page.evaluate(()=>window.rts.state.draft.picks[0][0]),'lantern:duelist');record('Objective draft command remains accepted through the normal application');
 await page.getByRole('button',{name:'Close objectives',exact:true}).click();
 for(const viewport of [{width:1280,height:720},{width:520,height:720}]){
  await page.setViewportSize(viewport);await page.waitForFunction(()=>{const toolbar=document.querySelector('.session-toolbar'),world=document.querySelector('.world-tools');return world.getBoundingClientRect().top>=toolbar.getBoundingClientRect().bottom+7;});
  const geometry=await page.evaluate(()=>{const toolbar=document.querySelector('.session-toolbar'),world=document.querySelector('.world-tools');return {toolbar:{top:toolbar.getBoundingClientRect().top,bottom:toolbar.getBoundingClientRect().bottom},worldTop:world.getBoundingClientRect().top,buttons:Array.from(toolbar.querySelectorAll('button')).filter(b=>!b.disabled&&b.getBoundingClientRect().width>0).map(b=>{const r=b.getBoundingClientRect(),hit=document.elementFromPoint(r.x+r.width/2,r.y+r.height/2);return {name:b.textContent,hit:b===hit||b.contains(hit),rect:{x:r.x,y:r.y,width:r.width,height:r.height}};})};});
  assert(geometry.buttons.length>=5);for(const button of geometry.buttons){assert(button.hit,`Launcher ${button.name} is covered at ${viewport.width}px`);assert(button.rect.x>=0&&button.rect.x+button.rect.width<=viewport.width);}
  record(`Shared launcher hit tests and World placement at ${viewport.width} by ${viewport.height}`,geometry);
  for(const tool of ['saves','replay','analysis','production','controls','report','photo']){await page.locator(`[data-session-tool="${tool}"]`).click();if(tool==='photo'){await page.waitForSelector('.photo-mode');await page.getByRole('button',{name:'Exit photo mode',exact:true}).click();}else{await page.waitForSelector('.session-overlay:not([hidden])');await page.getByRole('button',{name:'Close session tools',exact:true}).click();}}
  for(const [selector,closeName] of [['[data-planning-launch]','Close settlement planning'],['.session-toolbar button:has-text("Online")','Close online play'],['[data-tournament-tool="dashboard"]','Close tournament dashboard']]){await page.locator(selector).click();await page.getByRole('button',{name:closeName,exact:true}).click();}
  record(`Every shared launcher opens through native click at ${viewport.width}px`);
  await page.locator('[data-economy-launch]').click();await page.getByRole('dialog',{name:'Economy and settlements',exact:true}).waitFor();assert.equal(await page.evaluate(()=>window.rts.paused),true);
  const frozen=await page.evaluate(()=>({tick:window.rts.state.tick,selected:window.rts.selected}));await page.keyboard.press('F2');await page.waitForTimeout(300);assert.deepEqual(await page.evaluate(()=>({tick:window.rts.state.tick,selected:window.rts.selected})),frozen);
  const close=page.getByRole('button',{name:'Close economy and settlements',exact:true});await close.focus();await page.keyboard.press('Shift+Tab');assert(await page.evaluate(()=>document.querySelector('.economy-dialog').contains(document.activeElement)));await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement.getAttribute('aria-label')==='Close economy and settlements'));
  await page.screenshot({path:`${out}/economy-${viewport.width}.png`});await page.keyboard.press('Escape');await page.waitForSelector('.economy-overlay[hidden]',{state:'attached'});assert.equal(await page.evaluate(()=>window.rts.paused),false);assert(await page.locator('[data-economy-launch]').evaluate(b=>document.activeElement===b));record(`Economy pauses, traps focus, suppresses keyboard and restores input at ${viewport.width}px`);
  await page.locator('[data-objective-tool="progress"]').click();await page.waitForSelector('.objective-overlay:not([hidden])');assert.equal(await page.evaluate(()=>window.rts.paused),false);await page.keyboard.press('Escape');await page.waitForSelector('.objective-overlay[hidden]',{state:'attached'});record(`Objectives launcher opens and Escape closes at ${viewport.width}px`);
  await page.locator('[data-session-tool="saves"]').click();await page.waitForSelector('.session-overlay:not([hidden])');await page.waitForFunction(()=>document.querySelector('[data-economy-launch]')?.disabled===true,null,{timeout:5000});assert.equal(await page.locator('[data-economy-launch]').isDisabled(),true);await page.getByRole('button',{name:'Close session tools',exact:true}).click();record(`Session modal disables Economy launcher at ${viewport.width}px`);
 }
 assert.equal(result.checks.length,12);assert(result.checks.every(check=>check.value!==false));result.sessionEquality=await nativeSessionEquality(page,context);assert.deepEqual(result.errors,[]);result.passed=true;
}catch(error){result.passed=false;result.error=String(error);await page.screenshot({path:`${out}/failure.png`}).catch(()=>{});throw error;}finally{await browser.close();result.browserClosed=true;await finishEconomyProof(context,result,'results.json');}
