import assert from 'node:assert/strict';
import {readFile,writeFile} from 'node:fs/promises';
import {prepareEconomyProof,observePage,nativeSessionEquality,finishEconomyProof,freshFixture} from './economy/browser-proof.mjs';
const {chromium}=await import(process.env.OVF_PLAYWRIGHT_MODULE??'playwright');
const base=process.argv[2]??'http://127.0.0.1:4173',fixturePath=process.argv[3];
assert(fixturePath,'Pass a saved economy scenario as argument 3. The scenario needs five workers, one military unit, three empty caravans, an owned stocked warehouse, an expansion HQ, a completed extractor, an unclaimed visible crystal node, unused depleted ore, a visible hostile warehouse, salvage, and a nearby market/open contract.');
const out=process.argv[4];assert(out,'Pass a new final economy evidence directory.');
const context=await prepareEconomyProof(base,out,'economy'),fixture=await freshFixture(context,fixturePath),buildId=context.buildId;
const result={base,fixturePath,productionSourceCommit:context.sourcePin,buildId,evidence:{},errors:[],passed:false};
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']}),errors=result.errors,evidence=result.evidence;
let page;
try{
  page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.on('pageerror',error=>errors.push(error.message));observePage(page,result,context);
  await page.goto(base);await page.locator('#map-size').selectOption('small');await page.locator('.begin-match').click();await page.waitForSelector('.loading-battle[hidden]',{state:'attached',timeout:60000});
  await page.locator('[data-session-tool="saves"]').click();await page.getByLabel('Import save JSON',{exact:true}).setInputFiles({name:'economy-scenario.json',mimeType:'application/json',buffer:fixture});await page.getByRole('button',{name:'Import save',exact:true}).click();await page.waitForFunction(()=>Array.from(document.querySelectorAll('.session-notice')).some(item=>item.textContent?.includes('Save loaded.')),null,{timeout:60000});await page.getByRole('button',{name:'Close session tools',exact:true}).click();
  await page.locator('[data-economy-launch]').click();await page.getByRole('dialog',{name:'Economy and settlements',exact:true}).waitFor();
  const read=()=>page.evaluate(()=>{const s=window.rts.state;return {tick:s.tick,time:s.time,width:s.width,height:s.height,world:s.world,contentHash:s.content?.hash,art:window.rts.art,viewLevel:window.rts.viewLevel,starts:s.starts,players:s.players,teams:s.teams,entities:s.entities,resources:s.resources,terrain:s.terrain,visible:[...s.visible[0]],economy:s.economy};});
  const initial=await read();assert(initial.economy,'The loaded scenario does not contain economy state.');
  const visible=point=>initial.visible.includes((point.level??0)*initial.width*initial.height+Math.floor(point.y)*initial.width+Math.floor(point.x));
  const own=initial.entities.filter(item=>item.side===0&&item.hp>0&&!item.illusion&&!item.raised),caravanIds=new Set(initial.economy.caravans),workers=own.filter(item=>item.kind==='unit'&&item.role==='worker'&&(item.level??0)===0&&!caravanIds.has(item.id));assert(workers.length>=5,'Scenario needs five workers.');
  const hq=own.find(item=>item.kind==='building'&&item.role==='hq'&&item.progress===1&&Math.hypot(item.x-initial.starts[0].x,item.y-initial.starts[0].y)<8);assert(hq,'Scenario needs the original completed HQ.');
  const units=ids=>page.getByLabel('Economy units',{exact:true}).selectOption(ids.map(String));
  const choose=(label,value)=>page.getByLabel(label,{exact:true}).selectOption(String(value));
  const fill=(label,value)=>page.getByLabel(label,{exact:true}).fill(String(value));
  const tab=name=>page.getByRole('tab',{name,exact:true}).click();
  async function act(name){const action=page.getByRole('button',{name,exact:true});assert(await action.isEnabled(),`${name} is disabled: ${await action.getAttribute('title')}`);const previous=await page.locator('.economy-notice').textContent();await action.click();await page.waitForFunction(previous=>{const notice=document.querySelector('.economy-notice');return notice&&!notice.hidden&&notice.textContent&&notice.textContent!==previous;},previous);const notice=await page.locator('.economy-notice').innerText();assert(!(await page.locator('.economy-notice').getAttribute('class')).includes('economy-error'),`${name}: ${notice}`);}
  const occupied=new Set();
  function freePoint(){const home=initial.starts[0],points=[];for(let y=Math.max(1,Math.floor(home.y)-8);y<Math.min(initial.height-1,home.y+9);y++)for(let x=Math.max(1,Math.floor(home.x)-8);x<Math.min(initial.width-1,home.x+9);x++){const point={x:x+.5,y:y+.5},key=`${x},${y}`;if(occupied.has(key)||!visible(point)||!['grass','road','mud'].includes(initial.terrain[y*initial.width+x])||initial.entities.some(item=>item.kind==='building'&&(item.level??0)===0&&item.hp>0&&Math.hypot(item.x-point.x,item.y-point.y)<5))continue;points.push(point);}const result=points.sort((a,b)=>Math.hypot(a.x-home.x,a.y-home.y)-Math.hypot(b.x-home.x,b.y-home.y))[0];assert(result,'Scenario needs free visible construction sites.');for(let y=Math.floor(result.y)-3;y<=Math.floor(result.y)+3;y++)for(let x=Math.floor(result.x)-3;x<=Math.floor(result.x)+3;x++)occupied.add(`${x},${y}`);return result;}
  await units([workers[0].id]);const grove=freePoint();await fill('Grove X',grove.x);await fill('Grove Y',grove.y);await act('Plant grove');let state=await read();assert.equal(state.economy.groves.length,initial.economy.groves.length+1);assert(state.economy.tasks.some(item=>item.entityId===workers[0].id&&item.kind==='plant'));evidence.forestryOrderAndPayment=state.players[0].wood<initial.players[0].wood;
  await tab('Settlements and contracts');await units([workers[1].id]);const site=freePoint();await fill('Warehouse X',site.x);await fill('Warehouse Y',site.y);await act('Build warehouse');state=await read();assert.equal(state.economy.structures.filter(item=>item.kind==='warehouse').length,initial.economy.structures.filter(item=>item.kind==='warehouse').length+1);evidence.warehouseFoundationAndWorkerOrder=state.entities.some(item=>item.id===workers[1].id&&item.order.type==='build');
  await tab('Resources');await units([workers[2].id]);const ore=initial.resources.find(item=>item.kind==='ore'&&item.amount<=1e-8&&visible(item)&&!initial.economy.deepSites.includes(item.id));assert(ore,'Scenario needs unused visible depleted ore.');await choose('Depleted ore deposit',ore.id);await act('Build deep mine');state=await read();assert(state.economy.structures.some(item=>item.kind==='deep-mine'&&item.resourceId===ore.id));evidence.deepMineFoundation=true;
  await units([workers[3].id]);const crystal=initial.resources.find(item=>item.kind==='crystal'&&item.amount>0&&visible(item)&&!initial.economy.structures.some(structure=>structure.kind==='extractor'&&structure.resourceId===item.id));assert(crystal,'Scenario needs unclaimed visible crystal.');if(initial.world){const caveWorker=initial.entities.find(e=>e.side===0&&e.role==='worker'&&e.level===1);assert(caveWorker);await units([caveWorker.id]);const foreignOption=page.getByLabel('Crystal deposit',{exact:true}).locator(`option[value="${crystal.id}"]`);assert.equal(await foreignOption.count(),1,'Visible unclaimed surface crystal must remain listed.');await page.waitForFunction(({workerId,resourceId})=>{const picker=document.querySelector('[aria-label="Economy units"]'),deposit=document.querySelector('[aria-label="Crystal deposit"]');return Array.from(picker.selectedOptions).some(option=>option.value===String(workerId))&&Array.from(deposit.options).some(option=>option.value===String(resourceId)&&option.disabled);},{workerId:caveWorker.id,resourceId:crystal.id},{timeout:5000});const optionState=await foreignOption.evaluate(option=>({disabled:option.disabled,selected:Array.from(document.querySelector('[aria-label="Economy units"]').selectedOptions).map(option=>option.value)}));assert(optionState.disabled,`Surface crystal must be disabled for a cavern worker: ${JSON.stringify(optionState)}`);await units([workers[3].id]);}await choose('Crystal deposit',crystal.id);await act('Build crystal extractor');state=await read();assert(state.economy.structures.some(item=>item.kind==='extractor'&&item.resourceId===crystal.id));evidence.extractorFoundation=true;
  const extractor=initial.economy.structures.find(item=>item.kind==='extractor'&&own.some(entity=>entity.id===item.entityId&&entity.progress===1));assert(extractor,'Scenario needs a completed owned extractor.');await choose('Owned crystal extractor',extractor.entityId);await act(extractor.overcharge?'Disable overcharge':'Enable overcharge');state=await read();assert.equal(state.economy.structures.find(item=>item.entityId===extractor.entityId).overcharge,!extractor.overcharge);evidence.overchargeToggled=true;
  await tab('Caravans and markets');await choose('Caravan recruitment settlement',hq.id);const beforeRecruit=await read();await act('Recruit caravan');state=await read();assert.equal(state.economy.recruits.length,initial.economy.recruits.length+1);assert.equal(state.players[0].wood,beforeRecruit.players[0].wood-90);assert.equal(state.players[0].ore,beforeRecruit.players[0].ore-35);assert.equal(state.players[0].crystal,beforeRecruit.players[0].crystal);evidence.caravanRecruitmentPaid=true;
  const caravans=initial.economy.cargo.filter(item=>caravanIds.has(item.entityId)&&own.some(entity=>entity.id===item.entityId)&&Object.values(item.stock).every(value=>value<=1e-8));assert(caravans.length>=3,'Scenario needs three empty owned caravans.');
  const endpoint=own.find(item=>item.kind==='building'&&item.progress===1&&['hq','depot'].includes(item.role)&&Math.hypot(item.x-hq.x,item.y-hq.y)>=8);assert(endpoint,'Scenario needs a completed trading endpoint at least 8 tiles from HQ.');await choose('Caravan',caravans[0].entityId);await choose('Trade route source',hq.id);await choose('Trade route destination',endpoint.id);await choose('Trade route resource','ore');await fill('Trade route amount',5);await choose('Repeat trade route','no');await act('Start trade route');state=await read();assert(state.economy.tasks.some(item=>item.entityId===caravans[0].entityId&&item.kind==='route'&&item.sourceId===hq.id&&item.targetId===endpoint.id));assert.equal(state.economy.cargo.find(item=>item.entityId===caravans[0].entityId).origin,'trade');evidence.physicalTradeRouteOrdered=true;
  const market=initial.economy.markets.find(item=>visible(item)&&own.some(entity=>entity.kind==='unit'&&Math.hypot(entity.x-item.x,entity.y-item.y)<=3));assert(market,'Scenario needs a visible market with an owned unit within 3 tiles.');await choose('Neutral market',market.id);await choose('Market resource','crystal');await fill('Market amount',2);const beforeBuy=await read();await act('Buy resource');state=await read();assert.equal(state.players[0].crystal,beforeBuy.players[0].crystal+2);assert(state.players[0].wood<beforeBuy.players[0].wood);await fill('Market amount',1);const beforeSell=await read();await act('Sell resource');state=await read();assert.equal(state.players[0].crystal,beforeSell.players[0].crystal-1);assert(state.players[0].wood>beforeSell.players[0].wood);evidence.marketDemandAndCurrency=true;
  await tab('Supply and salvage');const soldier=own.find(item=>item.kind==='unit'&&item.role!=='worker');assert(soldier,'Scenario needs an owned military unit.');const enemyWarehouse=initial.economy.structures.find(item=>item.kind==='warehouse'&&initial.entities.some(entity=>entity.id===item.entityId&&initial.teams[entity.side]!==initial.teams[0]&&visible(entity)));assert(enemyWarehouse,'Scenario needs a visible hostile warehouse.');await units([soldier.id]);await choose('Supply raid target',enemyWarehouse.entityId);await act('Raid supply');state=await read();assert(state.economy.tasks.some(item=>item.entityId===soldier.id&&item.kind==='raid'&&item.targetId===enemyWarehouse.entityId));evidence.militarySupplyRaidOrdered=true;
  const salvage=initial.economy.salvage.find(visible);assert(salvage,'Scenario needs visible salvage.');await units([workers[4].id]);await choose('Salvage deposit',salvage.id);await act('Collect salvage');state=await read();assert(state.economy.tasks.some(item=>item.entityId===workers[4].id&&item.kind==='collect'&&item.targetId===salvage.id));evidence.workerSalvageCollectionOrdered=true;
  await tab('Settlements and contracts');const warehouse=initial.economy.structures.find(item=>item.kind==='warehouse'&&item.stock.wood>=5&&own.some(entity=>entity.id===item.entityId&&entity.progress===1));assert(warehouse,'Scenario needs an owned stocked completed warehouse.');await choose('Worker delivery warehouse',warehouse.entityId);await act('Assign worker warehouse');state=await read();assert(state.economy.workerWarehouses.some(item=>item.entityId===workers[4].id&&item.warehouseId===warehouse.entityId));evidence.workerLocalDeliveryConfigured=true;
  await choose('Delivery caravan',caravans[1].entityId);await choose('Delivery stock source',warehouse.entityId);await choose('Delivery stock destination',hq.id);await fill('Wood delivery amount',5);await act('Deliver stock');state=await read();assert(state.economy.tasks.some(item=>item.entityId===caravans[1].entityId&&item.kind==='route'&&item.sourceId===warehouse.entityId&&item.targetId===hq.id));evidence.localStockDeliveryOrdered=true;
  const expansion=own.find(item=>item.kind==='building'&&item.role==='hq'&&item.progress===1&&Math.hypot(item.x-initial.starts[0].x,item.y-initial.starts[0].y)>=8&&!initial.economy.specializations.some(entry=>entry.entityId===item.id));assert(expansion,'Scenario needs an unspecialized expansion HQ.');await choose('Expansion settlement',expansion.id);await choose('Settlement specialization','research');const beforeSpecialization=await read();await act('Specialize settlement');state=await read();assert(state.economy.specializations.some(item=>item.entityId===expansion.id&&item.kind==='research'));assert.equal(state.players[0].wood,beforeSpecialization.players[0].wood-120);assert.equal(state.players[0].ore,beforeSpecialization.players[0].ore-80);assert.equal(state.players[0].crystal,beforeSpecialization.players[0].crystal-30);evidence.expansionSpecializationPaid=true;
  const contract=initial.economy.contracts.find(item=>item.status==='open'&&item.deadline>initial.time&&visible(item)&&own.some(entity=>entity.kind==='unit'&&Math.hypot(entity.x-item.x,entity.y-item.y)<=3));assert(contract,'Scenario needs a nearby open contract.');await choose('Resource contract',contract.id);await act('Accept contract');state=await read();assert.equal(state.economy.contracts.find(item=>item.id===contract.id).status,'accepted');await choose('Contract caravan',caravans[2].entityId);await choose('Contract stock source',hq.id);await act('Deliver contract');state=await read();assert(state.economy.tasks.some(item=>item.entityId===caravans[2].entityId&&item.contractId===contract.id));evidence.contractAcceptedAndDeliveryOrdered=true;
  await page.screenshot({path:`${out}/economy-panel.png`});await page.getByRole('button',{name:'Close economy and settlements',exact:true}).click();
  await page.waitForFunction(({contractId,oreId,raiderId,collectorId})=>{const s=window.rts?.state,e=s?.economy;return e?.groves.some(g=>g.resourceId)&&e.structures.filter(item=>['deep-mine','warehouse','extractor'].includes(item.kind)).every(item=>s.entities.find(entity=>entity.id===item.entityId)?.progress===1)&&e.contracts.find(item=>item.id===contractId)?.status==='complete'&&e.ledgers[0].traded.crystal>0&&e.ledgers[0].raided.wood>0&&e.ledgers[0].salvaged.wood>0&&[raiderId,collectorId].every(id=>!e.tasks.some(task=>task.entityId===id)&&Object.values(e.cargo.find(item=>item.entityId===id)?.stock??{}).every(value=>value<=1e-8))&&s.resources.find(r=>r.id===oreId)?.amount>0;},{contractId:contract.id,oreId:ore.id,raiderId:soldier.id,collectorId:workers[4].id},{timeout:180000});
  state=await read();evidence.actualConstructionAndGroveMaturity=true;evidence.completedRoutePaidFromFiniteMarket=state.economy.ledgers[0].traded.crystal>0;evidence.raidAndSalvageReachedOwnedStorage=state.economy.ledgers[0].raided.wood>0&&state.economy.ledgers[0].salvaged.wood>0;evidence.completedContractReward=state.economy.ledgers[0].contractRewards.crystal>0;
  const planted=state.economy.groves.find(item=>item.x===grove.x&&item.y===grove.y),tree=state.resources.find(item=>item.id===planted.resourceId);assert(tree&&tree.amount>0);const worker=state.entities.find(item=>item.id===workers[0].id&&item.hp>0);assert(worker);
  // The native minimap centers each target without altering simulation state or bypassing input.
  const center=async(point)=>{const minimap=page.locator('#minimap');await minimap.waitFor({state:'visible'});const rect=await minimap.boundingBox();assert(rect,'The minimap is not available for battlefield targeting.');const dimensions=await page.evaluate(()=>({width:window.rts.state.width,height:window.rts.state.height}));await page.mouse.click(rect.x+rect.width*point.x/dimensions.width,rect.y+rect.height*point.y/dimensions.height);};
  const screen=async(point,lift=0)=>page.evaluate(({point,lift})=>{const canvas=document.querySelector('#game-canvas canvas'),rect=canvas.getBoundingClientRect(),r=window.rts,density=canvas.width/rect.width,zoom=r.camera.zoom;const wx=1600+(point.x-point.y)*32,wy=80+(point.x+point.y)*16-lift;return {x:rect.left+((wx-r.camera.x)*zoom+canvas.width/2*(1-zoom))/density,y:rect.top+((wy-r.camera.y)*zoom+canvas.height/2*(1-zoom))/density};},{point,lift});
  const clickTarget=async(point,lift,options={})=>{await center(point);const pixel=await screen(point,lift),viewport=page.viewportSize();assert(viewport&&pixel.x>=0&&pixel.x<viewport.width&&pixel.y>=0&&pixel.y<viewport.height,'Centered battlefield target is outside the browser viewport.');await page.mouse.click(pixel.x,pixel.y,options);};
  await clickTarget(worker,40);await page.waitForFunction(id=>window.rts?.selected.includes(id),worker.id);const priorHarvest=state.economy.ledgers[0].gathered.wood;await clickTarget(tree,20,{button:'right'});await page.waitForFunction(({id,target})=>window.rts?.state.entities.find(e=>e.id===id)?.order.type==='gather'&&window.rts.state.entities.find(e=>e.id===id)?.order.target===target,{id:worker.id,target:tree.id});await page.waitForFunction(previous=>window.rts?.state.economy.ledgers[0].gathered.wood>previous,priorHarvest,{timeout:60000});evidence.canvasHarvestDepositedWood=true;
  const engineer=initial.entities.find(e=>e.definitionId==='core:fairies-engineer'),commander=initial.entities.find(e=>e.definitionId==='core:fairies-commander');
  if(engineer&&commander){await clickTarget(engineer,40);await page.waitForFunction(id=>window.rts.selected.includes(id),engineer.id);for(const name of ['Temporary bridge','Field barricade','Field repair'])assert(await page.getByRole('button',{name,exact:true}).isVisible());await clickTarget(commander,40);await page.waitForFunction(id=>window.rts.selected.includes(id),commander.id);assert(await page.getByRole('button',{name:'Queen’s Step',exact:true}).isVisible());evidence.nativeSpecialistSelectionAndControls=true;await page.screenshot({path:`${out}/specialist-controls.png`});}
  if(initial.world){
    assert.equal(initial.world.levels.length,2);assert(initial.contentHash,'Mixed fixture must pin its mod content.');assert(initial.art.loaded,'Pinned content artwork must load with vector economy definitions.');evidence.mixedWorldAndPinnedArtLoaded=true;
    const caveWorker=initial.entities.find(e=>e.side===0&&e.role==='worker'&&e.level===1),caveCrystal=initial.resources.find(r=>r.kind==='crystal'&&r.level===1&&visible(r)),hidden=initial.resources.find(r=>r.kind==='crystal'&&r.level===1&&r.amount===777);assert(caveWorker&&caveCrystal&&hidden);assert(initial.visible.includes(Math.floor(hidden.y)*initial.width+Math.floor(hidden.x)),'The hidden cavern crystal must share coordinates with a visible surface tile.');assert(!visible(hidden),'Coincident surface visibility must not disclose cavern ore.');
    await page.locator('.world-tools > summary').click();await page.getByRole('group',{name:'World tools',exact:true}).getByLabel('Map level',{exact:true}).selectOption('1');await page.waitForFunction(()=>window.rts.viewLevel===1);await page.locator('[data-economy-launch]').click();await tab('Resources');await units([caveWorker.id]);
    const options=await page.getByLabel('Crystal deposit',{exact:true}).locator('option').evaluateAll(options=>options.map(o=>({value:o.value,disabled:o.disabled})));assert(!options.some(o=>o.value===String(hidden.id)));
    await choose('Crystal deposit',caveCrystal.id);const beforeCave=await read();await act('Build crystal extractor');state=await read();const caveStructure=state.economy.structures.find(e=>e.kind==='extractor'&&e.resourceId===caveCrystal.id);assert(caveStructure);assert.equal(state.entities.find(e=>e.id===caveStructure.entityId).level,1);assert.equal(state.players[0].wood,beforeCave.players[0].wood-100);assert.equal(state.players[0].ore,beforeCave.players[0].ore-90);assert.equal(state.players[0].crystal,beforeCave.players[0].crystal-15);evidence.nativeCavernEconomyPaymentAndLayer=true;
    await page.screenshot({path:`${out}/cavern-economy.png`});await page.getByRole('button',{name:'Close economy and settlements',exact:true}).click();await page.waitForFunction(id=>window.rts.state.entities.find(e=>e.id===id)?.progress===1,caveStructure.entityId,{timeout:60000});const caveBuilt=(await read()).entities.find(e=>e.id===caveStructure.entityId);await clickTarget(caveBuilt,40);await page.waitForFunction(id=>window.rts.selected.includes(id),caveStructure.entityId);await page.screenshot({path:`${out}/cavern-battlefield.png`});await page.getByRole('group',{name:'World tools',exact:true}).getByLabel('Map level',{exact:true}).selectOption('0');await page.locator('.world-tools > summary').click();
  }
  await page.screenshot({path:`${out}/completed-battlefield.png`});await writeFile(`${out}/completed-state.json`,JSON.stringify(await read(),null,2));
  await page.locator('[data-session-tool="saves"]').click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export save',exact:true}).click();await (await downloadPromise).saveAs(`${out}/commanded-session.json`);const saved=JSON.parse(await readFile(`${out}/commanded-session.json`,'utf8'));assert(saved.game.state.economy);assert.equal(saved.game.state.economy.specializations.some(item=>item.entityId===expansion.id),true);evidence.economySaveExport=true;
  await page.locator('[data-session-tab="report"]').click();await page.getByLabel('Bug description',{exact:true}).fill('Economy UI browser proof');const reportPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download bug report',exact:true}).click();await (await reportPromise).saveAs(`${out}/report.json`);const report=JSON.parse(await readFile(`${out}/report.json`,'utf8'));assert.equal(report.versions.buildId,buildId,'Served application is stale. Rebuild before this proof.');assert(report.session.game.state.economy);evidence.economyReportExport=true;
  result.sessionEquality=await nativeSessionEquality(page,context,{saved,report});evidence.completedSaveAndReplayReloaded=true;
  assert.equal(Object.keys(evidence).length,25,'Final mixed fixture must execute all 25 intended economy checks.');assert(Object.values(evidence).every(value=>value===true));result.passed=true;
  assert.deepEqual(errors,[]);result.scope='Real browser controls, construction, growth and harvested income, completed routes, finite market rewards, raids, salvage, contracts and full native save/report/reload/replay equality.';console.log(JSON.stringify(evidence));
}catch(error){result.passed=false;result.error=String(error);if(page)await page.screenshot({path:`${out}/failure.png`}).catch(()=>{});await writeFile(`${out}/failure.json`,JSON.stringify(result,null,2));throw error;}finally{await browser.close();result.browserClosed=true;await finishEconomyProof(context,result,'proof.json');}
