import assert from 'node:assert/strict';
import {mkdir,writeFile} from 'node:fs/promises';
import {resolve,join} from 'node:path';
import {execFileSync} from 'node:child_process';

const {chromium}=await import(process.env.OVF_PLAYWRIGHT_MODULE??'playwright');
const base=process.argv[2]??'http://127.0.0.1:9241',out=resolve(process.env.OVF_MODES_BROWSER_EVIDENCE??'docs/evidence/assembled-modes/browser');
await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});
const contexts=[],profiles=[],errors=[],result={base,sourceCommit:execFileSync('git',['rev-parse','HEAD'],{encoding:'utf8'}).trim(),checks:[],builds:[]};
let phase='open production app';
const record=(name,data=true)=>{result.checks.push({name,data});console.log(`${name}: ${JSON.stringify(data)}`);};
async function profile(name){const context=await browser.newContext({viewport:{width:1440,height:1000},acceptDownloads:true});contexts.push(context);const page=await context.newPage(),value={name,page,snapshots:[],sent:[],receipts:[]};profiles.push(value);page.on('pageerror',error=>errors.push({name,message:error.message}));page.on('websocket',socket=>{socket.on('framesent',event=>{try{const message=JSON.parse(event.payload);if(message.kind==='command')value.sent.push(message);}catch{}});socket.on('framereceived',event=>{try{const message=JSON.parse(event.payload);if(message.kind==='snapshot')value.snapshots.push(message);if(message.kind==='commandAck')value.receipts.push(message);}catch{}});});await page.goto(base,{waitUntil:'domcontentloaded'});result.builds.push({profile:name,...await page.evaluate(()=>({scripts:[...document.querySelectorAll('script[type="module"][src]')].map(node=>node.src),styles:[...document.querySelectorAll('link[rel="stylesheet"]')].map(node=>node.href)}))});return value;}
async function waitBattle(page,mode){await page.waitForFunction(mode=>window.rts?.mode===mode,mode,{timeout:60000});await page.waitForSelector('.loading-battle[hidden]',{state:'attached',timeout:60000});}
async function openObjectives(page){await page.locator('[data-objective-tool="progress"]').click();await page.waitForSelector('.objective-overlay:not([hidden])');}
async function closeObjectives(page){await page.getByRole('button',{name:'Close objectives',exact:true}).click();await page.waitForSelector('.objective-overlay[hidden]',{state:'attached'});}
async function moveArmy(profile,target){const {page}=profile;await page.keyboard.press('F2');await page.waitForFunction(()=>window.rts.selected.length>0);const minimap=await page.locator('#minimap').boundingBox(),dimensions=await page.evaluate(()=>({width:window.rts.state.width,height:window.rts.state.height}));await page.mouse.click(minimap.x+target.x/dimensions.width*minimap.width,minimap.y+target.y/dimensions.height*minimap.height);const canvas=await page.locator('#game-canvas canvas').boundingBox(),camera=await page.evaluate(()=>window.rts.camera),projected={x:1600+(target.x-target.y)*32,y:80+(target.x+target.y)*16};await page.mouse.click(canvas.x+(projected.x-camera.x)*camera.zoom*canvas.width/camera.width,canvas.y+(projected.y-camera.y)*camera.zoom*canvas.height/camera.height,{button:'right'});}
async function guest(profile){await profile.page.getByRole('button',{name:'Online',exact:true}).click();await profile.page.getByRole('button',{name:'Play as guest',exact:true}).click();await profile.page.waitForSelector('.online-account:not([hidden])');}
async function refresh(profile){await profile.page.getByRole('button',{name:'Refresh lobbies',exact:true}).click();}
async function exportReplay(page,name){await page.locator('[data-session-tool="replay"]').click();const download=page.waitForEvent('download');await page.getByRole('button',{name:'Export replay',exact:true}).click();const path=join(out,name);await (await download).saveAs(path);await page.getByRole('button',{name:'Close session tools',exact:true}).click();return path;}

try{
 const local=await profile('local-custom-hill'),page=local.page;
 phase='custom rules through normal menu';await page.locator('.mod-library > summary').click();await page.getByRole('button',{name:'Install Lantern Keepers example',exact:true}).click();await page.locator('#map-size').selectOption('small');await page.getByLabel('Enable team match setup',{exact:true}).check();await page.getByLabel('Victory mode',{exact:true}).selectOption('hill');await page.getByLabel('Hill capture seconds',{exact:true}).fill('3');await page.getByLabel('Hill hold seconds',{exact:true}).fill('60');await page.getByLabel('Enable army draft',{exact:true}).check();await page.getByLabel('Draft ban rounds',{exact:true}).fill('0');await page.getByLabel('Draft pick rounds',{exact:true}).fill('1');await page.getByLabel('Draft turn seconds',{exact:true}).fill('60');
 await page.getByRole('button',{name:'Play Lantern Keepers',exact:true}).click();await waitBattle(page,'local');await page.waitForSelector('.objective-overlay:not([hidden])');await page.getByRole('button',{name:'Pick Lantern Duelist',exact:true}).click();await page.waitForFunction(()=>window.rts.state.draft.status==='complete',{},{timeout:15000});
 const setup=await page.evaluate(()=>({faction:window.rts.state.players[0].faction,rules:window.rts.state.rules,picks:window.rts.state.draft.picks,starter:window.rts.state.entities.find(e=>e.side===0&&e.kind==='unit'&&e.role!=='worker').definitionId}));assert.equal(setup.faction,'lantern:keepers');assert.equal(setup.rules.mode,'hill');assert.equal(setup.starter,'lantern:duelist');assert.ok(setup.picks[0].includes('lantern:duelist'));assert.match(await page.locator('.objective-tag').textContent(),/Capture and defend the hill/);record('Normal mod launch retains custom rules and drafts the exact custom starter',setup);
 await page.screenshot({path:join(out,'local-custom-draft.png')});await closeObjectives(page);const hill=await page.evaluate(()=>window.rts.state.objectives.hill);await moveArmy(local,hill);await page.waitForFunction(()=>window.rts.state.entities.some(e=>e.side===0&&e.definitionId==='lantern:duelist'&&['move','attackMove','attack'].includes(e.order.type)));await page.screenshot({path:join(out,'local-hill-marker.png')});record('Normal canvas order and the main HUD use the active hill match');
 const replayPath=await exportReplay(page,'local-custom-hill.replay.json');await page.locator('[data-session-tool="replay"]').click();await page.getByLabel('Import replay JSON',{exact:true}).setInputFiles(replayPath);await page.getByRole('button',{name:'Import replay',exact:true}).click();await waitBattle(page,'replay');await page.getByRole('button',{name:'Close session tools',exact:true}).click();await openObjectives(page);assert.match(await page.locator('.objective-panel h3').first().textContent(),/King of the hill/);assert.equal(await page.evaluate(()=>window.rts.readOnly),true);await closeObjectives(page);record('Exported custom objective replay reopens through normal session tools');
 await page.locator('[data-session-tool="photo"]').click();await page.waitForSelector('.photo-mode');assert.equal(await page.locator('[data-objective-tool="progress"]').isVisible(),false);await page.getByRole('button',{name:'Exit photo mode',exact:true}).click();record('Photo mode hides objective controls and overlays');
 phase='hosted lobby draft';const host=await profile('host'),other=await profile('guest');await guest(host);await guest(other);
 await host.page.getByLabel('Lobby map size',{exact:true}).selectOption('small');await host.page.getByLabel('Lobby Victory mode',{exact:true}).selectOption('relic');await host.page.getByLabel('Lobby Relic count',{exact:true}).fill('1');await host.page.getByLabel('Lobby Relics needed to win',{exact:true}).fill('1');await host.page.getByLabel('Lobby Relic hold seconds',{exact:true}).fill('120');await host.page.getByLabel('Lobby Enable army draft',{exact:true}).check();await host.page.getByLabel('Lobby Draft ban rounds',{exact:true}).fill('0');await host.page.getByLabel('Lobby Draft pick rounds',{exact:true}).fill('1');await host.page.getByRole('button',{name:'Create lobby',exact:true}).click();await host.page.waitForSelector('.online-current:not([hidden])');const id=(await host.page.locator('.online-lobby-id').textContent()).split(' · ')[0].trim();await refresh(other);await other.page.getByRole('button',{name:`Join lobby ${id}`,exact:true}).click();await other.page.waitForSelector('.online-current:not([hidden])');await refresh(host);
 assert.match(await other.page.locator('.online-received-rule-values').textContent(),/Relic control/);await host.page.locator('.online-current [data-draft-choice="orc-ranged"]').click();await refresh(other);await other.page.locator('.online-current [data-draft-choice="fairy-melee"]').click();await refresh(host);await host.page.locator('[data-online="ready"]').click();await refresh(other);await other.page.locator('[data-online="ready"]').click();await refresh(host);await host.page.screenshot({path:join(out,'hosted-relic-lobby.png')});await host.page.getByRole('button',{name:'Start match',exact:true}).click();await waitBattle(host.page,'online');await refresh(other);await other.page.locator('.online-current [data-online="rejoin"]').click();await waitBattle(other.page,'online');
 const hosted=await host.page.evaluate(()=>({rules:window.rts.state.rules,draft:window.rts.state.draft,starter:window.rts.state.entities.find(e=>e.side===0&&e.kind==='unit'&&e.role!=='worker').definitionId,simulationEnabled:window.rts.simulationEnabled}));assert.equal(hosted.rules.mode,'relic');assert.equal(hosted.starter,'orc-ranged');assert.equal(hosted.simulationEnabled,false);record('Real server lobby preserves both picks, mode rules and exact starting definition in Phaser',hosted);
 await openObjectives(host.page);await host.page.waitForSelector('[data-relic-id="1"]');const relic=host.snapshots.at(-1).view.objectives.relics[0];assert.match(await host.page.locator('.objective-panel-relic').textContent(),/Relic 1/);await closeObjectives(host.page);await moveArmy(host,relic);
 await host.page.waitForFunction(point=>window.rts.state.entities.some(e=>e.side===0&&e.kind==='unit'&&e.role!=='worker'&&Math.hypot(e.x-point.x,e.y-point.y)<=1.5),relic,{timeout:45000});await openObjectives(host.page);await host.page.getByRole('button',{name:'Collect relic 1',exact:true}).click();await host.page.waitForFunction(()=>document.querySelector('.objective-panel-relic button')?.textContent==='Drop relic',{},{timeout:10000});assert.equal(host.sent.at(-1).command.type,'collectRelic');assert.equal(host.receipts.at(-1).accepted,true);await host.page.screenshot({path:join(out,'hosted-relic-collected.png')});record('Main objective control collects a relic through an accepted server command',host.receipts.at(-1));
 await host.page.getByRole('button',{name:'Drop relic 1',exact:true}).click();await host.page.waitForFunction(()=>document.querySelector('.objective-panel-relic button')?.textContent==='Collect relic',{},{timeout:10000});assert.equal(host.sent.at(-1).command.type,'dropRelic');assert.equal(host.receipts.at(-1).accepted,true);await closeObjectives(host.page);await host.page.screenshot({path:join(out,'hosted-relic-marker.png')});record('Main objective control drops the carried relic through the authoritative server',host.receipts.at(-1));
 await openObjectives(other.page);assert.match(await other.page.locator('.objective-panel h3').first().textContent(),/Relic control/);await other.page.screenshot({path:join(out,'guest-relic-objectives.png')});record('Guest main objectives show the received relic mode and shared public progress');
 assert.deepEqual(errors,[]);record('All production profiles have no page errors');result.passed=true;
}catch(error){result.passed=false;result.phase=phase;result.error=error.stack??String(error);for(const value of profiles)try{await value.page.screenshot({path:join(out,`${value.name}-failure.png`)});}catch{}throw error;}
finally{result.errors=errors;await writeFile(join(out,'results.json'),JSON.stringify(result,null,2));await Promise.all(contexts.map(context=>context.close()));await browser.close();}
