import assert from 'node:assert/strict';
import { mkdir,writeFile } from 'node:fs/promises';
const { chromium }=await import(process.env.OVF_PLAYWRIGHT_MODULE??'playwright');
const url=process.argv[2]??'http://127.0.0.1:5365',out=process.argv[3]??'docs/evidence/world-systems-20261001';await mkdir(out,{recursive:true});
const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),evidence={url,checks:[],errors:[]};
try{
 for(const biome of ['desert','marsh','snow','forest']){
  const context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage();page.on('pageerror',e=>evidence.errors.push(e.message));
  await page.goto(url);await page.getByLabel('World biome',{exact:true}).selectOption(biome);await page.locator('#map-size').selectOption('small');await page.getByRole('button',{name:/Begin skirmish/}).click();await page.waitForFunction(b=>window.rts?.state.world?.biome===b,biome,{timeout:60000});await page.waitForSelector('.loading-battle[hidden]',{state:'attached',timeout:60000});
  const initial=await page.evaluate(()=>({biome:window.rts.state.world.biome,terrain:[...new Set(window.rts.state.terrain)],levels:window.rts.state.world.levels.length,transitions:window.rts.state.world.transitions.length,viewLevel:window.rts.viewLevel,tick:window.rts.state.tick}));assert.equal(initial.levels,2);assert.equal(initial.transitions,2);assert.equal(initial.viewLevel,0);assert(initial.terrain.includes({desert:'sand',marsh:'mud',snow:'snow',forest:'forest'}[biome]));evidence.checks.push({name:`${biome} launches through menu`,...initial});
  await page.locator('.world-tools > summary').click();await page.getByText('Owned troops by level',{exact:true}).click();const select=page.getByRole('button',{name:/^melee #/}).first();await select.click();const actor=(await page.evaluate(()=>window.rts.selected))[0];assert(actor>0);await page.getByRole('button',{name:'Traverse entrance',exact:true}).first().click();await page.waitForFunction(id=>window.rts.state.entities.find(e=>e.id===id)?.level===1,actor,{timeout:20000});await page.getByLabel('Map level',{exact:true}).selectOption('1');await page.waitForFunction(()=>window.rts.viewLevel===1);await page.waitForFunction(id=>{const s=window.rts.state,u=s.entities.find(e=>e.id===id);return s.visible[0].has(s.width*s.height+Math.floor(u.y)*s.width+Math.floor(u.x));},actor);const underground=await page.evaluate(id=>{const s=window.rts.state,u=s.entities.find(e=>e.id===id),key=s.width*s.height+Math.floor(u.y)*s.width+Math.floor(u.x);return {id,level:u.level,caveVisible:s.visible[0].has(key),surfaceVisible:s.visible[0].has(key-s.width*s.height),caveExplored:[...s.explored[0]].filter(k=>k>=s.width*s.height).length};},actor);assert(underground.caveVisible);assert(underground.caveExplored>0);evidence.checks.push({name:`${biome} real entrance and independent cavern view`,...underground});await page.screenshot({path:`${out}/${biome}-cavern.png`});
  // Native troop selection and the same bidirectional entrance bring it back to the surface.
  await page.getByText('Owned troops by level',{exact:true}).click();await page.getByRole('button',{name:new RegExp(`^melee #${actor} `)}).click();await page.getByRole('button',{name:'Traverse entrance',exact:true}).first().click();await page.waitForFunction(id=>window.rts.state.entities.find(e=>e.id===id)?.level===0,actor,{timeout:10000});evidence.checks.push({name:`${biome} return through cave entrance`,id:actor});await page.getByLabel('Map level',{exact:true}).selectOption('0');await page.screenshot({path:`${out}/${biome}-surface.png`});await context.close();
 }
 assert.deepEqual(evidence.errors,[]);await writeFile(`${out}/browser-world.json`,JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence,null,2));
}catch(error){evidence.failure=String(error.stack??error);await writeFile(`${out}/browser-world-failure.json`,JSON.stringify(evidence,null,2));throw error;}finally{await browser.close();}
