import assert from 'node:assert/strict';
import {readFile,writeFile,mkdir,readdir} from 'node:fs/promises';
import {createHash} from 'node:crypto';
const {chromium}=await import(process.env.OVF_PLAYWRIGHT_MODULE??'playwright');
const base=process.argv[2]??'http://127.0.0.1:5295';
const out='work/hundred-features';await mkdir(out,{recursive:true});
const sourceHash=createHash('sha256');for(const path of (await readdir('src',{recursive:true})).filter(path=>/\.(ts|css)$/.test(path)).sort()){sourceHash.update(path);sourceHash.update(await readFile(`src/${path}`));}const expectedBuildId=sourceHash.digest('hex');
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});
const evidence={},errors=[];
try {
 const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});
 page.on('pageerror',error=>errors.push(error.message));
 await page.goto(base);
 await page.locator('#map-size').selectOption('small');
 await page.locator('.begin-match').click();
 await page.waitForSelector('.loading-battle[hidden]',{state:'attached',timeout:60000});
 await page.waitForFunction(()=>window.rts?.state.tick>5);
 await page.locator('[data-session-tool="saves"]').click();
 const savedTick=await page.evaluate(()=>window.rts.state.tick);
 await page.getByLabel('Save name',{exact:true}).fill('Browser match');
 await page.getByRole('button',{name:'Save match',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.session-save-list')?.textContent.includes('Browser match'));
 assert.equal(await page.evaluate(()=>window.rts.state.tick),savedTick);evidence.modalPausesSimulation=true;
 await page.getByRole('button',{name:'Close session tools',exact:true}).click();
 await page.waitForFunction(tick=>window.rts.state.tick>tick,savedTick);
 await page.locator('[data-session-tool="saves"]').click();
 await page.getByRole('button',{name:'Load Browser match',exact:true}).click();
 await page.waitForFunction(tick=>{try{return window.rts?.state.tick===tick;}catch{return false;}},savedTick);
 await page.waitForFunction(()=>document.querySelector('.session-notice')?.textContent.includes('Loaded Browser match'));
 await page.waitForSelector('.loading-battle[hidden]',{state:'attached',timeout:60000});
 evidence.namedSaveLoadsExactTick=true;
 const exportPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export save',exact:true}).click();
 const saveDownload=await exportPromise;await saveDownload.saveAs(`${out}/browser-save.json`);
 const saved=JSON.parse(await readFile(`${out}/browser-save.json`,'utf8'));assert.equal(saved.game.state.tick,savedTick);evidence.saveExportIncludesReplay=!!saved.replay;
 const invalid={...saved,version:999};await page.getByLabel('Import save JSON',{exact:true}).setInputFiles({name:'invalid.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(invalid))});
 await page.getByRole('button',{name:'Import save',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.session-notice')?.textContent.includes('Unsupported session'));
 assert.equal(await page.evaluate(()=>window.rts.state.tick),savedTick);evidence.failedImportKeepsMatch=true;
 await page.locator('[data-session-tab="production"]').click();
 const hq=page.locator('[data-production-building]').first();
 await hq.locator('[data-recruit="worker"]').click();
 await page.waitForFunction(()=>window.rts.state.entities.find(e=>e.side===0&&e.role==='hq').queue.length===1);
 evidence.globalProductionUsesRealCommand=true;
 await page.locator('[data-session-tab="controls"]').click();
 const pan=page.locator('[data-binding-action="cameraRight"]');await pan.focus();await page.keyboard.press('r');
 await page.getByRole('button',{name:'Apply Pan right shortcut',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.session-notice')?.textContent.includes('Updated Pan right'));
 await page.getByRole('button',{name:'Close session tools',exact:true}).click();
 assert.equal(await page.evaluate(()=>window.rts.paused),false);
 const right=await page.evaluate(()=>window.rts.camera.x);await page.keyboard.press('ArrowLeft');
 await page.waitForFunction(before=>window.rts.camera.x<before,right);
 const x=await page.evaluate(()=>window.rts.camera.x);await page.keyboard.press('r');
 await page.waitForFunction(before=>window.rts.camera.x>before,x);evidence.reboundKeyboardWorksInFullApp=true;
 await page.keyboard.press('F9');await page.waitForSelector('.photo-controls:not([hidden])');
 assert.equal(await page.locator('.war-hud').isVisible(),false);
 const photoTick=await page.evaluate(()=>window.rts.state.tick);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.rts.state.tick),photoTick);
 const photoPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download photo',exact:true}).click();
 const photo=await photoPromise;await photo.saveAs(`${out}/battlefield-photo.png`);assert((await readFile(`${out}/battlefield-photo.png`)).length>1000);evidence.photoDownloadsCanvas=true;
 await page.getByRole('button',{name:'Exit photo mode',exact:true}).click();
 await page.locator('[data-session-tool="report"]').click();await page.getByLabel('Bug description',{exact:true}).fill('Browser verification report');
 await page.getByRole('button',{name:'Preview report',exact:true}).click();await page.waitForSelector('[aria-label="Bug report preview"]:not([hidden])');
 assert((await page.getByLabel('Bug report preview',{exact:true}).innerText()).includes('Build version'));evidence.reportPreviewShowsVersions=true;
 const reportPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Download bug report',exact:true}).click();const report=await reportPromise;await report.saveAs(`${out}/browser-report.json`);
 const reportData=JSON.parse(await readFile(`${out}/browser-report.json`,'utf8'));assert.equal(reportData.format,'orcs-vs-fairies/bug-report');assert.equal(reportData.session.replay.finalTick,reportData.session.game.state.tick);assert.equal(reportData.versions.buildId,expectedBuildId,'Build identity is stale: rebuild the preview or restart the development server.');evidence.reportContainsMatchingReplay=true;
 await page.locator('[data-session-tab="replay"]').click();
 const fixture=JSON.parse(await readFile(process.argv[3]??`${out}/current-replay.json`,'utf8'));
 await page.getByLabel('Import replay JSON',{exact:true}).setInputFiles({name:'complete-replay.json',mimeType:'application/json',buffer:Buffer.from(JSON.stringify(fixture))});
 await page.getByRole('button',{name:'Import replay',exact:true}).click();
 await page.waitForFunction(()=>document.querySelector('.session-notice')?.textContent.includes('Replay loaded'),null,{timeout:60000});
 await page.waitForFunction(tick=>{try{return window.rts?.state.tick===tick;}catch{return false;}},fixture.initial.state.tick,{timeout:60000});
 assert.equal(await page.evaluate(()=>window.rts.state.tick),fixture.initial.state.tick);
 await page.locator('[data-session-tab="analysis"]').click();
 await page.waitForSelector('[data-session-page="analysis"] svg');
 const analysisText=await page.locator('[data-session-page="analysis"]').innerText();
 assert(analysisText.includes(`${fixture.analysis.length} recorded samples`));
 assert.equal(await page.locator('[data-analysis-technology-tick]').count(),fixture.technologies.length);
 assert((await page.locator('[data-session-page="analysis"] svg').count())>=8);evidence.fullAnalysisAvailableAtOpeningTick=true;
 const technologyLink=page.locator('[data-analysis-technology-tick]').first(),technologyTick=Number(await technologyLink.getAttribute('data-analysis-technology-tick'));
 await technologyLink.click();await page.waitForFunction(tick=>window.rts.state.tick===tick,technologyTick);evidence.technologyLinkSeeksReplay=true;
 await page.locator('[data-session-tab="analysis"]').click();
 const samplePoint=page.locator('circle[data-analysis-tick="0"]').first();await samplePoint.focus();await samplePoint.press('Enter');await page.waitForFunction(()=>window.rts.state.tick===0);evidence.chartKeyboardLinkSeeksReplay=true;
 const slider=page.getByLabel('Replay tick',{exact:true});await slider.press('End');
 await page.waitForFunction(tick=>window.rts?.state.tick===tick,fixture.finalTick,{timeout:60000});
 evidence.replaySeeksFullMatch=true;
 await page.getByLabel('Replay perspective',{exact:true}).selectOption('1');
 await page.locator('[data-session-tab="analysis"]').click();
 await page.waitForSelector('[data-session-page="analysis"] svg');assert((await page.locator('[data-session-page="analysis"] svg').count())>=8);assert((await page.locator('[data-session-page="analysis"]').innerText()).includes('Technology timing'));evidence.fullMatchChartsVisible=true;
 await page.screenshot({path:`${out}/analysis.png`});
 await page.getByRole('button',{name:'Close session tools',exact:true}).click();
 await page.locator('#technology-button').click();await page.waitForSelector('.technology-tree[open]');
 assert((await page.locator('.technology-tree').innerText()).includes('Tender'));assert(!(await page.locator('.technology-tree').innerText()).includes('Scrapper'));evidence.technologyTreeUsesReplayPerspective=true;
 await page.getByRole('button',{name:'Close technology tree',exact:true}).click();await page.locator('[data-session-tool="replay"]').click();
 await page.locator('[data-session-tab="replay"]').click();await slider.press('Home');
 await page.waitForFunction(()=>window.rts.state.tick===0);
 await page.getByRole('button',{name:'Play replay',exact:true}).click();await page.getByRole('button',{name:'Close session tools',exact:true}).click();
 await page.waitForFunction(()=>window.rts.state.tick>0);evidence.replayPlayIntentSurvivesModal=true;
 await page.locator('[data-session-tool="replay"]').click();await page.getByRole('button',{name:'Pause replay',exact:true}).click();await page.getByRole('button',{name:'Close session tools',exact:true}).click();
 const pausedTick=await page.evaluate(()=>window.rts.state.tick);await page.waitForTimeout(150);assert.equal(await page.evaluate(()=>window.rts.state.tick),pausedTick);evidence.replayPauseIntentSurvivesModal=true;
 await page.screenshot({path:`${out}/integrated-game.png`});
 assert.deepEqual(errors,[]);
 await writeFile(`${out}/session-browser-proof.json`,JSON.stringify({base,buildId:expectedBuildId,evidence,errors},null,2));console.log(JSON.stringify(evidence));
} finally {await browser.close();}
