import assert from 'node:assert/strict';
import {mkdir,readFile,writeFile} from 'node:fs/promises';
const {chromium}=await import(process.env.OVF_PLAYWRIGHT_MODULE??'playwright'),url=process.argv[2]??'http://127.0.0.1:5365',out=process.argv[3]??'docs/evidence/world-systems-20261001';await mkdir(out,{recursive:true});const manifest=JSON.parse(await readFile('work/world-browser/manifest.json','utf8'));
const browser=await chromium.launch({headless:true,args:['--no-sandbox']}),context=await browser.newContext({viewport:{width:1440,height:900}}),page=await context.newPage(),evidence={url,checks:[],errors:[]};page.on('pageerror',e=>evidence.errors.push(e.message));
await page.addInitScript(()=>{window.worldProofPad=null;Object.defineProperty(navigator,'getGamepads',{value:()=>[window.worldProofPad]});});
const selectTroop=async id=>{const summary=page.getByText('Owned troops by level',{exact:true}),details=summary.locator('..');if(await details.getAttribute('open')===null)await summary.click();await page.getByRole('button',{name:new RegExp(`^[a-z]+ #${id} `)}).click();await page.waitForFunction(id=>window.rts.selected.includes(id),id);};
const load=async name=>{await page.locator('[data-session-tool="saves"]').click();await page.getByLabel('Import save JSON',{exact:true}).setInputFiles(`work/world-browser/${name}.json`);await page.getByRole('button',{name:'Import save',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.session-notice')?.textContent.includes('Save loaded'),null,{timeout:60000});await page.waitForSelector('.loading-battle[hidden]',{state:'attached',timeout:60000});await page.getByRole('button',{name:'Close session tools',exact:true}).click();const details=page.locator('.world-tools');if(await details.getAttribute('open')===null)await page.locator('.world-tools > summary').click();};
try{
 await page.goto(url);await load('neutral');await selectTroop(manifest.neutral.supportActor);await page.waitForFunction(()=>window.rts.viewLevel===1);
 const cycleTarget=await page.evaluate(id=>{const owned=window.rts.state.entities.filter(e=>e.side===0&&e.hp>0).sort((a,b)=>a.id-b.id),index=owned.findIndex(e=>e.id===id),next=owned[(index-1+owned.length)%owned.length];return {id:next.id,level:next.level??0};},manifest.neutral.supportActor);
 await page.evaluate(()=>{document.activeElement?.blur();window.worldProofPad={index:0,id:'world proof controller',mapping:'standard',connected:true,axes:[0,0,0,0],buttons:Array(17).fill(0)};});await page.waitForTimeout(100);await page.evaluate(()=>{window.worldProofPad.buttons[4]=1;});await page.waitForFunction(target=>window.rts.viewLevel===target.level&&window.rts.selected.includes(target.id),cycleTarget);await page.evaluate(()=>{window.worldProofPad.buttons[4]=0;});evidence.checks.push({name:'Controller previous selection follows the selected troop level',target:cycleTarget});
 await selectTroop(manifest.neutral.supportActor);await page.evaluate(()=>document.activeElement?.blur());await page.keyboard.press('Space');const hq=await page.evaluate(()=>{const e=window.rts.state.entities.find(e=>e.side===0&&e.role==='hq'&&e.hp>0);return {id:e.id,level:e.level??0};});await page.waitForFunction(level=>window.rts.viewLevel===level,hq.level);evidence.checks.push({name:'Stronghold camera control switches back to the stronghold level',hq});await selectTroop(manifest.neutral.supportActor);
 const before=await page.evaluate(()=>({...window.rts.state.players[0],units:window.rts.state.entities.filter(e=>e.side===0&&e.kind==='unit').length}));await page.getByRole('button',{name:'Support village / collect supplies',exact:true}).click();await page.waitForFunction(id=>window.rts.state.world.sites.find(s=>s.id===id).loyalty[0]===60,manifest.neutral.village);const supported=await page.evaluate(id=>({owner:window.rts.state.world.sites.find(s=>s.id===id).owner,stock:window.rts.state.world.sites.find(s=>s.id===id).reward,player:window.rts.state.players[0]}),manifest.neutral.village);assert.equal(supported.owner,0);assert.equal(before.wood-supported.player.wood,80);await page.getByRole('button',{name:'Support village / collect supplies',exact:true}).click();await page.waitForFunction(id=>window.rts.state.world.sites.find(s=>s.id===id).rewarded.includes(0),manifest.neutral.village);await page.getByRole('button',{name:'Recruit local defender',exact:true}).click();await page.waitForFunction(n=>window.rts.state.entities.filter(e=>e.side===0&&e.kind==='unit').length===n+1,before.units);evidence.checks.push({name:'Village request, supplies and real defender through controls',...supported});
 // F2 is the shipped army selection control; it selects the cave cavalry and supported melee.
 await page.locator('canvas').first().click({position:{x:800,y:570}});await page.keyboard.press('F2');await page.waitForFunction(()=>window.rts.selected.length>=3);await page.getByRole('button',{name:'Attack monster den',exact:true}).click();await page.waitForFunction(id=>{const s=window.rts.state;return s.world.sites.find(site=>site.id===id).rewarded.length===1&&s.world.creatures.filter(c=>c.site===id).every(c=>c.hp===0);},manifest.neutral.den,{timeout:25000});const den=await page.evaluate(id=>({site:window.rts.state.world.sites.find(s=>s.id===id),creatures:window.rts.state.world.creatures.filter(c=>c.site===id).map(({id,hp,maxHp,respawnAt})=>({id,hp,maxHp,respawnAt})),players:window.rts.state.players}),manifest.neutral.den);assert.equal(den.site.reward.wood,0);evidence.checks.push({name:'Normal army order clears real monster den and finite reward',...den});
 await page.locator('canvas').first().click({position:{x:800,y:570}});await page.keyboard.press('F2');await page.getByRole('button',{name:'Capture relic',exact:true}).click();await page.waitForFunction(()=>window.rts.state.world.sites.find(s=>s.kind==='relic').owner===0,null,{timeout:25000});evidence.checks.push({name:'Native army captures contested cavern relic',site:await page.evaluate(()=>window.rts.state.world.sites.find(s=>s.kind==='relic'))});await page.screenshot({path:`${out}/neutral-services-and-relic.png`});
 await page.locator('[data-session-tool="saves"]').click();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export save',exact:true}).click();const download=await downloadPromise;await download.saveAs(`${out}/world-browser-save.json`);const saved=JSON.parse(await readFile(`${out}/world-browser-save.json`,'utf8'));assert.equal(saved.game.state.world.sites.find(s=>s.kind==='relic').owner,0);assert(saved.game.state.entities.some(e=>e.level===1));evidence.checks.push({name:'Native export contains world, underground troops and neutral progress',tick:saved.game.state.tick});await page.getByRole('button',{name:'Close session tools',exact:true}).click();
 await load('surface');await selectTroop(manifest.surface.fireActor);const woodBefore=await page.evaluate(id=>window.rts.state.resources.find(r=>r.id===id).amount,manifest.surface.wood),fuelPoint=await page.evaluate(id=>{const r=window.rts.state.resources.find(r=>r.id===id);return `${Math.floor(r.x)+.5},${Math.floor(r.y)+.5}`;},manifest.surface.wood);await page.getByLabel('Forest work tile',{exact:true}).selectOption(fuelPoint);await page.getByRole('button',{name:'Ignite',exact:true}).click();await page.waitForFunction(id=>window.rts.state.resources.find(r=>r.id===id).amount===0,manifest.surface.wood,{timeout:8000});assert(woodBefore>0);evidence.checks.push({name:'Native ignition consumes finite timber and creates fire',fires:await page.evaluate(()=>window.rts.state.world.fires)});const {x,y}=manifest.surface.firebreak;await page.getByLabel('Forest work tile',{exact:true}).selectOption(`${x},${y}`);await page.getByRole('button',{name:'Clear firebreak',exact:true}).click();await page.waitForFunction(p=>window.rts.state.terrain[Math.floor(p.y)*window.rts.state.width+Math.floor(p.x)]==='grass',manifest.surface.firebreak);evidence.checks.push({name:'Native worker clears forest firebreak',point:manifest.surface.firebreak});
 await selectTroop(manifest.surface.attackActor);await page.getByRole('button',{name:'Attack bridge',exact:true}).first().click();await page.waitForFunction(id=>window.rts.state.world.bridges.find(b=>b.id===id).hp===0,manifest.surface.bridge,{timeout:12000});const destroyed=await page.evaluate(id=>({bridge:window.rts.state.world.bridges.find(b=>b.id===id),revision:window.rts.state.world.revision}),manifest.surface.bridge);evidence.checks.push({name:'Native unit attack destroys crossing and invalidates terrain',...destroyed});await selectTroop(manifest.surface.repairActor);await page.getByRole('button',{name:'Rebuild bridge',exact:true}).first().click();await page.waitForFunction(id=>{const b=window.rts.state.world.bridges.find(b=>b.id===id);return b.hp===b.maxHp;},manifest.surface.bridge,{timeout:25000});evidence.checks.push({name:'Native workers pay and rebuild the crossing',bridge:await page.evaluate(id=>window.rts.state.world.bridges.find(b=>b.id===id),manifest.surface.bridge)});await page.screenshot({path:`${out}/forest-fire-and-bridge.png`});
 await load('dusk');await page.waitForFunction(()=>document.querySelector('.world-tools > summary')?.textContent.includes('dusk'),null,{timeout:8000});evidence.checks.push({name:'World day calendar advances to dusk in the production match',summary:await page.locator('.world-tools > summary').textContent()});
 await load('thaw');await selectTroop(manifest.thaw.actor);await page.waitForFunction(()=>document.querySelector('.world-tools').textContent.includes('Lake ice thaws in'),null,{timeout:4000});evidence.checks.push({name:'Winter thaw countdown is visible before the crossing changes',description:await page.locator('.world-tools-body > p').textContent()});await page.waitForFunction(id=>{const actor=window.rts.state.entities.find(e=>e.id===id);return actor.hp>0&&actor.hp<actor.maxHp;},manifest.thaw.actor,{timeout:15000});await page.waitForFunction(()=>document.querySelector('.world-tools > summary')?.textContent.includes('spring'));const thawed=await page.evaluate(id=>{const s=window.rts.state,e=s.entities.find(e=>e.id===id);return {actor:{id:e.id,x:e.x,y:e.y,hp:e.hp,maxHp:e.maxHp,order:e.order},iceTiles:s.world.iceTiles,season:document.querySelector('.world-tools > summary').textContent};},manifest.thaw.actor);assert.equal(thawed.iceTiles.length,0);assert.notEqual(`${thawed.actor.x},${thawed.actor.y}`,`${manifest.thaw.point.x},${manifest.thaw.point.y}`);evidence.checks.push({name:'Production winter crossing thaws and rescues an injured worker to a bank',...thawed});await page.screenshot({path:`${out}/winter-thaw-rescue.png`});
 assert.deepEqual(evidence.errors,[]);await writeFile(`${out}/browser-world-actions.json`,JSON.stringify(evidence,null,2));console.log(JSON.stringify(evidence,null,2));
}catch(error){evidence.failure=String(error.stack??error);await page.screenshot({path:`${out}/browser-world-actions-failure.png`});await writeFile(`${out}/browser-world-actions-failure.json`,JSON.stringify(evidence,null,2));throw error;}finally{await context.close();await browser.close();}
