import assert from 'node:assert/strict';
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { createHash } from 'node:crypto';
import { execFileSync } from 'node:child_process';
import path from 'node:path';
import { fileURLToPath } from 'node:url';
import { worldSourceProof, checkCurrentSession, downloadWorldBuildReport } from './world/proof-common.mjs';
const {chromium}=await import(process.env.OVF_PLAYWRIGHT_MODULE??'playwright');
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
process.chdir(root);
const base=process.argv[2]??'http://127.0.0.1:5186',out=path.resolve(process.env.OVF_MOD_EVIDENCE_DIR??path.join(root,'work/hundred-features/mods'));await mkdir(out,{recursive:true});
for(const name of ['browser-proof.json','browser-failure.json'])await readFile(path.join(out,name)).then(()=>{throw new Error(`Refusing retained browser output ${path.join(out,name)}`);},error=>{if(error.code!=='ENOENT')throw error;});
const source=await worldSourceProof(process.env.OVF_PRODUCTION_SOURCE_COMMIT??process.env.OVF_SOURCE_PIN),sourceFingerprint=source.buildId,sourceCommit=source.sourcePin;
assert.equal(execFileSync('git',['diff',sourceCommit,'--name-only','--','scripts/verify_mods.mjs','scripts/mods/scenario.ts'],{cwd:root,encoding:'utf8'}).trim(),'','Mod drivers must match the recorded source');
const scriptSha256=createHash('sha256').update(await readFile(fileURLToPath(import.meta.url))).digest('hex');
const staticDir=path.resolve(process.env.OVF_PROOF_DIST??'dist');
execFileSync(process.execPath,[path.join(root,'scripts/verify_served_build.mjs'),base,path.join(out,'served-build.json'),staticDir],{cwd:root,stdio:'pipe'});
const servedBuild=JSON.parse(await readFile(path.join(out,'served-build.json'),'utf8'));assert.equal(servedBuild.commit,sourceCommit);assert.equal(servedBuild.sourceSha256,sourceFingerprint);
const fixture=JSON.parse(await readFile(path.join(out,'scenario.json'),'utf8'));assert.equal(fixture.game.version,source.saveVersion,'Regenerate the mod fixture from SAVE4');
const fixtureManifest=JSON.parse(await readFile(path.join(out,'fixture-manifest.json'),'utf8'));assert.equal(fixtureManifest.sourceCommit,sourceCommit);assert.equal(fixtureManifest.sourceFingerprint,sourceFingerprint);assert.equal(fixtureManifest.saveVersion,source.saveVersion);assert.equal(fixtureManifest.simulationRevision,source.simulationRevision);
for(const [name,digest] of Object.entries(fixtureManifest.files))assert.equal(createHash('sha256').update(await readFile(path.join(out,name))).digest('hex'),digest,`Mod input changed after fixture generation: ${name}`);
function assertReplay(replay){assert.equal(replay.initial.version,4);assert.equal(replay.checksumVersion,4);assert.equal(replay.simulationRevision,'4.0.0');}
const browser=await chromium.launch({headless:true,args:['--disable-dev-shm-usage']});const errors=[],evidence={};
const page=await browser.newPage({viewport:{width:1440,height:1000},acceptDownloads:true});page.on('pageerror',error=>errors.push(error.message));
async function waitReady(){await page.waitForSelector('.loading-battle[hidden]',{state:'attached',timeout:60000});await page.waitForFunction(()=>window.rts?.art?.loaded,null,{timeout:60000});}
async function point(x,y){return page.evaluate(({x,y})=>{const c=window.rts.camera;return {x:((1600+(x-y)*32-c.x)*c.zoom+innerWidth/2*(1-c.zoom)),y:((80+(x+y)*16-c.y)*c.zoom+innerHeight/2*(1-c.zoom))};},{x,y});}
async function clickEntity(entity,{right=false}={}){const p=await point(entity.x,entity.y);await page.mouse.click(p.x,p.y-30,{button:right?'right':'left'});}
async function snapshot(){return page.evaluate(()=>({tick:window.rts.state.tick,players:window.rts.state.players,entities:window.rts.state.entities,contentHash:window.rts.state.content.hash,art:window.rts.art,selected:window.rts.selected}));}
try{
 await page.goto(base);const pageBuild=await page.evaluate(()=>({moduleScripts:[...document.querySelectorAll('script[type=module]')].map(el=>el.src),stylesheets:[...document.querySelectorAll('link[rel=stylesheet]')].map(el=>el.href)}));evidence.pageBuild=pageBuild;await page.locator('.mod-library > summary').click();
 await page.getByLabel('Choose mod package JSON').setInputFiles(`${out}/lantern.json`);await page.getByRole('button',{name:'Import package',exact:true}).click();await page.waitForSelector('.mod-library-card');const packageValue=JSON.parse(await readFile(`${out}/lantern.json`,'utf8'));assert((await page.locator('.mod-library-card').innerText()).includes(packageValue.hash));evidence.importPinsManifestHash=true;
 await page.getByRole('button',{name:'Play Lantern Keepers',exact:true}).click();await waitReady();assert.equal((await snapshot()).players[0].faction,'lantern:keepers');evidence.normalModLaunch=true;
 await page.locator('[data-session-tool="saves"]').click();await page.getByLabel('Import save JSON',{exact:true}).setInputFiles(`${out}/scenario.json`);await page.getByRole('button',{name:'Import save',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.session-notice')?.textContent.includes('Save loaded'));await waitReady();await page.getByRole('button',{name:'Close session tools',exact:true}).click();
 const initial=await snapshot();await page.screenshot({path:`${out}/initial.png`});
 const sentinel=initial.entities.find(e=>e.definitionId==='lantern:sentinel');await clickEntity(sentinel);await page.waitForFunction(id=>window.rts.selected.includes(id),sentinel.id);assert.equal(await page.locator('#selection-name').innerText(),'Lantern Sentinel');await page.getByRole('button',{name:'Renewal',exact:true}).click();await page.waitForFunction(id=>window.rts.state.entities.find(e=>e.id===id).hp>=150,sentinel.id);evidence.customHealingThroughHud=true;
 const worker=(await snapshot()).entities.find(e=>e.side===0&&e.role==='worker');await clickEntity(worker);await page.waitForFunction(id=>window.rts.selected.includes(id),worker.id);await page.locator('[data-mode="build"]').click();await page.getByRole('button',{name:'Lantern Hall',exact:true}).click();
 const placement=JSON.parse(await readFile(`${out}/placement.json`,'utf8'));const p=await point(placement.x,placement.y);await page.mouse.click(p.x,p.y);await page.waitForFunction(()=>window.rts.state.entities.some(e=>e.definitionId==='lantern:hall'),null,{timeout:10000});await page.waitForFunction(()=>window.rts.state.entities.find(e=>e.definitionId==='lantern:hall').progress===1,null,{timeout:60000});evidence.customHallConstruction=true;
 const hall=(await snapshot()).entities.find(e=>e.definitionId==='lantern:hall');await clickEntity(hall);await page.waitForFunction(id=>window.rts.selected.includes(id),hall.id);await page.getByRole('button',{name:'Lantern Sentinel',exact:true}).click();await page.getByRole('button',{name:'Lantern Duelist',exact:true}).click();assert.deepEqual((await snapshot()).entities.find(e=>e.id===hall.id).queueDefinitionIds,['lantern:sentinel','lantern:duelist']);assert((await page.locator('#production-queue').innerText()).length>0);await page.waitForFunction(()=>window.rts.state.entities.some(e=>e.definitionId==='lantern:duelist'),null,{timeout:25000});evidence.twoSameRoleDefinitionsRecruit=true;
 await page.locator('#technology-button').click();await page.locator('[data-technology="lantern:bright-blades"]').click();await page.getByRole('button',{name:'Close technology tree',exact:true}).click();await page.waitForFunction(()=>window.rts.state.players[0].upgrades.includes('lantern:bright-blades'),null,{timeout:15000});evidence.customResearchUsesNormalTree=true;
 const duelist=(await snapshot()).entities.find(e=>e.definitionId==='lantern:duelist');await page.keyboard.press('F2');await page.getByRole('button',{name:`Select Lantern Duelist ${duelist.id}`,exact:true}).click();await page.waitForFunction(id=>window.rts.selected.includes(id),duelist.id);const enemy=(await snapshot()).entities.find(e=>e.side===1&&e.role==='melee');const minimap=await page.locator('#minimap').boundingBox();await page.mouse.click(minimap.x+enemy.x/36*minimap.width,minimap.y+enemy.y/36*minimap.height);await page.keyboard.press('a');const target=await point(enemy.x,enemy.y);await page.mouse.click(target.x,target.y);await page.waitForFunction(id=>window.rts.state.events.some(e=>e.type==='attack'&&e.source===id),duelist.id,{timeout:30000});evidence.customCombatDamage=true;
 await page.locator('[data-session-tool="saves"]').click();await page.getByLabel('Save name',{exact:true}).fill('Pinned Lantern match');await page.getByRole('button',{name:'Save match',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.session-save-list')?.textContent.includes('Pinned Lantern match'));const saved=await snapshot();const downloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export save',exact:true}).click();const download=await downloadPromise;await download.saveAs(`${out}/browser-save.json`);const file=JSON.parse(await readFile(`${out}/browser-save.json`,'utf8'));assert.equal(file.game.version,4);assertReplay(file.replay);assert.equal(file.game.state.content.hash,saved.contentHash);assert(file.replay.initial.state.content);evidence.savedReplayEmbedsPinnedArtwork=true;
 await page.getByRole('button',{name:'Load Pinned Lantern match',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.session-notice')?.textContent==='Loaded Pinned Lantern match.');await waitReady();assert.equal((await snapshot()).tick,saved.tick);assert.equal((await snapshot()).contentHash,saved.contentHash);evidence.browserSaveResumeExactTick=true;
 await page.locator('[data-session-tab="replay"]').click();const replayDownloadPromise=page.waitForEvent('download');await page.getByRole('button',{name:'Export replay',exact:true}).click();const replayDownload=await replayDownloadPromise;await replayDownload.saveAs(`${out}/browser-replay.json`);assertReplay(JSON.parse(await readFile(`${out}/browser-replay.json`,'utf8')));await page.getByLabel('Import replay JSON',{exact:true}).setInputFiles(`${out}/browser-replay.json`);await page.getByRole('button',{name:'Import replay',exact:true}).click();await page.waitForFunction(()=>document.querySelector('.session-notice')?.textContent.includes('Replay loaded'));await waitReady();await page.getByLabel('Replay tick',{exact:true}).press('End');await page.waitForFunction(tick=>window.rts.state.tick===tick,saved.tick);assert.equal((await snapshot()).contentHash,saved.contentHash);evidence.replaySeeksWithPinnedContent=true;
 await page.locator('[data-session-tab="saves"]').click();const replaySaveWaiting=page.waitForEvent('download');await page.getByRole('button',{name:'Export save',exact:true}).click();await (await replaySaveWaiting).saveAs(`${out}/browser-replay-final.save.json`);const replaySession=JSON.parse(await readFile(`${out}/browser-replay-final.save.json`,'utf8'));assert.equal(replaySession.game.version,4);assertReplay(replaySession.replay);assert.deepEqual(replaySession.game,file.game,'Replay seeking restores the complete native saved game');
 checkCurrentSession(file,source);checkCurrentSession(replaySession,source);evidence.nativeExports=['browser-save.json','browser-replay-final.save.json'];
 await downloadWorldBuildReport(page,{out,provenance:source},'browser-build-report.json',evidence);
 await page.getByRole('button',{name:'Close session tools',exact:true}).click();await page.screenshot({path:`${out}/gameplay.png`});assert.deepEqual(errors,[]);assert.deepEqual(await worldSourceProof(sourceCommit),source,'Source changed during mod proof');await writeFile(`${out}/browser-proof.json`,JSON.stringify({base,source,sourceCommit,sourceFingerprint,scriptSha256,servedBuild,evidence,errors,final:await snapshot()},null,2));console.log(JSON.stringify(evidence));
} catch(error){await page.screenshot({path:`${out}/failure.png`});await writeFile(`${out}/browser-failure.json`,JSON.stringify({base,source,sourceCommit,sourceFingerprint,scriptSha256,servedBuild,error:String(error),errors,evidence,state:await snapshot().catch(()=>null)},null,2));throw error;}finally{await browser.close();}
