import assert from 'node:assert/strict';
import { createGame } from '../../src/core/simulation';
import { FACTIONS, UPGRADES } from '../../src/core/content';
import { PlayerView } from '../../src/core/observation';
import { researchRequirement } from '../../src/core/progression';
const baseline=JSON.stringify(FACTIONS),upgrades=JSON.stringify(UPGRADES);
const options={controllers:['external','external'] as ['external','external'],mapSize:'small' as const};
const before=createGame('orcs',4127,'fairies',options);
const firstSnapshot=JSON.stringify(new PlayerView(0).observe(before));
const improved=createGame('orcs',4127,'fairies',{...options,improvements:{'feature-001':{},'feature-041':true,'feature-061':{layout:'river'}}});
const after=createGame('orcs',4127,'fairies',options);
assert.equal(JSON.stringify(FACTIONS),baseline);
assert.equal(JSON.stringify(UPGRADES),upgrades);
assert.deepEqual(after,before);
assert.equal(JSON.stringify(new PlayerView(0).observe(before)),firstSnapshot);
assert.equal(improved.entities.find(e=>e.side===0&&e.role==='melee')!.maxHp,165);
assert.equal(after.entities.find(e=>e.side===0&&e.role==='melee')!.maxHp,165);
assert.equal(FACTIONS.orcs.units.ranged.cooldown,1.4);
assert.equal(researchRequirement(before,0,'ranged-drills'),'Technology disabled for this match');
assert.equal(researchRequirement(improved,0,'ranged-drills'),'Requires Town Age');
const plainKeys=Object.keys(new PlayerView(0).observe(before).content.upgrades);
const enabledKeys=Object.keys(new PlayerView(0).observe(improved).content.upgrades);
assert.equal(plainKeys.length,7);assert.equal(enabledKeys.length,12);assert.equal(plainKeys.includes('ranged-drills'),false);
console.log(JSON.stringify({contentIsolation:true,earlierStatePreserved:true,ordinaryGamesIdentical:true,plainUpgradeCount:plainKeys.length,enabledUpgradeCount:enabledKeys.length,disabledUpgradeAdvertised:plainKeys.includes('ranged-drills'),orca:{meleeHp:165,rangedCooldown:1.4}}));
