import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { createConquestProfile, prepareConquestBattle, completeConquestBattle, decodeConquestProfile } from 'review-source/core/conquest';
import { captureScenario, issueScenarioCommand, stepScenario } from 'review-source/core/scenarios';
import { verifyScenarioRecording, scenarioStateEquals } from 'review-source/core/scenario-recordings';
import { solveConquest } from 'review-scripts/scenarios/conquest-strategy';
import { campaignArmy, prepareCampaignMission, createCampaignProfile, completeCampaignMission, decodeCampaignProfile, chooseCampaignBranch } from 'review-source/core/campaign';
import { solveMission } from 'review-scripts/scenarios/mission-strategy';
const privateArchiveDir = process.env.PRIVATE_ARCHIVE_DIR;
if (!privateArchiveDir) throw new Error('PRIVATE_ARCHIVE_DIR must name a private artifact directory');
mkdirSync(privateArchiveDir, { recursive: true });
const archive = (name: string, value: unknown) => writeFileSync(resolve(privateArchiveDir, `${name}.json`), JSON.stringify(value));
const assert = (test: unknown, msg: string) => { if (!test) throw new Error(msg); };
let profile = createConquestProfile('dwarves', 'casualty-reserve-review');
const first = prepareConquestBattle(profile, 'quarry');
const barracks = first.session.state.entities.find(e => e.side === 0 && e.role === 'barracks')!;
let recruited = 0;
while (issueScenarioCommand(first.session, 0, { type: 'train', id: barracks.id, role: 'ranged' })) recruited++;
assert(recruited > 0, 'no reinforcements accepted');
const worker = first.session.state.entities.find(e => e.side === 0 && e.kind === 'unit' && e.role === 'worker')!;
assert(issueScenarioCommand(first.session, 0, { type: 'move', ids: [worker.id], x: 24, y: 13 }), 'worker move rejected');
while ((worker.hp > 0 || barracks.queue.length) && first.session.state.tick < 1800) stepScenario(first.session);
assert(worker.hp === 0, 'worker did not die');
solveConquest(first.session);
assert(first.session.runtime.outcome === 'won', 'battle did not win');
const recording = first.recorder.archive(); archive('quarry-recording', recording); first.recorder.destroy();
assert(scenarioStateEquals(verifyScenarioRecording(recording), first.session), 'recording diverged');
profile = completeConquestBattle(first.profile, first.session, recording);
assert(!profile.army.some(s => s.entity.id === worker.id), 'dead worker retained');
assert(completeConquestBattle(profile, first.session, recording) === profile, 'result not idempotent');
profile = decodeConquestProfile(JSON.stringify(profile));
const next = prepareConquestBattle(profile, 'crossroads');
const units = next.session.state.entities.filter(e => e.side === 0 && e.kind === 'unit');
const reserves = profile.army.filter(s => !next.profile.active!.deployedIds.includes(s.entity.id));
assert(new Set(next.session.state.entities.map(e => e.id)).size === next.session.state.entities.length, 'duplicate entity id');
assert(new Set(next.profile.active!.deployedIds).size === next.profile.active!.deployedIds.length, 'duplicate deployed id');
assert(!units.some(e => e.role === 'worker'), 'casualty replaced by worker placeholder');
assert(units.every(e => e.hp === e.maxHp && e.cooldown === 0 && e.path.length === 0), 'survivor did not rest');
assert(next.profile.active!.deployedIds.every(id => profile.army.some(s => s.entity.id === id)), 'new id deployed as carryover');
assert(scenarioStateEquals(verifyScenarioRecording(next.recorder.archive()), next.session), 'initial carryover recording diverged');
console.log(JSON.stringify({battleTick: first.session.state.tick, deadWorker: worker.id, survivors: profile.army.map(s => [s.entity.id, s.entity.role]), nextDeployed: next.profile.active!.deployedIds, reserves: reserves.map(s => s.entity.id), recruited, outcome: first.session.runtime.outcome, reconstruction: 'ok'}));
solveConquest(next.session);
assert(next.session.runtime.outcome === 'won', 'next battle did not win');
const nextRecording = next.recorder.archive(); archive('crossroads-recording', nextRecording); next.recorder.destroy();
profile = completeConquestBattle(next.profile, next.session, nextRecording);
assert(reserves.every(s => profile.army.some(after => after.entity.id === s.entity.id)), 'reserve disappeared after next battle');
profile = decodeConquestProfile(JSON.stringify(profile));
console.log(JSON.stringify({afterSecondBattle: profile.army.map(s => s.entity.id), reservesRetained: reserves.map(s => s.entity.id), reconstruction: 'ok'}));
let campaign = createCampaignProfile('campaign-dwarves', 'campaign-idempotence-review');
for (let i = 0; i < 4; i++) {
 if (i === 2) campaign = chooseCampaignBranch(campaign, 'surveyor');
 const run = prepareCampaignMission(campaign); solveMission(run.session); assert(run.session.runtime.outcome === 'won', 'campaign did not win');
 const rec = run.recorder.archive(); archive(`campaign-chapter-${i+1}-recording`, rec); run.recorder.destroy(); campaign = completeCampaignMission(run.profile, run.session, rec);
 assert(completeCampaignMission(campaign, run.session, rec) === campaign, 'campaign result not idempotent');
 campaign = decodeCampaignProfile(JSON.stringify(campaign));
 assert(new Set(campaignArmy(campaign).map(s => s.entity.id)).size === campaignArmy(campaign).length, 'campaign duplicate carryover identity');
}
console.log(JSON.stringify({campaignChapters: campaign.history.length, army: campaignArmy(campaign).map(s => [s.entity.id,s.entity.role]), reconstruction:'ok'}));
